const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const store=require('./store.cjs');
const ROOT=path.resolve(__dirname,'../../hero-reviews'),ID=/^[a-z0-9][a-z0-9-]{0,79}$/;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function collection(id){if(!ID.test(id||''))throw Object.assign(Error('Choose a valid review collection.'),{status:400});const dir=path.join(ROOT,id);if(!fs.existsSync(path.join(dir,'collection.json')))throw Object.assign(Error('Review collection not found.'),{status:404});return{dir,...JSON.parse(fs.readFileSync(path.join(dir,'collection.json')))};}
function list(){if(!fs.existsSync(ROOT))return[];return fs.readdirSync(ROOT).filter(id=>ID.test(id)&&fs.existsSync(path.join(ROOT,id,'collection.json'))).map(id=>{const c=collection(id);return{id,title:c.title,count:c.count,createdAt:c.createdAt};});}
function createServer(){return http.createServer(async(req,res)=>{const json=(data,status=200)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};try{const host=req.headers.host||'';if(!/^(localhost|127\.0\.0\.1):\d+$/.test(host))return json({error:'Local review access only.'},403);const url=new URL(req.url,'http://'+host);if(!['GET','POST'].includes(req.method))return json({error:'Method not allowed'},405);
if(req.method==='POST'&&req.headers.origin!=='http://'+host)return json({error:'Save from this local review page.'},403);
const sendFile=(file,type)=>{if(!fs.existsSync(file))return json({error:'File not found'},404);res.writeHead(200,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res);};
if(url.pathname==='/api/hero-review'){const c=collection(url.searchParams.get('collection')),file=path.join(c.dir,url.searchParams.get('sandbox')==='1'?'feedback-sandbox.json':'feedback.json');if(req.method==='GET')return json(store.read(file));let text='';for await(const chunk of req){text+=chunk;if(Buffer.byteLength(text)>12000)return json({error:'Request too large'},413);}let input;try{input=JSON.parse(text);}catch{return json({error:'Invalid JSON'},400);}return json({decision:store.save(file,JSON.parse(fs.readFileSync(path.join(c.dir,'data.json'))),input)});}
if(req.method!=='GET')return json({error:'Method not allowed'},405);
if(url.pathname==='/api/review-collection'){const{dir,...info}=collection(url.searchParams.get('collection'));return json(info);}
if(url.pathname==='/source-needed/'||url.pathname==='/source-needed/index.html')return sendFile(path.join(__dirname,'source-needed/index.html'),'text/html; charset=utf-8');
if(url.pathname==='/source-needed/data.json')return sendFile(path.join(__dirname,'source-needed/data.json'),'application/json');
if(url.pathname==='/api/reviews')return json(list());
if(url.pathname==='/review/data.json'){const c=collection(url.searchParams.get('collection'));return sendFile(path.join(c.dir,'data.json'),'application/json');}
if(url.pathname==='/review/'||url.pathname==='/review/index.html')return sendFile(path.join(__dirname,'index.html'),'text/html; charset=utf-8');
if(['/review/review.js','/review/review.css'].includes(url.pathname))return sendFile(path.join(__dirname,path.basename(url.pathname)),url.pathname.endsWith('.js')?'text/javascript':'text/css');
const asset=url.pathname.match(/^\/assets\/([a-z0-9-]+)\/([a-f0-9]{64}\.(png|jpg|jpeg|webp))$/);if(asset){const c=collection(asset[1]);return sendFile(path.join(c.dir,'assets',asset[2]),asset[3]==='jpg'?'image/jpeg':'image/'+asset[3]);}
if(url.pathname==='/'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'});return res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Best Bottles — Review library</title><style>body{margin:0;background:#f5f3ef;color:#272722;font:16px/1.6 Arial}main{max-width:1050px;padding:40px 24px;margin:auto}h1{font:36px Georgia}.collections{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr));gap:20px}article{padding:24px;border:1px solid #d8cbb3;background:#fff}a{color:#186b89}code{overflow-wrap:anywhere}h2{font-size:22px}</style></head><body><main><p>BEST BOTTLES / IMAGE REVIEW</p><h1>Review library</h1><p><a href="/source-needed/">25 products needing source images →</a></p><p>Height grids, shoulder targets, source comparisons and feedback are preserved for each collection. Approvals belong to exact image versions; publishing remains separate.</p><div class="collections">${list().map(c=>`<article><h2>${esc(c.title)}</h2><p>${c.count} images</p><a href="/review/?collection=${c.id}&amp;view=all">Open review →</a><p><small>Collection: ${esc(c.id)}</small></p></article>`).join('')||'<p>No collections yet. Import a local image manifest to begin.</p>'}</div><p>Add another collection with <code>npm run review:heroes:import -- --id new-family --title "New family" --manifest /path/data.json --public-root /path/public</code>.</p></main></body></html>`);}
return json({error:'Not found'},404);
}catch(error){res.writeHead(error.status||500,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({error:error.status?error.message:'Review operation failed. Your previous saved feedback is preserved.'}));}});}
if(require.main===module){const i=process.argv.indexOf('--port'),port=Number(i>=0?process.argv[i+1]:3010);if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Choose a port between 1024 and 65535.');const server=createServer();server.on('error',e=>{console.error(e.code==='EADDRINUSE'?`Port ${port} is already in use. Try --port ${port+1}.`:e.message);process.exitCode=1;});server.listen(port,'127.0.0.1',()=>console.log(`Hero review library: http://localhost:${port}\nFeedback and assets: ${ROOT}\nStop with Ctrl+C. No Next.js, Convex or external credentials required.`));}
module.exports={createServer,collection,list,ROOT};
