"use client";

import { useMemo, useState } from "react";
import type { Ledger, LedgerRow, Kind } from "@/lib/asset-ledger/types";
import styles from "./ledger.module.css";
import SunburstSizing from "./SunburstSizing";
import ReuseQueue from "./ReuseQueue";
import StandardReview, {type BottleStandard} from "./StandardReview";

type Candidate = {state:string; sha256?:string; collection:string; bytesVerified?:boolean};
type Row = LedgerRow & {plate:LedgerRow['plate'] & {complete?:boolean; checksPassed?:boolean; sizeHold?:string; approval?:unknown; review?:unknown; candidate?:Candidate; sourcePath?:string; sourceHold?:unknown; masterSourceRecorded?:boolean; localCandidate?:unknown}; kit:LedgerRow['kit'] & {candidate?:Candidate}; hero:LedgerRow['hero'] & {candidate?:Candidate}};
type Group = {id:string;slug:string;family:string;capacityMl?:number;color?:string;skus:string[];indexedSkus:string[];sunburstSkus:string[];state:string};
type Snapshot = Ledger & {platePreparation?:{prepared:number;reviewable:number;held:number;approved:number;preserved:number};bottleStandards?:{standards:BottleStandard[]};groupRows:Group[];scope:{reviewOnly:number;groupRecords:number;duplicateProductRecords:number;missingSkuRecords:Array<{id:string;family:string;itemName:string}>;note:string};reviewAudit:{unclassified:unknown[];invalidAssets:unknown[];superseded:unknown[];orphanDecisions:unknown[]}};
const labels:Record<string,string> = {plated:'Checks passed', 'plated-no-capoff-by-design':'Checks passed · no cap-off needed', 'plated-wrong-size':'Size check failed','plated-legacy-source':'Master PSD needed','plated-cap-on-only':'Cap-off view missing','not-applicable':'Not required',none:'Not started',pending:'Awaiting review',rendered:'Awaiting review',held:'On hold',hold:'On hold',stale:'Recheck current image',changes_requested:'Changes requested',rejected:'Rejected','approved-not-published':'Approved · awaiting release','approved-not-indexed':'Locked · awaiting indexing','approved-not-locked':'Approved · lock needed','no-plate':'Plate needed first',live:'Complete · live kit',indexed:'Existing indexed image','evidence-missing':'Image evidence missing','measurement-stale':'Measurement needed','integrity-hold':'Integrity check failed',candidate:'Candidate prepared','prior-release':'Earlier hero · Sunburst needed',missing:'Hero needed',complete:'Complete · Sunburst'};
const label=(state:string)=>labels[state]??state.replaceAll('-',' ').replaceAll('_',' ');
function friendlyReason(reason?:string){
 if(!reason)return '';
 if(/alpha gate|transparen|touchesOwnEdge/i.test(reason))return 'The photographed part needs extraction review before it can be used.';
 if(/parity/i.test(reason))return 'The kit does not yet align with the current plate.';
 if(/source_preflight|basename|identity reconciliation/i.test(reason))return 'Verify the exact product and its master PSD source.';
 if(/independently recoverable|independent component/i.test(reason))return 'A separate photographed component is still needed.';
 if(/layer|blending|opacity/i.test(reason))return 'Review the original component layers in the master PSD.';
 return reason;
}
function rowState(r:Row,k:Kind){if(k==='plate')return r.plate.complete?'complete':r.plate.sizeHold||r.plate.sourceHold||(r.plate.sourcePath&&!r.plate.masterSourceRecorded)?'held':r.plate.checksPassed?'pending':r.plate.state;return r[k].state;}
function tone(state:string){return ['complete','live'].includes(state)?'done':['held','hold','stale','rejected','changes_requested','evidence-missing','measurement-stale','integrity-hold','plated-wrong-size','plated-legacy-source'].includes(state)?'blocked':state==='not-applicable'?'neutral':'waiting';}
function Badge({state,children}:{state:string;children?:React.ReactNode}){return <span className={`${styles.badge} ${styles[tone(state)]}`}>{children??label(state)}</span>;}
const titles:Record<Kind,string>={plate:'Bottle plates',kit:'Component kits',hero:'Sunburst heroes'};

export default function LedgerDashboard({snapshot,localReview=false}:{snapshot:Ledger;localReview?:boolean}){
 const data=snapshot as Snapshot;
 const [standards,setStandards]=useState(data.bottleStandards?.standards??[]);
 const [reviewId,setReviewId]=useState<string|null>(null);
 const [sizingId,setSizingId]=useState<string|null>(null);
 const activeStandard=standards.find(s=>s.id===reviewId);
 const sizingStandard=standards.find(s=>s.id===sizingId);
 const bostonReady=standards.filter(s=>s.family==='Boston Round'&&s.lockReadiness?.ready).length;
 const bostonLocked=standards.filter(s=>s.family==='Boston Round'&&s.state==='locked').length;
 const bostonFinalPending=standards.filter(s=>s.family==='Boston Round'&&s.finalCandidate?.ready&&s.finalCandidate.status!=='approved').length;
 const bostonFinalApproved=standards.filter(s=>s.family==='Boston Round'&&s.finalCandidate?.ready&&s.finalCandidate.status==='approved').length;
 const rows=data.rows as Row[];
 const products=useMemo(()=>(data.rows as Row[]).filter(r=>r.productRecord),[data.rows]);
 const [kind,setKind]=useState<Kind>('plate');const [family,setFamily]=useState('Boston Round');const [capacity,setCapacity]=useState('15');const [query,setQuery]=useState('');const [filter,setFilter]=useState('attention');const [page,setPage]=useState(0);
 const families=[...new Set([...products.map(r=>r.family),...data.groupRows.map(g=>g.family)])].sort();
 const counts={plate:{done:products.filter(r=>r.plate.complete).length,total:products.filter(r=>r.plate.state!=='not-applicable').length},kit:{done:products.filter(r=>r.kit.state==='live').length,total:products.filter(r=>r.kit.state!=='not-applicable').length},hero:{done:data.groupRows.filter(g=>g.state==='complete').length,total:data.groupRows.length}};
 const visible = useMemo(()=>{
   const candidates: Array<{id:string;name:string;description:string;state:string;row?:Row;group?:Group}> = kind==='hero'?data.groupRows.map(g=>({id:g.id,name:`${g.family}${g.capacityMl ? ` · ${g.capacityMl} mL`:''}${g.color?` · ${g.color}`:''}`,description:g.slug,state:g.state,group:g})):products.map(r=>({id:r.sku,name:r.sku,description:[r.capacityMl?`${r.capacityMl} mL`:null,r.color,r.applicator].filter(Boolean).join(' · '),state:rowState(r,kind),row:r}));
   const q=query.trim().toLowerCase();
   return candidates.filter(x=>(family==='all'||(x.row?.family??x.group?.family)===family)&&(capacity==='all'||(x.row?.capacityMl??x.group?.capacityMl)===Number(capacity))&&(!q||[x.name,x.description,...(x.group?.skus??[])].join(' ').toLowerCase().includes(q))&&(filter==='all'||filter==='attention'&&!['complete','live','not-applicable'].includes(x.state)||filter==='complete'&&['complete','live'].includes(x.state)||filter==='blocked'&&tone(x.state)==='blocked')).sort((a,b)=>(tone(a.state)==='blocked'?0:1)-(tone(b.state)==='blocked'?0:1)||a.name.localeCompare(b.name));
 },[data.groupRows,products,kind,family,capacity,query,filter]);
 const localFamily=products.filter(r=>(family==='all'||r.family===family)&&(capacity==='all'||r.capacityMl===Number(capacity)));
 const sizeHolds=localFamily.filter(r=>r.plate.sizeHold).length;
 const reset=()=>setPage(0);
 return <main className={styles.page}><div className={styles.shell}>
  <header className={styles.header}><div><a className={styles.back} href="/team">← Team hub</a><h1>Asset workbench</h1><p>One family at a time. Every plate, kit and hero accounted for.</p></div><div className={styles.snapshot}><span className={styles.dot}/>Local review · nothing shipped here<br/><small>Snapshot {new Date(data.generatedAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})} Pacific</small></div></header>
  <section aria-labelledby="next-title" className={styles.next}><div className={styles.step}>2</div><div><h2 id="next-title">Current focus: {family==='Boston Round'?'reuse and finish Boston Round by size':bostonFinalPending?'review the saved Boston image':bostonFinalApproved?'verify the approved Boston image on the website':bostonLocked>0?'match Sunburst images to the locked sizes':bostonReady?'review the Boston glass standards':'prepare the Boston glass standards'}</h2><p>{family==='Boston Round'?'Start with the reuse & gap queue below. Preserve existing files, reconcile approval evidence, and resolve the remaining gaps one size at a time.':bostonFinalPending?'The 30 mL image has been resized and saved. Open its final review card to approve the exact file or request changes.':bostonFinalApproved?'The saved 30 mL image has visual approval. Check its desktop/mobile product experience before a release-specific ship.':bostonLocked>0?`${bostonLocked} of 3 glass standards are locked. Open a Sunburst sizing preview below, then prepare the final image for its own review.`:bostonReady?`${bostonReady} measured comparisons are ready. Keep 15 and 60 mL at their current glass size; review the 30 mL increase, then lock each standard.`:'Prepare a verified bare-glass comparison for each size. Your existing reference approvals stay saved.'}</p></div><span className={`${styles.badge} ${styles.waiting}`}>In progress</span></section>
  {(family==='Boston Round'||family==='all')&&data.platePreparation&&<section className={styles.next}><div className={styles.step}>→</div><div><h2>Boston plates are ready for family review</h2><p>{data.platePreparation.preserved} earlier approvals preserved · {data.platePreparation.prepared} prepared candidates · {data.platePreparation.approved} candidate approvals · {data.platePreparation.held} held.</p><a className={styles.primaryAction} href="/team/asset-ledger?preview=1&view=completion">Open the family contact sheet and product previews →</a><p>Published coverage below changes only after an approved release.</p></div></section>}
  {localReview&&(family==='Boston Round'||family==='all')&&<section className={styles.next}><div className={styles.step}>3</div><div><h2>Boston kits: reuse the existing work</h2><p>21 candidates on preserved plates · 4 needing realignment · 98 to prepare. Component validation and kit approval remain separate.</p><a className={styles.primaryAction} href="/team/asset-ledger?preview=1&view=kits">Open Boston kit comparisons →</a></div></section>}
  <section aria-label="Overall progress" className={styles.metrics}>{(['plate','kit','hero'] as Kind[]).map((k,i)=><button key={k} className={`${styles.metric} ${kind===k?styles.selected:''}`} onClick={()=>{setKind(k);reset();}} aria-pressed={kind===k}>
   <span className={styles.metricTitle}><span className={styles.number}>{i+1}</span>{titles[k]}<span aria-hidden>↗</span></span><span className={styles.value}>{counts[k].done.toLocaleString()}<small> / {counts[k].total.toLocaleString()}</small></span>
   <span className={styles.metricCopy}>{k==='hero'?'product groups with approved, locked, indexed Sunburst':k==='plate'?'bottle SKUs checked and approved for current bytes':'applicable SKUs with a live kit'}</span>
   <span className={styles.track}><span style={{width:`${counts[k].total?100*counts[k].done/counts[k].total:0}%`}}/></span><span className={styles.remaining}>{(counts[k].total-counts[k].done).toLocaleString()} still need work</span>
  </button>)}</section>
  <div className={styles.context}><span>{data.groupRows.filter(g=>g.indexedSkus.length).length} groups already have an indexed hero. Older images remain visible; they do not complete the Sunburst goal.</span><details><summary>What counts as complete?</summary><p>Plates need the current image checks, required views and matching visual approval. Kits must be served against the current plate. Heroes need a matching Sunburst approval lock and a valid indexed image. This snapshot checks the configured development catalog, not production release health.</p></details></div>
  <section className={styles.familyPicker} aria-label="Choose your family"><div><h2>Choose a family</h2><p>This selection filters the size standards and all three asset lists below.</p></div><label className={styles.family}>Bottle family<select value={family} onChange={e=>{setFamily(e.target.value);setCapacity('all');setQuery('');setReviewId(null);setSizingId(null);reset();}}><option value="all">All families</option>{families.map(f=><option key={f}>{f}</option>)}</select></label></section>
  <ReuseQueue key={family} rows={rows} groups={data.groupRows} standards={standards} family={family} capacity={capacity} onCapacity={value=>{setCapacity(value);reset();}} generatedAt={data.generatedAt} onFinalReview={id=>{setReviewId(null);setSizingId(id);}}/>
  <section className={styles.standards} aria-labelledby="standards-title"><div className={styles.standardHeading}><div><h2 id="standards-title">{family==='all'?'All bottle':family} size standards</h2><p>{standards.filter(s=>(family==='all'||s.family===family)&&s.referenceDecision).length} reference choices approved · {standards.filter(s=>(family==='all'||s.family===family)&&s.lockReadiness?.ready).length} comparisons ready for your approval.</p></div><Badge state={standards.filter(s=>family==='all'||s.family===family).length>0&&standards.filter(s=>family==='all'||s.family===family).every(s=>s.state==='locked')?'complete':'pending'}>{standards.filter(s=>(family==='all'||s.family===family)&&s.state==='locked').length} / {standards.filter(s=>family==='all'||s.family===family).length} shared standards locked</Badge></div>
   <div className={styles.standardGrid}>{standards.filter(s=>family==='all'||s.family===family).map(s=><article key={s.id} className={styles.standardCard}><h3>{s.family} · {s.capacityMl} mL</h3><p>{s.colors.join(' · ')}</p><Badge state={s.state==='locked'?'complete':'pending'}>{s.state==='locked'?`Height locked · v${s.version}`:s.lockReadiness?.ready?'Ready to review & lock':s.sizingRequest?'Sizing requested':s.referenceDecision?'Reference chosen':'Reference proposed'}</Badge><p className={styles.standardNote}>{s.productGroupIds.length} product groups share this {s.state==='locked'?'locked':'proposed'} glass standard.</p>{(s.lockReadiness?.ready||s.state==='locked')&&s.preparedReview&&<img src={s.preparedReview.after.url} alt={`${s.capacityMl} mL master glass ready to review`} width={240} height={264}/>} <button className={s.state==='locked'?styles.focusSize:styles.primaryAction} aria-expanded={reviewId===s.id} onClick={()=>{setSizingId(null);setReviewId(reviewId===s.id?null:s.id);setFamily(s.family);setCapacity(String(s.capacityMl));setQuery('');reset();}}>{s.lockReadiness?.ready?'Review & lock':'Review'} {s.capacityMl} mL standard</button>{s.state==='locked'&&<button className={styles.primaryAction} aria-expanded={sizingId===s.id} onClick={()=>{setReviewId(null);setSizingId(s.id);setFamily(s.family);setCapacity(String(s.capacityMl));setKind('hero');setQuery('');reset();}}>{s.finalCandidate?`Review final ${s.capacityMl} mL image`:`Next: match ${s.capacityMl} mL Sunburst`}</button>}<button className={styles.focusSize} aria-pressed={family===s.family&&capacity===String(s.capacityMl)} onClick={()=>{setFamily(s.family);setCapacity(String(s.capacityMl));setQuery('');setFilter('attention');reset();}}>Work on {s.capacityMl} mL assets</button><details><summary>Reference &amp; previous decisions</summary><a href={s.reference.url} target="_blank" rel="noreferrer"><img src={s.reference.url} alt={`Proposed ${s.capacityMl} mL ${s.family} glass-size reference`} width={240} height={264}/></a><p>{s.reference.sku}</p><details><summary>Historical sizing decisions</summary><pre>{JSON.stringify(s.history,null,2)}</pre></details><small>Standard version {s.version} · reference SHA-256</small><code>{s.reference.sha256}</code></details></article>)}</div>
   {!standards.some(s=>family==='all'||s.family===family)&&<p>No verified physical standard is registered for this family yet. Reconcile its shapes and sizes, then prepare reference cards here. Its SKUs remain in the workspace below.</p>}
   {activeStandard&&<StandardReview key={activeStandard.id} standard={activeStandard} localReview={localReview} onSave={updated=>{setStandards(current=>current.map(s=>s.id===updated.id?updated:s));if(updated.state==='locked'&&updated.sizingRequest?.status==='approved'){setReviewId(null);setSizingId(updated.id);}}} onClose={()=>setReviewId(null)}/>}
   {sizingStandard&&<SunburstSizing key={sizingStandard.id} standard={sizingStandard} localReview={localReview} onCandidateSave={candidate=>setStandards(current=>current.map(s=>s.id===sizingStandard.id?{...s,finalCandidate:candidate}:s))} onClose={()=>setSizingId(null)} onReviewStandard={()=>{setSizingId(null);setReviewId(sizingStandard.id);}}/>}
   <p className={styles.standardRule}>One standard can serve multiple glass colors and closures with verified matching geometry. The glass stays fixed during component swaps. Each component needs verified scale and registration; changing an image never resets approved siblings.</p>
  </section>
  <section className={styles.workspace} aria-labelledby="family-title"><div className={styles.workspaceTop}><div><h2 id="family-title">Your family workspace</h2><p>Choose a family, then focus on one kind of asset.</p></div></div>
   <div className={styles.sizeControl}><label>Bottle size<select value={capacity} onChange={e=>{setCapacity(e.target.value);reset();}}><option value="all">All sizes</option>{[...new Set(products.filter(r=>family==='all'||r.family===family).map(r=>r.capacityMl).filter((n):n is number=>n!==null&&n>0))].sort((a,b)=>a-b).map(n=><option key={n} value={n}>{n} mL</option>)}</select></label></div>
   <div className={styles.tabs} role="group" aria-label="Asset type">{(['plate','kit','hero'] as Kind[]).map(k=><button key={k} aria-pressed={kind===k} className={kind===k?styles.activeTab:''} onClick={()=>{setKind(k);reset();}}>{titles[k]}</button>)}</div>
   <div className={styles.focus}><strong>{family==='all'?'All families':family}{capacity!=='all'?` · ${capacity} mL`:''} · {titles[kind]}</strong><p>{kind==='plate'&&sizeHolds>0?`${sizeHolds} earlier sizing findings remain on hold. Comparing a different set of images does not resolve them.`:kind==='kit'?'Confirm real photographed parts and alignment with the current plate before approval.':kind==='hero'?'Review once per product group. A prepared candidate is separate from the indexed image.':'Check source, sizing and required views before visual approval.'}</p></div>
   <div className={styles.controls}><label>Find a product<input type="search" placeholder="Search SKU, size, color or group" value={query} onChange={e=>{setQuery(e.target.value);reset();}}/></label><label>Show<select value={filter} onChange={e=>{setFilter(e.target.value);reset();}}><option value="attention">Needs attention</option><option value="blocked">On hold / blocked</option><option value="complete">Complete</option><option value="all">Everything</option></select></label></div>
   <div className={styles.resultLine}><span role="status">{visible.length} {kind==='hero'?(visible.length===1?'product group':'product groups'):(visible.length===1?'SKU':'SKUs')}{visible.length>20?` · showing ${page*20+1}–${Math.min(visible.length,(page+1)*20)}`:''}</span><div className={styles.legend}><span className={styles.done}>● Complete</span><span className={styles.waiting}>● Needs work</span><span className={styles.blocked}>● Blocked</span></div></div>
   <div className={styles.items}>{visible.slice(page*20,(page+1)*20).map(item=><article className={styles.item} key={item.id}><div className={styles.itemHeading}><div><h3>{item.name}</h3><p>{item.description}</p></div><Badge state={item.state}>{kind==='plate'&&item.state==='complete'?'Complete · plate':kind==='plate'&&item.state==='pending'?'Visual review needed':undefined}</Badge></div>
    {item.row?.plate.sizeHold&&kind==='plate'?<p className={styles.reason}>Size finding remains open. Verify against the correct physical bottle profile.</p>:item.row&&<p className={styles.reason}>{friendlyReason(kind==='plate'?item.row.plate.reason:kind==='kit'?item.row.kit.reason:'')}</p>}
    {item.group&&<p className={styles.reason}>{item.group.skus.length} catalog SKUs · {item.group.sunburstSkus.length?'Sunburst approval lock matches the indexed bytes.':item.group.indexedSkus.length?'An earlier hero is indexed. Sunburst work remains.':'No valid indexed hero found.'}</p>}
    <details className={styles.evidence}><summary>View evidence &amp; next action</summary>{item.row?<><p><strong>Next action:</strong> {['live','complete'].includes(item.state)?'Retain the verified asset and include it in release checks.':item.state==='not-applicable'?'No bottle asset required for this product type.':tone(item.state)==='blocked'?'Resolve the recorded hold, prepare a same-zoom comparison, then request review.':'Prepare or review the exact SKU image. Approval and release remain separate.'}</p><p><strong>Catalog group:</strong> {item.row.groupSlug??'Unmatched — identity reconciliation required'}</p><pre>{JSON.stringify(item.row[kind],null,2)}</pre></>:<><p><strong>Next action:</strong> {item.state==='complete'?'Verify the indexed hero in the actual product experience before release.':'Find the latest exact-SKU candidate; review and lock its bytes before indexing.'}</p><p><strong>Indexed hero SKUs:</strong> {item.group?.indexedSkus.join(', ')||'None'}</p><p><strong>Catalog SKUs:</strong> {item.group?.skus.join(', ')||'No matching product records — scope hold'}</p><details><summary>Candidate evidence</summary><pre>{JSON.stringify(rows.filter(r=>item.group?.skus.includes(r.sku)&&r.hero.candidate).map(r=>({sku:r.sku,...r.hero.candidate})),null,2)}</pre></details></>}</details>
   </article>)}</div>
   {!visible.length&&<div className={styles.empty}><h3>No items in this view</h3><p>Try another status or clear your search. Hidden results are still included in the ledger.</p><button onClick={()=>{setFilter('all');setQuery('');reset();}}>Show everything in this family</button></div>}
   {visible.length>20&&<nav aria-label="Results pages" className={styles.pagination}><button disabled={page===0} onClick={()=>setPage(p=>p-1)}>← Previous</button><span>Page {page+1} of {Math.ceil(visible.length/20)}</span><button disabled={(page+1)*20>=visible.length} onClick={()=>setPage(p=>p+1)}>Next →</button></nav>}
  </section>
  <section className={styles.reconciliation}><h2>Nothing falls through the gaps</h2><p>Unmatched records stay visible. Scope reconciliation is still open; these counts are not a declaration that the entire legacy catalog is complete.</p><details><summary>{data.scope.reviewOnly} review-only SKUs need a catalog match</summary><ul>{rows.filter(r=>!r.productRecord).map(r=><li key={r.sku}>{r.sku} · {r.family}</li>)}</ul></details><details><summary>{data.scope.missingSkuRecords.length} catalog records have no SKU</summary><ul>{data.scope.missingSkuRecords.map(r=><li key={r.id}>{r.family} · {r.itemName||r.id}</li>)}</ul></details>{data.scope.duplicateProductRecords>0&&<details><summary>{data.scope.duplicateProductRecords} duplicate product records · identity review required</summary><p>Resolve the duplicate exact SKU records before treating the catalog scope as final. No record was removed by this dashboard.</p></details>}<details><summary>Evidence checks and snapshot sources</summary><p>{data.reviewAudit.unclassified.length} unclassified collection copies · {data.reviewAudit.invalidAssets.length} missing or changed review assets · {data.reviewAudit.superseded.length} superseded collections excluded.</p><pre>{JSON.stringify({scope:data.scope,reviewAudit:data.reviewAudit,sources:data.sources},null,2)}</pre></details></section>
  <footer className={styles.footer}>Review → exact-byte approval → release-specific “ship” → verify the published experience.</footer>
 </div></main>;
}
