"use client";
import {useState,useEffect,useRef} from 'react';
import styles from './contact-sheet.module.css';
import {requiresAssembledClosure} from '@/lib/products/closure-presentation';

type View={label:string;url:string;sha256:string;width:number;height:number};
type Row={sku:string;graceSku:string;capacityMl:number|null;color:string;productGroupId?:string;groupSlug?:string;applicator:string|null;capColor:string|null;itemName:string;views:View[];eligible:boolean;appearanceApproved?:boolean;appearanceBinding?:string;reason:string;status:string;notes:string;binding:string};
export type PlateSheet={family:string;rows:Row[];excludedDuplicates?:Array<{sku:string}>;revision:number;token:string;createdAt:string;ledgerAt:string};

export default function PlateContactSheet({initial,localReview,finalPreparation,reviewScope='full'}:{initial:PlateSheet;localReview:boolean;finalPreparation?:{preparedPairs:number;legacySourceDecisions:number;reviewUrl:string;status:string;publicationState?:string}|null;reviewScope?:'full'|'cap-on-appearance'}){
 const [sheet,setSheet]=useState(initial),[size,setSize]=useState('all'),[scope,setScope]=useState('eligible'),[flags,setFlags]=useState<Record<string,string>>({}),[loaded,setLoaded]=useState<Set<string>>(new Set()),[failed,setFailed]=useState<Set<string>>(new Set()),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[zoom,setZoom]=useState<Row|null>(null);
 const appearanceOnly=reviewScope==='cap-on-appearance';
 const sheetElement=useRef<HTMLDivElement>(null);
 useEffect(()=>{
  const cached=[...(sheetElement.current?.querySelectorAll<HTMLImageElement>('img[data-review-key]')??[])].filter(img=>img.complete&&img.naturalWidth>0).map(img=>img.dataset.reviewKey!);
  setLoaded(old=>{const next=new Set([...old,...cached]);return next.size===old.size?old:next;});
 },[size,scope,sheet.token]);
 const sizes=[...new Set(sheet.rows.map(r=>r.capacityMl))].sort((a,b)=>(a??Infinity)-(b??Infinity));
 const rows=sheet.rows.filter(r=>(size==='all'||String(r.capacityMl)===size)&&(scope==='all'||(scope==='eligible'?r.eligible:!r.eligible)));
 const groupsAt=(n:number|null)=>[...new Map(rows.filter(r=>r.capacityMl===n).map(r=>[r.productGroupId||'unlinked:'+r.sku,{id:r.productGroupId||'unlinked:'+r.sku,color:r.color,slug:r.groupSlug}])).values()].sort((a,b)=>(a.slug||a.id).localeCompare(b.slug||b.id));
 const pending=rows.filter(r=>r.eligible&&(appearanceOnly?!r.appearanceApproved:r.status!=='approved')&&!(r.sku in flags)&&r.status!=='changes_requested');
 const key=(r:Row,v:View)=>r.sku+':'+v.sha256;
 const ready=pending.every(r=>r.views.length>0&&r.views.every(v=>loaded.has(key(r,v))&&!failed.has(key(r,v))));
 const flagRows=rows.filter(r=>r.sku in flags);
 const flagNotesValid=flagRows.every(r=>flags[r.sku].trim().length>0);
 const approved=sheet.rows.filter(r=>r.status==='approved'&&r.eligible).length;
 const appearanceApproved=sheet.rows.filter(r=>r.appearanceApproved||(r.status==='approved'&&r.eligible)).length;
 const toggle=(r:Row)=>{setAck(false);setFlags(old=>{const next={...old};if(r.sku in next)delete next[r.sku];else next[r.sku]=r.notes||'';return next;});};
 async function save(includeApprovals:boolean){
  setBusy(true);setError('');setMessage('');
  try{
   const decisions=[...(includeApprovals?pending.map(r=>({sku:r.sku,binding:appearanceOnly?(r.appearanceBinding??r.binding):r.binding,status:'approved',notes:''})):[]),...flagRows.map(r=>({sku:r.sku,binding:appearanceOnly?(r.appearanceBinding??r.binding):r.binding,status:'changes_requested',notes:flags[r.sku]}))];
   const response=await fetch('/api/asset-ledger/plate-contact-sheet',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({family:sheet.family,token:sheet.token,revision:sheet.revision,scope:appearanceOnly?'cap-on-appearance':undefined,decisions})});const result=await response.json();if(!response.ok)throw Error(result.error);
   setSheet(result.sheet);setFlags(old=>Object.fromEntries(Object.entries(old).filter(([sku])=>!decisions.some(d=>d.sku===sku))));setAck(false);
   setMessage(`${includeApprovals?pending.length:0} ${appearanceOnly?'cap-on appearances':'plates'} approved; ${flagRows.length} exceptions saved. Exact image files are registered. This sheet reflects the saved decisions now; the next full ledger refresh checks served bytes again. Nothing published.`);
  }catch(e){setError(e instanceof Error?e.message:'Unable to save the batch.');}finally{setBusy(false);}
 }
 return <main className={styles.page}><div className={styles.shell} ref={sheetElement}>
  <a href={'/team/asset-ledger?preview=1&family='+encodeURIComponent(sheet.family)}>← Back to the asset workbench</a>
  <header className={styles.header}><div><p className={styles.eyebrow}>Family review · bottle plates</p><h1>{sheet.family} contact sheet</h1><p>{appearanceOnly?'Scan the family. Flag exceptions. Approve the cap-on appearance together.':'Scan the family. Flag exceptions. Approve the eligible plates together.'}</p></div><span className={styles.local}>Local review · not a release</span></header>
  {appearanceOnly&&<p className={styles.notice}><strong>Cap-on appearance lane.</strong> This batch records visual acceptance of the exact current cap-on bytes. It does not clear source, glass sizing, cap-off pairing, or publication holds; those remain in the technical queue.</p>}
  {finalPreparation&&finalPreparation.publicationState!=='released'&&<div className={styles.notice}><strong>{finalPreparation.preparedPairs} final pairs are {finalPreparation.status==='approved'?'approved · awaiting release':'prepared'}.</strong><p>{finalPreparation.status==='approved'?'Image review and source acceptance are complete. The indexed images below still await the approved replacements; these exact final files do not need another review.':'All paired alignment checks pass. Review the final files and their documented source basis.'}</p><a href={finalPreparation.reviewUrl}>{finalPreparation.status==='approved'?'View the approved final Cylinder batch':'Open the final Cylinder batch and register approval'} →</a></div>}
  <div className={styles.totals}><div><strong>{sheet.rows.length}</strong><span>configurations</span></div><div><strong>{sheet.rows.filter(r=>r.views.length).length}</strong><span>existing plates</span></div><div><strong>{approved}</strong><span>approved with plate checks passed</span></div><div><strong>{appearanceApproved}</strong><span>cap-on images visually approved</span></div></div>
  {!!sheet.excludedDuplicates?.length&&<p className={styles.success}>{sheet.excludedDuplicates.length} retired duplicates are recorded separately in the workbench. Their canonical products are included here; no new plates or approvals are needed for the duplicate records.</p>}
  {appearanceApproved===sheet.rows.filter(r=>r.views.length).length&&appearanceApproved>0&&<p className={styles.success}>All {appearanceApproved} existing cap-on images are visually approved. Their appearance review is complete. Source records and required cap-off pairs remain separate checks.</p>}
  <p className={styles.notice}><strong>Existing images, unchanged.</strong> Bulbs, tassels, droppers, reducers and atomizers are complete top swaps. Their assembled plate is the required view.  All tiles use the same zoom on the original 1000 × 1100 plate canvas. This review does not change your shared glass standards. Hero framing has not automatically resized these plates; this review records visual acceptance of the files shown, not a new sizing lock.</p>
  {sheet.family==='Boston Round'&&<><p><a href="/team/asset-ledger?preview=1&view=sources">View recovered master artwork for missing Boston plates →</a></p>
  <p><a href="/team/asset-ledger?preview=1&view=completion">Review newly prepared plates and corrections →</a></p></>}
  <p><a href="#register-review">Jump to batch approval ↓</a></p>
  <div className={styles.instructions}><strong>Look for:</strong> consistent glass within each physical profile and size, correct color and component, clean edges and a correct cap-off view where required. Your appearance sign-off stays recorded while source or pairing work is finished. Click an image for a closer look.</div>
  <nav className={styles.nav} aria-label="Plate contact sheet sizes">{['all',...sizes.map(String)].map(s=><button key={s} aria-pressed={size===s} disabled={busy} onClick={()=>{setSize(s);setAck(false);setMessage('');}}>{s==='all'?'Whole '+sheet.family+' family':s==='null'?'Size unresolved':s+' mL'} · {sheet.rows.filter(r=>s==='all'||String(r.capacityMl)===s).length}</button>)}</nav>
  <nav className={styles.nav} aria-label="Review scope">{[['eligible','Eligible plates'],['held','Reconciliation & missing'],['all','Whole family']].map(([value,label])=><button key={value} disabled={busy} aria-pressed={scope===value} onClick={()=>{setScope(value);setAck(false);}}>{label} · {sheet.rows.filter(r=>value==='all'||(value==='eligible'?r.eligible:!r.eligible)).length}</button>)}</nav>
  <div className={styles.legend}><span className={styles.approved}>Approved</span><span className={styles.eligible}>Eligible for review</span><span className={styles.hold}>Hold / missing</span><span className={styles.exception}>Flagged exception</span></div>
  <p className={styles.scope} role="status">Showing {rows.length} configurations · {pending.length} eligible plates awaiting approval · {rows.filter(r=>!r.eligible).length} held or missing. Scope: current development catalog; legacy reconciliation remains open.</p>
  {sizes.filter(n=>(size==='all'||String(n)===size)&&groupsAt(n).length>0).map(n=><section key={String(n)} className={styles.size} aria-label={`${n} mL plates`}><h2>{n!=null?n+' mL':'Size unresolved'} {sheet.family} <small>Physical profiles stay separate; this is an image review</small></h2>{groupsAt(n).map(group=><section className={styles.color} key={group.id}><h3>{group.color} glass · {group.slug||'Catalog group unresolved'}</h3><div className={styles.grid}>{rows.filter(r=>r.capacityMl===n&&(r.productGroupId||'unlinked:'+r.sku)===group.id).sort((a,b)=>(a.itemName??'').localeCompare(b.itemName??'')||a.sku.localeCompare(b.sku)).map(r=>{
   const flagged=r.sku in flags||r.status==='changes_requested';const tone=flagged?'exception':!r.eligible?'hold':r.status==='approved'?'approved':'eligible';
   return <article key={r.sku} className={`${styles.card} ${styles[tone+'Card']}`} data-sku={r.sku}>
    <div className={styles.cardTop}><span className={styles[tone]}>{flagged?'Needs attention':!r.eligible?(r.appearanceApproved?'Cap-on approved · checks remain':r.views.length?'On hold':'Plate missing'):appearanceOnly&&r.appearanceApproved?'Cap-on appearance approved':r.status==='approved'?'Approved':'Ready to review'}</span><span>{r.capColor??'Cap color unrecorded'}</span></div>
    <div className={styles.images}>{r.views.length?r.views.map(v=><figure key={v.sha256}><figcaption>{requiresAssembledClosure(r.applicator,r.sku)?'Assembled top':v.label}</figcaption><button className={styles.imageButton} onClick={()=>setZoom(r)} aria-label={`Enlarge ${r.sku} ${v.label}`}><img data-review-key={key(r,v)} src={v.url} alt={`${r.itemName||r.sku} — ${v.label}`} width={1000} height={1100} onLoad={()=>setLoaded(old=>new Set(old).add(key(r,v)))} onError={()=>setFailed(old=>new Set(old).add(key(r,v)))}/></button>{failed.has(key(r,v))&&<p className={styles.failure}>Image failed to load · excluded until refreshed</p>}</figure>):<div className={styles.placeholder}>No plate yet<br/><small>Preserved in the family scope</small></div>}{r.views.length===1&&<div className={styles.placeholder}>{requiresAssembledClosure(r.applicator,r.sku)?'Complete top swap':r.reason.includes('cap-off')?'Cap-off view missing':'No cap-off view on this sheet'}<small>{requiresAssembledClosure(r.applicator,r.sku)?'Bulb, tassel, dropper, reducer or atomizer stays assembled. No cap-off view needed.':r.eligible?'Not required for this recorded product type':'Resolve the recorded hold'}</small></div>}</div>
    <h4>{(r.itemName||[r.capacityMl+' mL',r.color,r.applicator].filter(Boolean).join(' · ')).split(/\s+For use with|\s+Price each/i)[0]}</h4><p className={styles.sku}>{r.sku}</p><p className={styles.sku}>Catalog profile: {r.groupSlug||'Unresolved group'}</p>
    {r.reason&&<p className={styles.reason}>{r.reason}</p>}{r.status==='changes_requested'&&<p className={styles.reason}>Saved feedback: {r.notes}</p>}
    <button className={styles.flag} disabled={busy||!localReview} aria-pressed={r.sku in flags} onClick={()=>toggle(r)}>{r.sku in flags?'Remove this exception':r.status==='changes_requested'?'Update exception note':'Flag an exception'}</button>
    {r.sku in flags&&<label className={styles.note}>What needs correction?<textarea maxLength={2000} rows={2} value={flags[r.sku]} onChange={e=>setFlags(old=>({...old,[r.sku]:e.target.value}))} placeholder="For example: glass looks too wide, wrong cap, rough edge"/></label>}
   </article>;
  })}</div></section>)}</section>)}
  <section id="register-review" className={styles.approval} aria-label={appearanceOnly?'Approve cap-on appearance':'Approve this contact sheet'}><h2>{appearanceOnly?'Register cap-on appearance review':'Register this review'}</h2><p><strong>{pending.length} eligible {appearanceOnly?'cap-on images':'plates'}</strong> in {size==='all'?'the '+sheet.family+' family':size+' mL'} will be approved. {flagRows.length} flagged exceptions will be saved separately. Held, missing, previously approved and previously flagged images are excluded.</p>
   <label className={styles.ack}><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/>{appearanceOnly?'I have reviewed the exact current cap-on images and flagged any exceptions.':'I have reviewed the eligible plates and their shown cap-off views, and flagged any exceptions.'}</label>
   {!ready&&<p className={styles.reason}>Wait for all eligible image previews to load. Failed images must be refreshed before this batch can be approved.</p>}
   <div className={styles.actions}><button className={styles.primary} disabled={!localReview||busy||!ack||!ready||!flagNotesValid||!pending.length} onClick={()=>save(true)}>{busy?'Verifying files and saving…':`Approve ${pending.length} ${appearanceOnly?'cap-on appearances':'eligible plates'}${flagRows.length?' & save exceptions':''}`}</button><button disabled={!localReview||busy||!flagRows.length||!flagNotesValid} onClick={()=>save(false)}>Save {flagRows.length} exceptions only</button></div>
   <p>{appearanceOnly?'Each appearance approval binds to the exact current cap-on file. Changed files return to review. Source, sizing, pairing, kits, heroes, and release approval stay separate.':'Each approval binds to the exact cap-on and cap-off files. Changed files return to review. Kits, heroes, shared sizing and release approval stay separate.'}</p>{!localReview&&<p>Approval controls are available only in the local workbench.</p>}{message&&<p role="status" className={styles.success}>{message}</p>}{error&&<p role="alert" className={styles.failure}>{error}</p>}
  </section>
  {zoom&&<div className={styles.overlay} role="dialog" aria-modal="true" aria-label={`Enlarged plate ${zoom.sku}`} onKeyDown={e=>{if(e.key==='Escape')setZoom(null);}}><div className={styles.dialog}><button autoFocus onClick={()=>setZoom(null)}>Close enlarged view</button><h2>{zoom.itemName||zoom.sku}</h2><p>{zoom.sku} · unchanged files, equal zoom</p><div className={styles.zoomImages}>{zoom.views.map(v=><figure key={v.sha256}><figcaption>{v.label}</figcaption><img src={v.url} alt={`${zoom.sku} ${v.label}`} width={1000} height={1100}/></figure>)}</div></div></div>}
 </div></main>;
}
