"use client";
import {useState,useEffect,useRef} from 'react';
import styles from './completion.module.css';
type View={label:string;url:string;sha256:string};
type Row={sku:string;groupSlug:string;capacityMl:number;color:string;itemName:string;origin:string;views:View[];before:View[];holds:string[];eligible:boolean;status:string;notes:string;binding:string};
type Sheet={token:string;revision:number;rows:Row[];preserved:Array<{sku:string;capacityMl:number;color:string;views:View[]}>;platePresentations:Record<string,{glassHeight:number;baseY:number}>;summary:{prepared:number;reviewable:number;approved:number;held:number;newPlates:number;corrections:number;preserved:number}};
export default function PlateCompletion({initial,localReview}:{initial:Sheet;localReview:boolean}){
 const [sheet,setSheet]=useState(initial),[size,setSize]=useState('all'),[kind,setKind]=useState('all'),[mode,setMode]=useState('after'),[flags,setFlags]=useState<Record<string,string>>({}),[ack,setAck]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loaded,setLoaded]=useState(new Set<string>());
 const element=useRef<HTMLDivElement>(null);
 const rows=sheet.rows.filter(r=>(size==='all'||r.capacityMl===Number(size))&&(kind==='all'||r.origin===kind));
 const candidates=rows.filter(r=>r.eligible&&r.status==='pending'&&!(r.sku in flags));
 const exceptions=rows.filter(r=>r.sku in flags);
 const key=(r:Row,v:View)=>r.sku+':'+v.sha256;
 useEffect(()=>{const keys=[...(element.current?.querySelectorAll<HTMLImageElement>('img[data-key]')??[])].filter(i=>i.complete&&i.naturalWidth>0).map(i=>i.dataset.key!);setLoaded(old=>new Set([...old,...keys]));},[size,kind,mode,sheet.token]);
 const ready=candidates.every(r=>[...r.views,...(mode==='compare'?r.before:[])].every(v=>loaded.has(key(r,v))));
 async function save(approve:boolean){setBusy(true);setError('');setMessage('');try{
  const decisions=[...(approve?candidates.map(r=>({sku:r.sku,binding:r.binding,status:'approved',notes:''})):[]),...exceptions.map(r=>({sku:r.sku,binding:r.binding,status:'changes_requested',notes:flags[r.sku]}))];
  const response=await fetch('/api/asset-ledger/plate-completion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:sheet.token,revision:sheet.revision,presentationAcknowledged:ack,decisions})});const result=await response.json();if(!response.ok)throw Error(result.error);setSheet(result.sheet);setFlags({});setAck(false);setMessage(`${approve?candidates.length:0} candidate plates approved; ${exceptions.length} exceptions saved. Existing approvals are preserved. Release remains separate.`);
 }catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 function views(r:Row,items:View[],label:string){return <div><h4>{label}</h4><div className={styles.views}>{items.map(v=><figure key={v.sha256+v.label}><a href={v.url} target="_blank" rel="noreferrer"><img data-key={key(r,v)} src={v.url} alt={`${r.sku} ${label} ${v.label}`} onLoad={()=>setLoaded(old=>new Set([...old,key(r,v)]))} onError={()=>{setLoaded(old=>{const n=new Set(old);n.delete(key(r,v));return n;});setError('An image failed to load. Reload before approving.');}}/></a><figcaption>{v.label}</figcaption></figure>)}</div></div>;}
 return <main className={styles.page}><div className={styles.shell} ref={element}>
  <a href="/team/asset-ledger?preview=1">← Asset workbench</a><p className={styles.eyebrow}>Boston Round · finished-plate review</p><h1>One family. One contact sheet.</h1><p className={styles.lead}>Your {sheet.summary.preserved} approved plates are preserved. Review the new plates and corrections below.</p>
  <div className={styles.totals}><div><b>{sheet.summary.preserved}</b>Approved · preserved</div><div><b>{sheet.summary.newPlates}</b>New plate candidates</div><div><b>{sheet.summary.corrections}</b>Existing plates corrected</div><div><b>{sheet.summary.approved} / {sheet.summary.reviewable}</b>Candidate approvals</div></div>
  <section className={styles.notice}><b>Check the glass first, then the components.</b><p>These plates use the 1000 × 1100 plate canvas. The proposed plate framing is based on your approved plates and is recorded separately from hero framing. Each size shares one glass height across colors and closures. Approving these images also approves their displayed plate framing; your hero locks stay intact.</p><div className={styles.targets}>{Object.entries(sheet.platePresentations).map(([n,t])=><span key={n}>{n} mL · glass {Math.round(t.glassHeight)} px · baseline {Math.round(t.baseY)} px</span>)}</div></section>
  <nav aria-label="Bottle size">{['all','15','30','60'].map(n=><button key={n} aria-pressed={size===n} disabled={busy} onClick={()=>{setSize(n);setAck(false);}}>{n==='all'?'Whole Boston family':n+' mL'}</button>)}</nav>
  <nav aria-label="Review scope">{[['all','New + corrections'],['new-plate','New plates'],['existing-correction','Corrections']].map(([v,label])=><button key={v} aria-pressed={kind===v} disabled={busy} onClick={()=>{setKind(v);setAck(false);}}>{label}</button>)}</nav>
  <nav aria-label="Comparison view">{[['compare','Before / After'],['after','Proposed contact sheet']].map(([v,label])=><button key={v} aria-pressed={mode===v} onClick={()=>{setMode(v);setAck(false);}}>{label}</button>)}</nav>
  <p role="status">Showing {rows.length} configurations · {candidates.length} ready to approve · {rows.filter(r=>!r.eligible).length} held. All image tiles use the same zoom. Click an image to inspect it at full size.</p>
  {[15,30,60].filter(n=>size==='all'||n===Number(size)).map(n=><section key={n}><h2>{n} mL Boston Round</h2><div className={styles.grid}>{rows.filter(r=>r.capacityMl===n).sort((a,b)=>a.color.localeCompare(b.color)||a.itemName.localeCompare(b.itemName)).map(r=><article key={r.sku} className={`${styles.card} ${!r.eligible?styles.held:r.status==='approved'?styles.approved:''}`}><div className={styles.cardHead}><b>{r.color}</b><span>{!r.eligible?'Hold':r.status==='approved'?'Approved':r.origin==='new-plate'?'New plate':'Correction'}</span></div><h3>{r.itemName.split(/\s+For use with|\s+Price each/i)[0]}</h3><p className={styles.sku}>{r.sku}</p>{r.eligible&&<p><a href={`/products/${r.groupSlug}?assetPreview=boston&sku=${encodeURIComponent(r.sku)}`} target="_blank" rel="noreferrer">Open product preview ↗</a></p>}<div className={mode==='compare'?styles.compare:styles.single}>{mode==='compare'&&views(r,r.before,r.origin==='new-plate'?'Original source':'Before · current plate')}{views(r,r.views,'After · proposed plate')}</div>{r.holds.map(h=><p className={styles.holdText} key={h}>{h}</p>)}{r.status!=='approved'&&<><button disabled={busy} onClick={()=>{setAck(false);setFlags(old=>{const next={...old};if(r.sku in next)delete next[r.sku];else next[r.sku]=r.notes||'';return next;});}}>{r.sku in flags?'Remove exception':'Flag an exception'}</button>{r.sku in flags&&<textarea aria-label={`Exception for ${r.sku}`} placeholder="What needs to change?" value={flags[r.sku]} onChange={e=>setFlags(old=>({...old,[r.sku]:e.target.value}))}/>}</>}</article>)}</div></section>)}
  <section className={styles.actions}><h2>Approve the batch you reviewed</h2><label><input type="checkbox" checked={ack} disabled={busy} onChange={e=>setAck(e.target.checked)}/> I reviewed the glass sizes, cap-on / cap-off views, and unflagged images shown above.</label><p>{candidates.length} eligible images will be approved. {exceptions.length} exceptions will be saved separately. Held plates stay on hold.</p><button disabled={!localReview||busy||!ack||!ready||!candidates.length||exceptions.some(r=>!flags[r.sku].trim())} onClick={()=>save(true)}>{busy?'Saving…':`Approve ${candidates.length} eligible plates`}</button>{exceptions.length>0&&<button disabled={busy||!localReview||exceptions.some(r=>!flags[r.sku].trim())} onClick={()=>save(false)}>Save exceptions only</button>}{!ready&&<p>Waiting for review images to load.</p>}{message&&<p role="status">{message}</p>}{error&&<p role="alert">{error}</p>}</section>
  <details className={styles.preserved}><summary>{sheet.summary.preserved} previously approved plates · unchanged</summary><p>These exact files and their approvals remain preserved. <a href="/team/asset-ledger?preview=1&view=plates">Open the original approved sheet</a>.</p></details>
 </div></main>;
}
