// Portrait editorial scenes under the locked material-board recipe (bone #F5F3EF, one daylight, one baseline,
// family material base in the lower quarter). Regenerate with scripts/family-cards. Not SKU plates.
//
// FAMILY_ART is the mobile / default plate. Cylinder, Boston Round, Round and Circle use
// nearly-square v4 mobile crops; desktop cards use the separate 3:4 lineups below.
export const FAMILY_ART: Record<string, string> = {
    "Cylinder": "family-cylinder-mobile-v4",
    "Boston Round": "family-boston-round-mobile-v4",
    "Round": "family-round-mobile-v4",
    "Circle": "family-circle-mobile-v4",
    "Elegant": "family-elegant-bone-v3",
    "Diva": "family-diva-bone-v3",
    "Grace": "family-grace-bone-v3",
    "Empire": "family-empire-bone-v3"
};

export const FAMILY_ART_DESKTOP: Record<string, string> = {
    "Cylinder": "family-cylinder-desktop-v4",
    "Boston Round": "family-boston-round-desktop-v4",
    "Round": "family-round-desktop-v4",
    "Circle": "family-circle-desktop-v4"
};

export type FamilyCardSources = { desktop: string; mobile: string };

export function familyCardSources(family: string, cmsSrc?: string | null): FamilyCardSources | null {
    if (cmsSrc) return { desktop: cmsSrc, mobile: cmsSrc };
    const mobile = FAMILY_ART[family];
    if (!mobile) return null;
    const desktop = FAMILY_ART_DESKTOP[family] ?? mobile;
    return {
        desktop: `/assets/homepage/${desktop}.webp`,
        mobile: `/assets/homepage/${mobile}.webp`,
    };
}

// Pencil silhouette tiles (4:3, 1200×900) for accent slots: mega-menu + search-panel tiles.
// Generated by scripts/family-silhouettes; never used in place of product photography.
export const FAMILY_SKETCH: Record<string, string> = {
    "Cylinder": "family-cylinder-4x3",
    "Elegant": "family-elegant-4x3",
    "Circle": "family-circle-4x3",
    "Boston Round": "family-boston-round-4x3",
    "Diva": "family-diva-4x3",
    "Grace": "family-grace-4x3",
    "Empire": "family-empire-4x3",
    "Round": "family-round-4x3"
};
export const familySketchSrc = (family: string): string | null => FAMILY_SKETCH[family] ? `/assets/sketches/${FAMILY_SKETCH[family]}.webp` : null;
