// Portrait editorial scenes follow the Figma material system; these are not SKU plates.
export const FAMILY_ART: Record<string, string> = {
    "Cylinder": "family-cylinder-portrait",
    "Elegant": "family-elegant-portrait-open-mouth",
    "Circle": "family-circle-portrait",
    "Boston Round": "family-boston-round-colors-portrait",
    "Diva": "family-diva-portrait-open-mouth",
    "Grace": "family-grace-portrait-open-mouth",
    "Empire": "family-empire-portrait-open-mouth",
    "Round": "family-round-portrait-open-mouth"
};

// Pencil silhouette tiles (4:3, 1200×900) for accent slots: mega-menu + search-panel tiles.
// Generated by scripts/family-silhouettes; never used in place of product photography.
export const FAMILY_SKETCH: Record<string, string> = {
    "Cylinder": "family-cylinder-4x3",
    "Elegant": "family-elegant-4x3",
    "Circle": "family-circle-4x3",
    "Boston Round": "family-boston-round-4x3",
    "Diva": "family-diva-4x3",
    "Grace": "family-grace-4x3",
    "Empire": "family-empire-4x3",
    "Round": "family-round-4x3"
};
export const familySketchSrc = (family: string): string | null => FAMILY_SKETCH[family] ? `/assets/sketches/${FAMILY_SKETCH[family]}.webp` : null;
