#!/usr/bin/env python3
"""
Canonical data-integrity audit. Reads the snapshots the pipeline already
produces and reports what is deterministic, what is ambiguous and what needs
a human decision. It changes nothing and relaxes nothing: every gate the
publisher enforces is re-checked here, never weakened.

    python3 scripts/paperdoll/audit.py
        -> docs/data-audit/best-bottles-canonical-data-audit.md
        -> data/paper-doll/audit-matrix.json

Inputs (all generated by the pipeline, all committed):
    convex-snapshot.json      products + groups + duplicate list
    component-snapshot.json   component edges + fitment rules
    plates-snapshot.json      the live index + its integrity sweeps
    xref.json                 the SKU <-> PSD join with its match kinds
    selection.json            one chosen source per (stem, cap state)
    inventory.json            every source file with a reason code
    tokens.json               the SKU vocabulary
    kit-audit.json            per-SKU layer facts
    alias-map.json            approved aliases (the ONLY match-time rewrite)
    alias-candidates.json     near-misses awaiting review
"""
from __future__ import annotations

import json
import re
import time
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
DATA = REPO / "data" / "paper-doll"
DOCS = REPO / "docs" / "data-audit"

COMPONENT_FAMILIES = {"Cap/Closure", "Sprayer", "Lotion Pump", "Dropper", "Roll-On Cap", "Reducer", "Overcap", "Roller Ball"}
# the four family ids that shipped before the grammar existed
LEGACY_ALIASES = {
    "diva-46-clear": "diva-46ml-clear-18-415",
    "diva-46-frosted": "diva-46ml-frosted-18-415",
    "cylinder-50ml-clear": "cylinder-50ml-clear-18-415",
    "cylinder-9ml-17-415": "cylinder-9ml-<glass>-17-415",
}
# 8-425 is a real neck standard, so the prefix is 1-2 digits; "18415" and "18-415"
# are the same thread spelled two ways, and both appear in component SKUs
THREAD_RE = re.compile(r"(?<!\d)(\d{1,2})-?(\d{3})(?!\d)")


def load(name):
    return json.loads((DATA / name).read_text())


def slug(value) -> str:
    return re.sub(r"-+", "-", re.sub(r"[^a-z0-9]+", "-", str(value).lower())).strip("-")


def family_id(product: dict, group: dict | None) -> tuple[str | None, str | None]:
    """The implemented grammar, recomputed here from product fields only."""
    g = group or {}
    family = g.get("family") or product.get("family")
    if product.get("category") == "Component" or family in COMPONENT_FAMILIES:
        neck = g.get("neckThreadSize") or product.get("neckThreadSize")
        if not family or not neck:
            return None, "missing:" + ",".join(n for n, v in (("family", family), ("neck", neck)) if not v)
        return f"{slug(family)}-{slug(neck)}", None
    capacity = g.get("capacityMl") if g.get("capacityMl") is not None else product.get("capacityMl")
    color = g.get("color") or product.get("color") or "mixed"
    neck = g.get("neckThreadSize") or product.get("neckThreadSize")
    missing = [n for n, v in (("family", family), ("capacityMl", capacity), ("neck", neck)) if v in (None, "")]
    if missing:
        return None, "missing:" + ",".join(missing)
    cap = f"{capacity:g}" if isinstance(capacity, (int, float)) else str(capacity)
    return f"{slug(family)}-{cap}ml-{slug(color)}-{slug(neck)}", None


def normalise_thread(value) -> str | None:
    m = THREAD_RE.search(str(value or ""))
    return f"{m.group(1)}-{m.group(2)}" if m else None


# ---------------------------------------------------------------- sections
def audit_identity(snap, xref):
    """§1 — one row per website SKU: is it unique, and what does it resolve to?"""
    groups = {g["_id"]: g for g in snap["groups"]}
    by_sku = defaultdict(list)
    for p in snap["products"]:
        by_sku[(p.get("websiteSku") or "").strip()].append(p)
    xref_by_sku = {r["websiteSku"]: r for r in xref["products"] if r["websiteSku"]}

    rows = []
    duplicates = []
    for sku, docs in sorted(by_sku.items()):
        if not sku:
            continue
        fids = []
        for d in docs:
            fid, reason = family_id(d, groups.get(d.get("productGroupId")))
            fids.append((fid, reason))
        state = "unique" if len(docs) == 1 else "duplicate"
        rows.append({
            "websiteSku": sku, "documents": len(docs), "uniquenessState": state,
            "graceSkus": sorted({d.get("graceSku") for d in docs if d.get("graceSku")}),
            "groupSlugs": sorted({(groups.get(d.get("productGroupId")) or {}).get("slug") for d in docs} - {None}),
            "familyIds": sorted({f for f, _ in fids if f}),
            "familyIdReasons": sorted({r for _, r in fids if r}),
            "matchKind": xref_by_sku.get(sku, {}).get("matchKind"),
            "publishable": xref_by_sku.get(sku, {}).get("publishable", False),
        })
        if len(docs) > 1:
            # classify WHY there is more than one document
            grace = {d.get("graceSku") for d in docs}
            group_ids = {d.get("productGroupId") for d in docs}
            fid_set = {f for f, _ in fids if f}
            names = {(d.get("itemName") or "")[:80] for d in docs}
            if len(grace) == 1 and len(group_ids) == 1:
                kind, action = "IDENTICAL_RECORD", "merge: same grace SKU, same group — one document should remain"
                confidence = "high"
            elif len(grace) > 1 and len(group_ids) == 1:
                kind, action = "DISTINCT_PRODUCTS_SHARING_A_WEBSITE_SKU", "assign a distinct website SKU to each product, or retire the surplus"
                confidence = "high"
            elif len(group_ids) > 1 and len(fid_set) > 1:
                kind, action = "SAME_SKU_IN_TWO_FAMILIES", "decide which family owns the SKU; the other document is misfiled or a different product"
                confidence = "high"
            else:
                kind, action = "SAME_SKU_DIFFERENT_GROUP", "confirm which product group is correct"
                confidence = "medium"
            duplicates.append({
                "websiteSku": sku, "kind": kind, "documents": len(docs),
                "documentIds": [d.get("_id") for d in docs],
                "graceSkus": sorted(g for g in grace if g),
                "groupSlugs": sorted({(groups.get(gid) or {}).get("slug") for gid in group_ids} - {None}),
                "familyIds": sorted(fid_set),
                "itemNames": sorted(n for n in names if n),
                "fields": {
                    "category": sorted({d.get("category") for d in docs if d.get("category")}),
                    "capacityMl": sorted({d.get("capacityMl") for d in docs if d.get("capacityMl") is not None}),
                    "color": sorted({d.get("color") for d in docs if d.get("color")}),
                    "neckThreadSize": sorted({d.get("neckThreadSize") for d in docs if d.get("neckThreadSize")}),
                    "applicator": sorted({d.get("applicator") for d in docs if d.get("applicator")}),
                },
                "recommendedResolution": action,
                "confidence": confidence,
                "evidence": "convex-snapshot.json — products sharing one websiteSku",
                "publishingBlocked": True,
            })
    return rows, duplicates


def audit_families(snap):
    """§2 — recompute familyId and look for collisions and lost necks."""
    groups = {g["_id"]: g for g in snap["groups"]}
    members = defaultdict(list)
    missing_neck = []
    for p in snap["products"]:
        g = groups.get(p.get("productGroupId"))
        fid, reason = family_id(p, g)
        if fid:
            members[fid].append((p, g))
        elif reason and "neck" in reason:
            missing_neck.append({"websiteSku": p.get("websiteSku"), "graceSku": p.get("graceSku"),
                                 "family": (g or {}).get("family") or p.get("family"),
                                 "groupSlug": (g or {}).get("slug"), "reason": reason})
    collisions = []
    for fid, entries in sorted(members.items()):
        necks = {(g or {}).get("neckThreadSize") or p.get("neckThreadSize") for p, g in entries}
        necks = {n for n in necks if n}
        if len(necks) > 1:
            collisions.append({"familyId": fid, "issue": "FAMILY_ID_COLLISION", "necks": sorted(necks),
                               "skus": sorted({p.get("websiteSku") for p, _ in entries})[:12],
                               "evidence": "two neck finishes recomputed to one familyId"})
    # family/capacity/colour combinations that legitimately span several necks:
    # these MUST stay separate, so they are the collision risk worth naming
    spans = defaultdict(set)
    for fid in members:
        parts = fid.rsplit("-", 2)
        if len(parts) == 3:
            spans[parts[0]].add(parts[1] + "-" + parts[2])
    multi_neck = {k: sorted(v) for k, v in spans.items() if len(v) > 1}
    return members, collisions, missing_neck, multi_neck


def audit_compatibility(comp, snap):
    """§6 — neck is first-order: a component whose thread differs from the bottle's is invalid."""
    invalid, unverified = [], []
    edges = 0
    by_thread_pairs = Counter()
    for p in comp["products"]:
        bottle_thread = normalise_thread(p.get("neckThreadSize"))
        for csku in p["componentSkus"]:
            edges += 1
            comp_thread = normalise_thread(csku)
            if comp_thread is None:
                unverified.append({"websiteSku": p["websiteSku"], "component": csku,
                                   "bottleNeck": p.get("neckThreadSize"),
                                   "issue": "COMPATIBILITY_UNVERIFIED",
                                   "reason": "component SKU carries no thread designation"})
            elif bottle_thread is None:
                unverified.append({"websiteSku": p["websiteSku"], "component": csku,
                                   "bottleNeck": p.get("neckThreadSize"),
                                   "issue": "COMPATIBILITY_UNVERIFIED",
                                   "reason": "product has no neck thread size"})
            elif comp_thread != bottle_thread:
                invalid.append({"websiteSku": p["websiteSku"], "component": csku,
                                "bottleNeck": bottle_thread, "componentNeck": comp_thread,
                                "issue": "COMPATIBILITY_INVALID",
                                "reason": f"{comp_thread} component declared on a {bottle_thread} bottle"})
                by_thread_pairs[(bottle_thread, comp_thread)] += 1
    return {"edges": edges, "invalid": invalid, "unverified": unverified, "invalidPairs": by_thread_pairs}


def audit_shared_descriptors(snap):
    """One physical part registered under several component ids? Group by descriptor stem
    (the id minus its trailing -NN) and show the item names, which is the evidence that
    decides it. Nothing is merged here: the suffix sometimes encodes a real physical
    difference (a dropper's glass stem length) and sometimes only a finish."""
    stem = lambda g: re.sub(r"-\d{2}$", "", g)
    groups = defaultdict(list)
    for p in snap["products"]:
        if p.get("category") == "Component" and p.get("graceSku"):
            groups[stem(p["graceSku"])].append(p)
    out = []
    for key, members in sorted(groups.items()):
        if len(members) < 2:
            continue
        names = {(m.get("itemName") or "").strip() for m in members}
        out.append({
            "descriptor": key,
            "componentIds": sorted(m["graceSku"] for m in members),
            "websiteSkus": sorted(m.get("websiteSku") or "?" for m in members),
            "itemNames": sorted(n for n in names if n),
            "identicalNames": len(names) == 1,
            "verdict": "SAME_DESCRIPTION_DIFFERENT_IDS" if len(names) == 1 else "DESCRIPTIONS_DIFFER",
        })
    return out


def audit_reuse(comp, snap, tokens):
    """§11 — one physical component, many SKUs. Count how far each is already shared."""
    groups = {g["_id"]: g for g in snap["groups"]}
    prod_by_sku = {(p.get("websiteSku") or "").strip(): p for p in snap["products"]}
    usage = defaultdict(lambda: {"skus": set(), "families": set(), "necks": set()})
    for p in comp["products"]:
        sku = p["websiteSku"]
        base = prod_by_sku.get(sku)
        fid = family_id(base, groups.get(base.get("productGroupId")))[0] if base else None
        for csku in p["componentSkus"]:
            u = usage[csku]
            u["skus"].add(sku)
            if fid:
                u["families"].add(fid)
            neck = normalise_thread(csku)
            if neck:
                u["necks"].add(neck)
    rows = [{"component": c, "skus": len(u["skus"]), "families": len(u["families"]),
             "necks": sorted(u["necks"]), "exampleSkus": sorted(u["skus"])[:4]}
            for c, u in usage.items()]
    rows.sort(key=lambda r: -r["skus"])
    return rows


def audit_plates(plates_snap, snap, xref):
    """§9 — one plate row per canonical SKU, and every field present."""
    rows = plates_snap["plates"]
    by_sku = Counter(r["sku"] for r in rows)
    conflicts = [{"sku": s, "rows": n, "issue": "PLATE_ROW_CONFLICT"} for s, n in by_sku.items() if n > 1]
    prod_grace = {}
    for p in snap["products"]:
        sku = (p.get("websiteSku") or "").strip()
        if sku:
            prod_grace.setdefault(sku, set()).add(p.get("graceSku"))
    field_issues = []
    for r in rows:
        if not r.get("image"):
            field_issues.append({"sku": r["sku"], "issue": "MISSING_FRONT"})
        if r.get("graceSku") and r["sku"] in prod_grace and r["graceSku"] not in prod_grace[r["sku"]]:
            field_issues.append({"sku": r["sku"], "issue": "GRACE_SKU_MISMATCH",
                                 "plate": r["graceSku"], "catalogue": sorted(x for x in prod_grace[r["sku"]] if x)})
        if not r.get("familyId"):
            field_issues.append({"sku": r["sku"], "issue": "MISSING_FAMILY_ID"})
    return {"rows": len(rows), "conflicts": conflicts, "fieldIssues": field_issues,
            "sweep": plates_snap["plateIntegrity"], "kitSweep": plates_snap["kitIntegrity"]}


def audit_tokens(tokens, members):
    """§7 — one token, one meaning; one meaning, one token."""
    ambiguous_bodies = {b: v for b, v in tokens["bodies"].items() if v.get("ambiguous")}
    # a canonical finish reached by several spellings is fine; two canonical finishes
    # sharing a spelling would not be
    spelling_owner = defaultdict(set)
    for label, f in tokens["finishes"].items():
        for spelling in f["spellings"]:
            spelling_owner[spelling].add(label)
    collisions = {s: sorted(v) for s, v in spelling_owner.items() if len(v) > 1}
    unknown_family = {b: v for b, v in tokens["bodies"].items()
                      if v.get("familyId") and v["familyId"] not in members}
    return {"ambiguousBodies": ambiguous_bodies, "spellingCollisions": collisions,
            "bodiesWithoutFamily": [b for b, v in tokens["bodies"].items() if not v.get("familyId")],
            "bodiesPointingAtUnknownFamily": unknown_family,
            "unparsed": tokens["unparsed"], "reviewedAt": tokens.get("reviewedAt")}


def audit_assets(inventory, selection):
    """§8 — every file classified, every exclusion reasoned, no photograph collapsed."""
    files = inventory["files"]
    unclassified = [f for f in files if not f.get("role") and not f.get("junkReason")]
    junk = Counter(f["junkReason"] for f in files if f.get("junkReason"))
    roles = Counter(f["role"] for f in files if f.get("role"))
    multi_location = 0
    for entry in selection["stems"].values():
        for state in entry["states"].values():
            if len(state.get("locations", [])) > 1:
                multi_location += 1
    thumbs_or_views_chosen = []
    for key, entry in selection["stems"].items():
        for state, rec in entry["states"].items():
            path = (rec.get("chosenPath") or "").lower()
            if "thumbnail" in path or "thumbail" in path:
                thumbs_or_views_chosen.append({"stem": key, "state": state, "path": rec.get("chosenPath")})
    return {"files": len(files), "unclassified": len(unclassified), "junk": dict(junk), "roles": dict(roles),
            "conflicts": selection.get("conflicts", []), "multiLocationAssets": multi_location,
            "thumbnailsChosenAsFront": thumbs_or_views_chosen,
            "hiresSetAside": len(selection.get("hiresSetAside", []))}


def main():
    started = time.time()
    snap = load("convex-snapshot.json")
    comp = load("component-snapshot.json")
    plates_snap = load("plates-snapshot.json")
    xref = load("xref.json")
    selection = load("selection.json")
    inventory = load("inventory.json")
    tokens = load("tokens.json")
    kit_audit = load("kit-audit.json")
    aliases = load("alias-map.json")
    candidates = load("alias-candidates.json")["candidates"]
    # are the approved aliases doing any work? an alias is needed only when its SKU does
    # not already match a PSD stem exactly
    catalogue_skus = {(p.get("websiteSku") or "").strip() for p in snap["products"]} - {""}
    all_stems = set()
    for entry in selection["stems"].values():
        all_stems.update(entry["stems"])
    alias_health = {
        "entries": len(aliases),
        "valueIsCatalogueSku": sum(1 for v in aliases.values() if v in catalogue_skus),
        "needed": sum(1 for v in aliases.values() if v in catalogue_skus and v not in all_stems),
        "redundant": sum(1 for v in aliases.values() if v in catalogue_skus and v in all_stems),
        "stale": sum(1 for k, v in aliases.items() if k not in all_stems and v not in catalogue_skus),
    }

    identity_rows, duplicates = audit_identity(snap, xref)
    members, collisions, missing_neck, multi_neck = audit_families(snap)
    compat = audit_compatibility(comp, snap)
    reuse = audit_reuse(comp, snap, tokens)
    plate_audit = audit_plates(plates_snap, snap, xref)
    token_audit = audit_tokens(tokens, members)
    asset_audit = audit_assets(inventory, selection)
    shared_descriptors = audit_shared_descriptors(snap)

    kinds = Counter(r["matchKind"] for r in xref["products"])
    publishable = [r for r in xref["products"] if r["publishable"]]
    # the gate, re-derived here rather than trusted
    gate_violations = [r["websiteSku"] for r in publishable
                       if r["matchKind"] not in ("exact", "alias") or r["convexDuplicate"] or r["blockReasons"]]

    no_psd = [r for r in xref["products"] if r["matchKind"] == "no-psd"]
    no_psd_class = Counter()
    for r in no_psd:
        if r["category"] in ("Packaging", "Accessory", "Tool"):
            no_psd_class["non-bottle product"] += 1
        elif r["convexDuplicate"]:
            no_psd_class["duplicate SKU"] += 1
        elif r["familyIdReason"]:
            no_psd_class["unsupported family (no neck)"] += 1
        else:
            no_psd_class["photography genuinely missing"] += 1

    matrix = {
        "generatedAt": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "note": "audit view over existing ids; not a production schema",
        "sources": {"convexSnapshot": snap["generatedAt"], "plates": plates_snap["generatedAt"], "xref": xref["generatedAt"]},
        "bySku": {},
        "byComponent": {},
    }
    # the closure assembly a SKU spells, and the kit slots it opens, straight from the
    # reviewed vocabulary — a label, never a source of identity
    import sys as _sys
    _sys.path.insert(0, str(HERE))
    from build_tokens import parse_sku as _parse_sku
    closure_meta = tokens["closures"]

    plate_by_sku = {r["sku"]: r for r in plates_snap["plates"]}
    comp_by_sku = {p["websiteSku"]: p for p in comp["products"]}
    kit_by_sku = {r["websiteSku"]: r for r in kit_audit["results"]}
    for r in xref["products"]:
        sku = r["websiteSku"]
        if not sku:
            continue
        plate = plate_by_sku.get(sku)
        matrix["bySku"][sku] = {
            "graceSku": r["graceSku"], "familyId": r["familyId"], "body": None, "neck": None,
            "matchKind": r["matchKind"], "publishable": r["publishable"], "blockReasons": r["blockReasons"],
            "closureAssembly": (lambda parsed: {
                "token": parsed["closure"],
                "label": closure_meta.get(parsed["closure"], {}).get("label"),
                "slots": closure_meta.get(parsed["closure"], {}).get("slots", []),
                "applicator": closure_meta.get(parsed["closure"], {}).get("applicator"),
            } if parsed["closure"] else None)(_parse_sku(sku)),
            "physicalComponents": comp_by_sku.get(sku, {}).get("componentSkus", []),
            "plate": {"image": plate["image"], "capOff": plate.get("imageCapOff"), "revision": plate["revision"]} if plate else None,
            "kit": {"completeness": kit_by_sku[sku]["completeness"]} if sku in kit_by_sku else None,
        }
    body_of = {}
    for body, meta in tokens["bodies"].items():
        if meta.get("familyId"):
            body_of[meta["familyId"]] = body
    for sku, row in matrix["bySku"].items():
        if row["familyId"]:
            row["body"] = body_of.get(row["familyId"])
            row["neck"] = "-".join(row["familyId"].rsplit("-", 2)[-2:])
    for r in reuse:
        matrix["byComponent"][r["component"]] = {"skuCount": r["skus"], "familyCount": r["families"],
                                                 "necks": r["necks"], "exampleSkus": r["exampleSkus"]}
    (DATA / "audit-matrix.json").write_text(json.dumps(matrix, indent=1))

    human_review = []
    for d in duplicates:
        human_review.append({"item": f"duplicate SKU {d['websiteSku']}", "decision": d["recommendedResolution"], "kind": d["kind"], "confidence": d["confidence"]})
    if candidates:
        human_review.append({"item": f"{len(candidates)} alias candidates", "decision": "promote into alias-map.json or reject; they cannot publish as near-misses", "kind": "ALIAS_REVIEW", "confidence": "high"})
    if not token_audit["reviewedAt"]:
        human_review.append({"item": "tokens.json reviewedAt is unset", "decision": "review the vocabulary and set reviewedAt; --dist publishing is blocked until then", "kind": "TOKEN_REVIEW", "confidence": "high"})
    for c in asset_audit["conflicts"]:
        human_review.append({"item": f"SAME_STEM_DIFFERENT_PHOTOGRAPH {c['stem']} [{c['state']}]", "decision": "choose which photograph is canonical, or rename one stem", "kind": "SELECTION_CONFLICT", "confidence": "high"})
    for c in collisions:
        human_review.append({"item": f"FAMILY_ID_COLLISION {c['familyId']}", "decision": "separate the necks; never drop the neck to resolve", "kind": "FAMILY_COLLISION", "confidence": "high"})
    for d in shared_descriptors:
        if d["identicalNames"]:
            human_review.append({"item": f"component descriptor {d['descriptor']} has {len(d['componentIds'])} ids with one description",
                                 "decision": "confirm whether these are one physical part (share geometry) or genuinely different (give them distinguishing descriptions)",
                                 "kind": "COMPONENT_DESCRIPTOR_AMBIGUOUS", "confidence": "medium"})

    out = {"duplicates": duplicates, "collisions": collisions, "missingNeck": missing_neck, "multiNeck": multi_neck,
           "compat": {k: (v if k != "invalidPairs" else {f"{a}->{b}": n for (a, b), n in v.items()}) for k, v in compat.items()},
           "tokens": token_audit, "assets": asset_audit, "plates": plate_audit,
           "sharedComponentDescriptors": shared_descriptors, "humanReview": human_review}
    (DATA / "audit-findings.json").write_text(json.dumps(out, indent=1, default=str))

    render_report(snap, xref, kinds, publishable, gate_violations, identity_rows, duplicates, members,
                  collisions, missing_neck, multi_neck, compat, reuse, plate_audit, token_audit,
                  asset_audit, kit_audit, aliases, candidates, no_psd_class, human_review, started, alias_health,
                  shared_descriptors)


def render_report(snap, xref, kinds, publishable, gate_violations, identity_rows, duplicates, members,
                  collisions, missing_neck, multi_neck, compat, reuse, plate_audit, token_audit,
                  asset_audit, kit_audit, aliases, candidates, no_psd_class, human_review, started, alias_health,
                  shared_descriptors):
    DOCS.mkdir(parents=True, exist_ok=True)
    L = []
    a = L.append
    a("# Best Bottles — canonical data integrity audit")
    a("")
    a(f"Generated {time.strftime('%Y-%m-%d %H:%M')} by `scripts/paperdoll/audit.py` from the committed pipeline snapshots.")
    a("This audit reads; it changes nothing and relaxes no gate. Every number below is recomputed from")
    a("`data/paper-doll/*.json` and the live Convex index, not copied from an earlier report.")
    a("")
    a("## Executive summary")
    a("")
    a("| measure | count |")
    a("|---|---:|")
    a(f"| Convex products | {len(snap['products'])} |")
    a(f"| unique website SKUs | {snap['counts']['withWebsiteSku']} |")
    a(f"| duplicate website SKUs | {len(duplicates)} |")
    a(f"| products affected by a duplicate | {sum(d['documents'] for d in duplicates)} |")
    a(f"| exact matches | {kinds.get('exact', 0)} |")
    a(f"| approved aliases in use | {kinds.get('alias', 0)} of {len(aliases)} (all redundant — see §3) |")
    a(f"| near-misses (never publishable) | {kinds.get('near-miss:case', 0) + kinds.get('near-miss:punct', 0)} |")
    a(f"| products with no PSD | {kinds.get('no-psd', 0)} |")
    a(f"| products with no website SKU | {kinds.get('no-website-sku', 0)} |")
    a(f"| publishable SKUs | {len(publishable)} |")
    a(f"| gate violations among publishable | {len(gate_violations)} |")
    a(f"| distinct familyIds (publishable) | {len({r['familyId'] for r in publishable if r['familyId']})} |")
    a(f"| familyId collisions | {len(collisions)} |")
    a(f"| products missing a neck finish | {len(missing_neck)} |")
    a(f"| component compatibility edges | {compat['edges']} |")
    a(f"| COMPATIBILITY_INVALID edges | {len(compat['invalid'])} |")
    a(f"| COMPATIBILITY_UNVERIFIED edges | {len(compat['unverified'])} |")
    a(f"| plate rows | {plate_audit['rows']} |")
    a(f"| plate row conflicts (>1 per SKU) | {len(plate_audit['conflicts'])} |")
    a(f"| plate index issues from the sweep | {len(plate_audit['sweep']['issues'])} |")
    a(f"| kit rows | {plate_audit['kitSweep']['checked']} |")
    a(f"| source files inventoried | {asset_audit['files']} |")
    a(f"| unclassified source files | {asset_audit['unclassified']} |")
    a(f"| selection conflicts (SAME_STEM_DIFFERENT_PHOTOGRAPH) | {len(asset_audit['conflicts'])} |")
    a(f"| token spelling collisions | {len(token_audit['spellingCollisions'])} |")
    a(f"| ambiguous body tokens | {len(token_audit['ambiguousBodies'])} |")
    a(f"| human-review items | {len(human_review)} |")
    a("")
    verdict = "PASSES" if not gate_violations and not collisions and not plate_audit["conflicts"] and asset_audit["unclassified"] == 0 else "FAILS"
    a(f"**Determinism verdict: the publishing path {verdict}.** "
      f"{len(publishable)} SKUs resolve to exactly one Convex document, one familyId and at most one plate row. "
      f"The {len(duplicates)} duplicated website SKUs remain blocked, as does every near-miss.")
    a("")

    a("## 1. Duplicate SKU report")
    a("")
    a(f"{len(duplicates)} website SKUs resolve to more than one Convex product document. Publishing to any of them")
    a("is blocked by `publish.mjs` (it refuses a SKU whose presence count is not exactly one) and reported by")
    a("`productPlates.integrity` as `products_duplicate_websiteSku`. None were merged or deleted by this audit.")
    a("")
    kinds_of_dupe = Counter(d["kind"] for d in duplicates)
    a("| classification | count | meaning |")
    a("|---|---:|---|")
    meaning = {
        "IDENTICAL_RECORD": "same grace SKU, same group — one document is a straight re-import",
        "DISTINCT_PRODUCTS_SHARING_A_WEBSITE_SKU": "different grace SKUs in one group — two real products, one SKU string",
        "SAME_SKU_IN_TWO_FAMILIES": "documents land in different families — one is misfiled, or they are different products",
        "SAME_SKU_DIFFERENT_GROUP": "same SKU across groups without a family split",
    }
    for k, n in kinds_of_dupe.most_common():
        a(f"| `{k}` | {n} | {meaning.get(k, '')} |")
    a("")
    a("<details><summary>Every duplicated SKU (click to expand)</summary>")
    a("")
    a("| websiteSku | kind | docs | Convex document ids | grace SKUs | group(s) | familyId(s) | recommended resolution | confidence |")
    a("|---|---|---:|---|---|---|---|---|---|")
    for d in duplicates:
        a("| `{sku}` | {kind} | {n} | {ids} | {grace} | {groups} | {fids} | {action} | {conf} |".format(
            sku=d["websiteSku"], kind=d["kind"], n=d["documents"],
            ids="<br>".join(f"`{i}`" for i in d["documentIds"]),
            grace="<br>".join(f"`{g}`" for g in d["graceSkus"]) or "—",
            groups="<br>".join(d["groupSlugs"]) or "—",
            fids="<br>".join(f"`{f}`" for f in d["familyIds"]) or "—",
            action=d["recommendedResolution"], conf=d["confidence"]))
    a("")
    a("</details>")
    a("")
    a("Evidence for every row: `data/paper-doll/convex-snapshot.json`, products sharing one `websiteSku`.")
    a("Full machine-readable detail including the per-field spread is in `data/paper-doll/audit-findings.json`.")
    a("")

    a("## 2. Family integrity report")
    a("")
    a(f"`familyId` was recomputed from product and group fields for all {len(snap['products'])} products using the")
    a("implemented grammar `<family>-<capacityMl>ml-<color>-<neck>` (components: `<family>-<neck>`).")
    a("")
    if collisions:
        a("| familyId | necks collapsed | example SKUs |")
        a("|---|---|---|")
        for c in collisions:
            a(f"| `{c['familyId']}` | {', '.join(c['necks'])} | {', '.join(c['skus'][:6])} |")
    else:
        a("**No `FAMILY_ID_COLLISION`.** No two neck finishes recompute to the same familyId — the neck segment is")
        a("doing its job. This is the check that matters most, because dropping the neck would silently merge")
        a("physically incompatible families.")
    a("")
    a(f"**{len(multi_neck)} family/capacity/colour combinations legitimately span more than one neck** and stay")
    a("separate under the grammar:")
    a("")
    a("| family-capacity-colour | necks |")
    a("|---|---|")
    for k, v in sorted(multi_neck.items())[:20]:
        a(f"| `{k}` | {', '.join(v)} |")
    a("")
    a(f"**{len(missing_neck)} products have no neck finish**, so no familyId can be derived and they cannot publish.")
    fam_missing = Counter(m["family"] for m in missing_neck)
    a("They are concentrated in non-bottle lines: " + ", ".join(f"{k} ({n})" for k, n in fam_missing.most_common(8)) + ".")
    a("")
    a("Legacy family aliases resolve as intended:")
    a("")
    a("| legacy id | canonical familyId |")
    a("|---|---|")
    for k, v in LEGACY_ALIASES.items():
        a(f"| `{k}` | `{v}` |")
    a("")

    a("## 3. SKU cross-reference")
    a("")
    a("| match kind | count | publishable? |")
    a("|---|---:|---|")
    for k, n in kinds.most_common():
        ok = "yes" if k in ("exact", "alias") else "**no**"
        a(f"| {k} | {n} | {ok} |")
    a("")
    a(f"The gate `publishable = matchKind ∈ {{exact, alias}} ∧ ¬convexDuplicate ∧ ¬selectionConflict ∧ familyGatePassed`")
    a(f"holds for all {len(publishable)} publishable SKUs: **{len(gate_violations)} violations**. `tokensReviewed` is")
    a(f"enforced separately at publish time and is currently **{'unset — --dist publishing is blocked' if not token_audit['reviewedAt'] else token_audit['reviewedAt']}**.")
    a("")
    a("**The approved aliases are currently doing no work, and that is correct rather than broken.** Each maps a")
    a("library spelling to a catalogue SKU (`GBSleek5SpryGlMatt` -> `GBSleek5SpryGlMt`); all")
    a(f"{alias_health['valueIsCatalogueSku']} of the {alias_health['entries']} values are catalogue SKUs, and all {alias_health['redundant']} of those also exist as a PSD stem in")
    a(f"their own right, so the exact match already succeeds and the alias is never consulted. {alias_health['needed']} aliases are")
    a(f"strictly required today and {alias_health['stale']} are stale. Keep them: they cost nothing and become load-bearing the")
    a("moment a spelling disappears from the library.")
    a("")
    a(f"{len(candidates)} near-misses sit in `alias-candidates.json` awaiting manual promotion. They are")
    a("case-only differences of the form `AnSp…`/`Ansp…` plus a handful of Boston Round dropper spellings.")
    a("None was promoted by this audit.")
    a("")
    a("Products with no PSD, classified:")
    a("")
    a("| reason | count |")
    a("|---|---:|")
    for k, n in no_psd_class.most_common():
        a(f"| {k} | {n} |")
    a("")
    a("Catalogue-image fallback covers these; no paper-doll asset was manufactured to reach coverage.")
    a("")

    a("## 4. Website reconciliation")
    a("")
    a("bestbottles.com was used as external evidence, never as an automatic overwrite. Material discrepancies")
    a("found and their disposition:")
    a("")
    a("| SKU | Convex value | bestbottles.com | recommended | confidence | action |")
    a("|---|---|---|---|---|---|")
    a("| `GBDiva46DrpSl` | group `diva-46ml-frosted-18-415-dropper` | described with gold and copper as one clear family; 3 clear dropper detail pages in the sitemap | clear group | high | **applied on dev** — moved |")
    a("| `GBDiva46Drp{Gl,Cu,Sl}` | graceSku `GB-DVA-FRS-46ML-DRP-*` | products are clear glass | `GB-DVA-CLR-46ML-DRP-*` | high | **applied on dev** — renamed |")
    a("| `GBDivaFrst46DrpCu` | absent | live listing `large-dropper-bottles.php`, $2.90/$2.76/$2.61/$2.47/$2.26, no detail page | create | high | **applied on dev** — created |")
    a("| `GBDivaFrst46Drp{Gl,Sl}` | absent | not in live markup; Nemat confirms both sell | create at the frosted ladder | medium — price by family convention, not a listing | **applied on dev** — created, flagged |")
    a("| 72 SKUs spelling `Frst` | group colour says clear | — | HUMAN_REVIEW_REQUIRED | medium | not changed |")
    a("")
    a("The 72 frosted-token SKUs filed under clear groups are reported by `xref.py` as")
    a("`sku_says_frosted_catalogue_says_clear` and are listed in `data/paper-doll/xref.json`. They are not")
    a("corrected here: each needs a decision on whether the SKU or the group is wrong.")
    a("")

    a("## 5. Component compatibility report")
    a("")
    a(f"{compat['edges']} declared component relationships were checked with neck finish as a first-order")
    a("attribute. Thread was read from the component's own grace SKU (`CMP-CAP-BLK-18415-LTR` → 18-415) and")
    a("compared with the product's `neckThreadSize`. Nothing was inferred from appearance, folder or colour.")
    a("")
    a("| verdict | edges |")
    a("|---|---:|")
    a(f"| confirmed (threads agree) | {compat['edges'] - len(compat['invalid']) - len(compat['unverified'])} |")
    a(f"| `COMPATIBILITY_INVALID` | {len(compat['invalid'])} |")
    a(f"| `COMPATIBILITY_UNVERIFIED` | {len(compat['unverified'])} |")
    a("")
    if not compat["invalid"]:
        a("**No `COMPATIBILITY_INVALID` edge exists.** Every component whose thread can be read is declared only on")
        a("bottles of that same thread: 55,170 edges on 18-415, 9,996 on 13-415, 2,732 on 17-415, 1,391 on 20-400,")
        a("147 on 15-415, 129 on 18-400, 20 on 8-425. The stored compatibility data is thread-consistent.")
        a("")
    if compat["invalidPairs"]:
        a("Invalid edges by thread pair (bottle → component):")
        a("")
        a("| bottle neck | component neck | edges |")
        a("|---|---|---:|")
        for (bottle, comp_thread), n in compat["invalidPairs"].most_common(15):
            a(f"| {bottle} | {comp_thread} | {n} |")
        a("")
        a("Examples:")
        a("")
        for e in compat["invalid"][:8]:
            a(f"- `{e['websiteSku']}` ({e['bottleNeck']}) declares `{e['component']}` ({e['componentNeck']})")
    a("")
    if compat["unverified"]:
        unverified_components = Counter(e["component"] for e in compat["unverified"])
        a(f"All {len(compat['unverified'])} unverified edges come from just {len(unverified_components)} component SKUs that")
        a("carry no thread designation, so their fit cannot be established from the data:")
        a("")
        a("| component SKU | edges | note |")
        a("|---|---:|---|")
        notes = {
            "CMP-SPR-SLV-": "malformed SKU — trailing separator, no thread",
            "CMP-SPR-CLR-30ML": "names a capacity, not a thread",
            "CMP-PLUG-BLK-VIAL": "orphan: no product document defines it",
            "CMP-PLUG-WHT-VIAL": "orphan: no product document defines it",
            "BB-ALU250SPRYBL": "a product id, not a component id",
            "BB-CREAMJARAMB5MLSLCAP": "a product id, not a component id",
        }
        for c, n in unverified_components.most_common():
            a(f"| `{c}` | {n} | {notes.get(c, 'no thread designation')} |")
        a("")
        a("These are `COMPATIBILITY_UNVERIFIED`, not `COMPATIBILITY_INVALID`: nothing shows them to be wrong,")
        a("and nothing shows them to be right. They are review items, not assumptions.")
        a("")
    a("`fitments` holds 63 thread rules that `getCompatibleFitments` already applies at read time; this audit")
    a("checks the stored edges themselves, which the runtime filter can hide but not fix.")
    a("")

    a("## 6. Physical component reuse report")
    a("")
    a("A different SKU does not imply a different physical part, and a different finish does not imply different")
    a("geometry. How widely each component is already shared:")
    a("")
    buckets = Counter()
    for r in reuse:
        n = r["skus"]
        bucket = "1" if n == 1 else "2–10" if n <= 10 else "11–100" if n <= 100 else "101–1000" if n <= 1000 else "1000+"
        buckets[bucket] += 1
    a("| SKUs referencing the component | components |")
    a("|---|---:|")
    for b in ("1", "2–10", "11–100", "101–1000", "1000+"):
        if buckets[b]:
            a(f"| {b} | {buckets[b]} |")
    a("")
    a("The largest group is the standard 18-415 closure set — 18 sprayers, pumps, caps and droppers each")
    a(f"referenced by {reuse[0]['skus']} SKUs across {reuse[0]['families']} families. That is reuse working as intended: one component")
    a("record, many products pointing at it.")
    a("")
    a("### Components registered under more than one id")
    a("")
    a(f"{len(shared_descriptors)} component descriptors exist as several component ids (the id minus its trailing `-NN`).")
    a("These are the candidates for one physical part represented as unrelated components — but the suffix is not")
    a("always cosmetic, so **none is merged here**:")
    a("")
    a("| descriptor | ids | website SKUs | descriptions | verdict |")
    a("|---|---|---|---|---|")
    for d in shared_descriptors:
        a("| `{k}` | {ids} | {skus} | {names} | {v} |".format(
            k=d["descriptor"],
            ids="<br>".join(f"`{i}`" for i in d["componentIds"]),
            skus="<br>".join(f"`{x}`" for x in d["websiteSkus"]),
            names="<br>".join(n[:70] for n in d["itemNames"]) or "—",
            v=d["verdict"]))
    a("")
    a("Two patterns, and they need opposite treatment:")
    a("")
    a("- **Genuinely different parts.** `CMP-DRP-WHT-20400-76` and `-90` are both \"White rubber bulb dropper with")
    a("  white cap\", but their descriptions end \"glass stem length is 7…\" and \"…9…\" — a 1 oz and a 2 oz dropper.")
    a("  Merging them on the strength of a shared descriptor would put the wrong stem in the bottle.")
    a("- **One part, several finishes.** `CMP-CAP-BLK-13-415-01` and `-02` carry the identical description")
    a("  \"Cap/Closure Thread 13-415\" and differ only as `CP13-415SpryBlkMt` (matte) versus `CP13-415SpryBlkSh`")
    a("  (shiny). Same geometry, different material — the case where geometry should be shared and only the")
    a(f"  material token differs. {sum(1 for d in shared_descriptors if d['identicalNames'])} of the {len(shared_descriptors)} groups have identical descriptions and are in the review queue.")
    a("")
    shared = [r for r in reuse if r["skus"] > 1]
    a(f"{len(shared)} of {len(reuse)} distinct components are already referenced by more than one SKU, so reuse is")
    a("canonical at the component level: the catalogue stores one component grace SKU and points many products")
    a("at it. No duplicate geometry is introduced by the plate pipeline — plate objects are content-addressed,")
    a("so a part photographed once yields one object however many SKUs show it.")
    a("")
    a("The 9 mL cylinder is the architectural pattern to preserve: 26 reusable layers compose 145 configurations,")
    a("and because keys start with the SHA-256 of the bytes, those 145 configurations cost 52 stored objects, not 145.")
    a("")

    a("## 7. Asset integrity report")
    a("")
    a(f"- {asset_audit['files']} source files inventoried; **{asset_audit['unclassified']} unclassified**.")
    a(f"- Roles: {asset_audit['roles']}")
    a(f"- Excluded with a reason code: {asset_audit['junk']}")
    a(f"- {asset_audit['multiLocationAssets']} chosen assets carry more than one provenance location; all locations are kept.")
    a(f"- {len(asset_audit['conflicts'])} `SAME_STEM_DIFFERENT_PHOTOGRAPH` conflicts remain hard selection conflicts — nothing is chosen for them.")
    a(f"- {asset_audit['hiresSetAside']} hi-res files set aside before registration.")
    a(f"- Thumbnails or views selected as a canonical front plate: **{len(asset_audit['thumbnailsChosenAsFront'])}**.")
    a("")
    if asset_audit["conflicts"]:
        a("Selection conflicts (each needs a human decision, none may publish):")
        a("")
        for c in asset_audit["conflicts"][:25]:
            a(f"- `{c['stem']}` [{c['state']}]: " + " vs ".join(Path(p).name for p in c["candidates"]))
        a("")

    a("## 8. Plate and kit integrity")
    a("")
    a(f"- {plate_audit['rows']} plate rows across {len({r['familyId'] for r in json.loads((DATA / 'plates-snapshot.json').read_text())['plates']})} families.")
    a(f"- Plate rows resolving more than once for a canonical SKU: **{len(plate_audit['conflicts'])}**.")
    a(f"- Field issues (missing front, grace mismatch, missing familyId): **{len(plate_audit['fieldIssues'])}**.")
    a(f"- `productPlates.integrity` reports {len(plate_audit['sweep']['issues'])} issues, all of class")
    a("  `products_duplicate_websiteSku` — the catalogue's duplicates surfacing through the index, not index defects.")
    a(f"- `productKits` holds {plate_audit['kitSweep']['checked']} rows: kits are built but not yet published, so")
    a("  `published kit → matching published plate` and `plateSha256 == the plate used for registration` are")
    a("  vacuously true today and must be enforced the moment the first kit publishes.")
    a("")
    completeness = kit_audit["completeness"]
    a(f"The kit audit over {kit_audit['audited']} publishable SKUs found: {completeness}.")
    a(f"{kit_audit['pairSharedBody'].get('True', 0)} capped/uncapped pairs share a pixel-identical body, which is what")
    a("lets a kit be cut without anchoring anything.")
    a("")

    a("## 9. Token system")
    a("")
    a(f"- `reviewedAt`: **{token_audit['reviewedAt'] or 'unset — publishing from the pipeline manifest is blocked'}**.")
    a(f"- Spelling collisions (one spelling, two canonical finishes): **{len(token_audit['spellingCollisions'])}**.")
    a(f"- Ambiguous body tokens (one body, several familyIds): **{len(token_audit['ambiguousBodies'])}**.")
    a(f"- Bodies with no familyId: {len(token_audit['bodiesWithoutFamily'])}.")
    a(f"- SKUs that do not parse from the vocabulary: {len(token_audit['unparsed'])}.")
    a("")
    if token_audit["ambiguousBodies"]:
        a("| body token | familyIds it resolves to |")
        a("|---|---|")
        for b, v in sorted(token_audit["ambiguousBodies"].items()):
            fids = ", ".join(f"`{k}` ({n})" for k, n in list(v["familyIds"].items())[:4])
            a(f"| `{b}` | {fids} |")
        a("")
        a("Each of these is a body token that two catalogue families spell the same way — for example a frosted")
        a("body filed under a clear group. They are reported, not auto-resolved: the body token is a label, and")
        a("`familyId` still comes from the product fields.")
        a("")

    a("## 10. Human review queue")
    a("")
    a("| # | item | decision required | class | confidence |")
    a("|---:|---|---|---|---|")
    for i, h in enumerate(human_review[:60], 1):
        a(f"| {i} | {h['item']} | {h['decision']} | `{h['kind']}` | {h['confidence']} |")
    if len(human_review) > 60:
        a(f"| … | {len(human_review) - 60} further items | see `data/paper-doll/audit-findings.json` | | |")
    a("")

    a("## 11. Machine-readable matrix")
    a("")
    a("`data/paper-doll/audit-matrix.json` carries both directions:")
    a("")
    a("- `bySku`: websiteSku → graceSku, familyId, body, neck, matchKind, publishable, blockReasons,")
    a("  physicalComponents, plate, kit.")
    a("- `byComponent`: component grace SKU → SKU count, family count, necks, example SKUs.")
    a("")
    a("It uses the production ids and introduces no parallel identity system.")
    a("")

    a("## 12. Integrity test coverage")
    a("")
    a("`scripts/paperdoll/verify.mjs` exits non-zero on index failures. Coverage today:")
    a("")
    a("| check | enforced by | status |")
    a("|---|---|---|")
    rows = [
        ("duplicate Convex website SKU", "productPlates.integrity → products_duplicate_websiteSku", "reported; fails under --strict"),
        ("multiple plate rows for one SKU", "productPlates.integrity → duplicate_index_rows; upsertMany refuses", "hard fail"),
        ("orphan plate", "productPlates.integrity → orphan_plate; publish skips", "hard fail"),
        ("incorrect grace SKU", "productPlates.integrity → grace_sku_mismatch", "hard fail"),
        ("malformed familyId / missing neck", "xref.py familyId gate", "blocks publishing"),
        ("unsupported alias / near-miss marked publishable", "xref.py assertion", "hard fail in the builder"),
        ("unpublished selection conflict imported", "dedupe SAME_STEM_DIFFERENT_PHOTOGRAPH → not publishable", "blocks publishing"),
        ("missing plate front", "productPlates.integrity → missing_front", "hard fail"),
        ("invalid asset host", "productPlates.integrity → url_host_not_allowed", "hard fail"),
        ("incorrect content hash", "publish.mjs hash drift check before upload", "hard fail"),
        ("kit without a plate / mismatched plateSha256", "productKits.integrity → kit_without_plate, kit_stale_plate", "hard fail"),
        ("unresolved token", "tokens.json reviewedAt gate in publish.mjs --dist", "blocks publishing"),
        ("invalid component-family mapping", "products.componentIntegrity → component_thread_mismatch", "**added by this audit**; 0 today"),
        ("orphan component reference", "products.componentIntegrity → component_reference_unknown", "**added by this audit**; 2 today"),
    ]
    for check, by, status in rows:
        a(f"| {check} | {by} | {status} |")
    a("")
    a("This audit added the last two. `verify.mjs` now sweeps all 70,541 component edges on every run and prints")
    a("what it finds; like the duplicate-SKU check that was already there, they are classed as catalogue defects")
    a("rather than index defects, so a plate publish is not blocked by a component the catalogue has mislabelled —")
    a("but `verify.mjs --strict` fails on them, and nothing was downgraded to a silent pass. Sample run:")
    a("")
    a("```")
    a("productPlates: 280 rows, 0 index issues, 49 catalogue issues")
    a("productKits: 0 rows, 0 index issues, 0 catalogue issues")
    a("components: 2477 products, 70541 edges, 131 distinct components, 2 catalogue issues")
    a("   ~~ CMP-PLUG-WHT-VIAL: component_reference_unknown no product document defines this component")
    a("   ~~ CMP-PLUG-BLK-VIAL: component_reference_unknown no product document defines this component")
    a("```")
    a("")
    (DOCS / "best-bottles-canonical-data-audit.md").write_text("\n".join(L) + "\n")
    print(f"wrote {(DOCS / 'best-bottles-canonical-data-audit.md').relative_to(REPO)} ({len(L)} lines) in {time.time() - started:.0f}s")
    print(f"     {len(duplicates)} duplicates, {len(collisions)} family collisions, {len(compat['invalid'])} invalid component edges, {len(human_review)} review items")


if __name__ == "__main__":
    main()
