#!/usr/bin/env python3
"""
Emit src/lib/paper-doll/tokens.generated.ts from tokens.json.

The product page reads a cap finish off the website SKU when the catalogue's
capColor is missing or wrong ("Clear" on a black cap). That table was typed by
hand and covered 21 spellings; the catalogue actually uses 45 across 38
finishes. This writes the table from the reviewed vocabulary instead, so the
two can never drift.

    python3 scripts/paperdoll/emit_tokens_ts.py [--check]

--check exits non-zero if the file on disk is not what this would write
(for CI, and so a stale table is a failure and not a silent wrong label).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[1]
DATA = REPO / "data" / "paper-doll"
TARGET = REPO / "src" / "lib" / "paper-doll" / "tokens.generated.ts"

# Swatch names the storefront already paints (materialSwatch / COLOR_SWATCH).
# A finish whose label is not one of these keeps its label as the swatch name,
# which is what the hand-written table did.
SWATCH_ALIASES = {
    "Ivory + Gold": "Ivory + Gold",
    "Ivory + Silver": "Ivory + Silver",
    "Clear Overcap": "Clear Overcap",
}


def emit() -> str:
    tokens = json.loads((DATA / "tokens.json").read_text())
    rows = []
    for label, finish in tokens["finishes"].items():
        for spelling in finish["spellings"]:
            rows.append((spelling, label, SWATCH_ALIASES.get(label, label), finish["count"]))
    # longest spelling first so ShnBlk wins over Blk, and MtSlClOvrCap over MtSl
    rows.sort(key=lambda r: (-len(r[0]), r[0]))
    lines = [
        "// GENERATED by scripts/paperdoll/emit_tokens_ts.py from data/paper-doll/tokens.json.",
        "// Do not edit by hand: run the script, or the SKU vocabulary and the page disagree.",
        f"// {tokens['coverage']['parsed']} of {tokens['coverage']['skus']} catalogue SKUs parse from this vocabulary"
        f" ({len(tokens['finishes'])} finishes, {len(rows)} spellings).",
        f"// tokens.json generatedAt {tokens['generatedAt']}, reviewedAt {tokens.get('reviewedAt') or 'not yet reviewed'}.",
        "",
        "export type FinishToken = { label: string; swatchName: string };",
        "",
        "/** Website-SKU finish suffixes, longest first. */",
        "export const WEBSITE_SKU_FINISHES: Array<[string, FinishToken]> = [",
    ]
    for spelling, label, swatch, count in rows:
        lines.append(f'    ["{spelling}", {{ label: "{label}", swatchName: "{swatch}" }}],   // {count}')
    lines += [
        "];",
        "",
        "/**",
        " * The finish a website SKU spells, or null. The decorative-ring modifier is",
        " * stripped first: a ring variant is the same closure in the same finish.",
        " */",
        "export function getFinishFromWebsiteSku(websiteSku: string | null | undefined): FinishToken | null {",
        "    if (!websiteSku) return null;",
        '    const stem = websiteSku.trim().replace(/Rng$/, "");',
        "    for (const [token, finish] of WEBSITE_SKU_FINISHES) {",
        "        if (stem.endsWith(token) && stem.length > token.length) return finish;",
        "    }",
        "    return null;",
        "}",
        "",
    ]
    return "\n".join(lines)


def main():
    text = emit()
    if "--check" in sys.argv:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != text:
            print(f"{TARGET.relative_to(REPO)} is stale — run: python3 scripts/paperdoll/emit_tokens_ts.py", file=sys.stderr)
            sys.exit(1)
        print("tokens.generated.ts is current")
        return
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(text)
    print(f"wrote {TARGET.relative_to(REPO)} ({text.count(chr(10))} lines)")


if __name__ == "__main__":
    main()
