/**
 * Material registry — ONE constructor for every material in the app.
 *
 * WHY
 * Materials used to be built inline wherever they were needed. That is how a
 * gold cap and a gold fitment drift apart: the antique atomizer got a
 * hand-rolled metal whose envMapIntensity was capped at 1.1 against shiny
 * silver's approved 2.4, and it read flat white beside correct caps. Nothing
 * prevented it, because there was no single place a material came from.
 *
 * Now there is. Values come from public/models/tokens.json (physical tokens,
 * generated by scripts/materials/port-tokens.mjs from the approved set) and
 * every material in both the PDP and the lab is built here. A part asks for a
 * name — legacy key or token id — and gets the same memoized instance as any
 * other part asking for the same thing.
 *
 * Contract: no component may construct a MeshPhysicalMaterial for a catalogue
 * part. If a value is wrong, fix the token and both consumers follow.
 */

import * as THREE from "three";

export type TokenSpec = {
  class: string;
  family: string;
  baseColorHex?: string;
  baseColorLinear?: [number, number, number];
  metalness?: number;
  roughness?: number;
  clearcoat?: number;
  ior?: number;
  transmission?: number;
  specularIntensity?: number;
  specularColor?: string;
  provenance?: string;
  lanes?: { web?: Record<string, unknown> };
};

export type TokenFile = {
  schemaVersion: string;
  aliases: Record<string, string>;
  materials: Record<string, TokenSpec>;
  colorManagement: { exposure: number; toneMapping: string };
};

let cache: Promise<TokenFile> | null = null;
/** Loaded once per session and shared; the file is small and immutable. */
export function loadTokens(): Promise<TokenFile> {
  cache ??= fetch("/models/tokens.json").then((r) => r.json());
  return cache;
}

/** Legacy part-name or physical token id -> token id. */
export function resolveId(tokens: TokenFile, name: string): string | null {
  const stripped = name.replace(/_TALL_VIEW$/, "");
  return tokens.aliases[stripped] ?? (tokens.materials[stripped] ? stripped : null);
}

export function getSpec(tokens: TokenFile, name: string): TokenSpec | null {
  const id = resolveId(tokens, name);
  return id ? tokens.materials[id] ?? null : null;
}

type MapSet = { normal: THREE.Texture; rough: THREE.Texture };
export type Envs = {
  metalEnv?: THREE.Texture | null;
  plasticEnv?: THREE.Texture | null;
  /** keyed by the token's lanes.web.maps value: "matte" | "leather" | … */
  maps?: Record<string, MapSet>;
  /** @deprecated pass via `maps.matte` */
  matteMaps?: MapSet;
};

/** True when the token's maps need a UV set the closure GLBs do not carry. */
export function needsCylindricalUV(spec: TokenSpec | null): boolean {
  return Boolean((spec?.lanes?.web as { maps?: string } | undefined)?.maps);
}

/**
 * Build the material for a token. Reproduces the previously-inline logic
 * exactly — this is a refactor, not a retune, so every approved look is
 * byte-identical. The only behavioural change is that there is now one copy
 * of it instead of several.
 */
export function createMaterial(spec: TokenSpec | null, envs: Envs): THREE.MeshPhysicalMaterial {
  const web = (spec?.lanes?.web ?? {}) as {
    envMapIntensity?: number; env?: string; maps?: string;
    opacity?: number; alphaHash?: boolean;
  };
  const mat = new THREE.MeshPhysicalMaterial(
    spec
      ? {
          color: new THREE.Color(spec.baseColorHex ?? "#999999"),
          roughness: spec.roughness ?? 0.4,
          metalness: spec.metalness ?? 0,
          clearcoat: spec.clearcoat ?? 0,
          ior: spec.ior ?? 1.5,
          transmission: spec.transmission ?? 0,
        }
      : { color: 0x999999, roughness: 0.4, metalness: 0.4 },
  );
  if ((spec?.transmission ?? 0) > 0) mat.thickness = 0.002;

  // alpha translucency: transparent objects DO render into three's
  // transmission buffer; transmissive ones do not. alphaHash is stochastic
  // transparency inside the opaque pass — the only translucency that
  // survives being seen through glass.
  if (web.opacity != null && web.opacity < 1) {
    if (web.alphaHash) { mat.alphaHash = true; mat.opacity = web.opacity; }
    else { mat.transparent = true; mat.opacity = web.opacity; mat.depthWrite = false; }
  }

  // library reflectivity: specularIntensity scales dielectric F0 — the pop a
  // glossy black needs that roughness alone cannot give
  if (spec?.specularIntensity != null) mat.specularIntensity = spec.specularIntensity;
  if (spec?.specularColor) mat.specularColor = new THREE.Color(spec.specularColor);

  // any token naming a map set gets it — "matte" for the brushed metals,
  // "leather" for the grain. One branch, so adding a set is data not code.
  const set = web.maps
    ? envs.maps?.[web.maps] ?? (web.maps === "matte" ? envs.matteMaps : undefined)
    : undefined;
  if (set) {
    mat.normalMap = set.normal;
    mat.roughnessMap = set.rough;
    mat.roughness = 1.0;                     // the map IS the roughness
    // leather grain needs more relief than a brushed-metal micro-finish
    const depth = web.maps === "leather" ? 1.0 : 0.6;
    mat.normalScale = new THREE.Vector2(depth, depth);
  }

  const glossy = (spec?.metalness ?? 0) >= 0.85 || (spec?.roughness ?? 1) <= 0.3;
  mat.envMap =
    web.env === "tent" ? envs.plasticEnv ?? null
    : web.env === "metal" ? envs.metalEnv ?? null
    : glossy ? envs.metalEnv ?? null : envs.plasticEnv ?? null;
  mat.envMapIntensity = web.envMapIntensity ?? (glossy ? 1.15 : 0.9);
  return mat;
}

/** Give closure GLBs (authored without UVs) a cylindrical unwrap for maps. */
export function ensureCylindricalUV(mesh: THREE.Mesh) {
  if (mesh.geometry.getAttribute("uv")) return;
  const pos = mesh.geometry.getAttribute("position");
  const uv = new Float32Array(pos.count * 2);
  mesh.geometry.computeBoundingBox();
  const bb = mesh.geometry.boundingBox as THREE.Box3;
  const hh = Math.max(1e-6, bb.max.y - bb.min.y);
  for (let i = 0; i < pos.count; i++) {
    uv[i * 2] = Math.atan2(pos.getX(i), pos.getZ(i)) / (2 * Math.PI) + 0.5;
    uv[i * 2 + 1] = (pos.getY(i) - bb.min.y) / hh;
  }
  mesh.geometry.setAttribute("uv", new THREE.BufferAttribute(uv, 2));
}
