/**
 * Studio environment presets — versioned data, like the glass.
 *
 * WHY THIS IS A FILE AND NOT JSX
 * ------------------------------
 * Glass has almost no appearance of its own: it is a mirror and a lens, so what
 * you see is the ENVIRONMENT, bent. That makes the studio as much a part of the
 * product's look as `attenuationColor` — and just as deserving of being pinned,
 * reviewed and shipped as data. A studio that lives inside a component gets
 * quietly edited and nobody can tell which render came from which lighting.
 *
 * THE FAILURE THIS EXISTS TO PREVENT
 * ----------------------------------
 * A narrow, hot emitter reflects off a cylinder as a HARD WHITE STRIPE, and
 * that stripe swims across the glass as the bottle rotates. The original rig
 * used two rim sources at intensity 22 and 18 scaled [0.35, 3.0] — narrow and
 * hot — which produced exactly that. The same mistake, with a rectangular area
 * light, produced the "white card" artefact in the Blender bench.
 *
 * The fix is not dimmer lights. It is WIDER, FEATHERED ones: a broad source
 * wraps the edge and reads as a gradient that slides as the bottle turns, which
 * is what real studio glass does.
 */

export type StudioPresetId = "softbox-tent" | "room" | "lightformer-rig";

export type StudioPreset = {
  id: StudioPresetId;
  label: string;
  /** equirectangular HDR served from /public, or null to use in-scene lights */
  hdri: string | null;
  environmentIntensity: number;
  /** degrees */
  environmentRotation: number;
  toneMappingExposure: number;
  /** viewport backdrop — glass TRANSMITS this, so a dark one makes dark glass */
  backdrop: string;
  provenance: string;
};

export const STUDIO_PRESETS: Record<StudioPresetId, StudioPreset> = {
  "softbox-tent": {
    id: "softbox-tent",
    label: "Softbox tent",
    hdri: "/models/studio-browser.hdr",
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 1.05,
    backdrop: "#e9e6e0",
    provenance:
      "Generated by pipeline/paper-doll-3d/scripts/make_studio_hdri.py " +
      "--browser. Every emitter is a feathered ellipse; nothing has a hard " +
      "edge. Dynamic range 0.45–8.6, deliberately LOW contrast: three.js " +
      "mirrors the environment onto the surface, so a hot narrow source paints " +
      "a stripe that swims when the bottle rotates. Broad and dim gives a " +
      "sliding gradient instead. " +
      "NOTE the sibling profile (no --browser) is the CYCLES one: dark ambient, " +
      "hot emitters, range 0.046–23.6. The two renderers need opposite things " +
      "and the files must not be swapped.",
  },
  room: {
    id: "room",
    label: "Room",
    hdri: "/models/studio-room.hdr",
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 0.91,
    backdrop: "#e9e6e0",
    provenance:
      "APPROVED STUDIO as of 2026-08-31 (Jordan, with the amber preset). " +
      "Generated by make_studio_hdri.py --room (v8). A room for the glass to " +
      "MIRROR (Aesop-style sheen), built after probing Pacdora: one broad " +
      "key softbox, one tall-but-wide window, warm floor, ambient shell. " +
      "Every emitter fully feathered (soft=1.0), range 0.36-7.8. The first " +
      "cut of this rig was in-scene Lightformer RECTS - and their hard edges " +
      "mirrored as vertical lines down the cylinder, the exact banned " +
      "artefact. Rooms are HDRIs here, never JSX panels.",
  },
  "lightformer-rig": {
    id: "lightformer-rig",
    label: "Lightformer rig (legacy)",
    hdri: null,
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 1.05,
    backdrop: "#e9e6e0",
    provenance:
      "The original in-scene rig from /lab/bottle-3d. Kept for comparison. " +
      "Its rim pair (intensity 22 and 18, scale [0.35, 3.0]) is narrow and hot " +
      "and is what produces the hard vertical stripes down a cylinder.",
  },
};

export const APPROVED_STUDIO: StudioPresetId = "room";
