/**
 * Studio environment presets — versioned data, like the glass.
 *
 * WHY THIS IS A FILE AND NOT JSX
 * ------------------------------
 * Glass has almost no appearance of its own: it is a mirror and a lens, so what
 * you see is the ENVIRONMENT, bent. That makes the studio as much a part of the
 * product's look as `attenuationColor` — and just as deserving of being pinned,
 * reviewed and shipped as data. A studio that lives inside a component gets
 * quietly edited and nobody can tell which render came from which lighting.
 *
 * THE FAILURE THIS EXISTS TO PREVENT
 * ----------------------------------
 * A narrow, hot emitter reflects off a cylinder as a HARD WHITE STRIPE, and
 * that stripe swims across the glass as the bottle rotates. The original rig
 * used two rim sources at intensity 22 and 18 scaled [0.35, 3.0] — narrow and
 * hot — which produced exactly that. The same mistake, with a rectangular area
 * light, produced the "white card" artefact in the Blender bench.
 *
 * The fix is not dimmer lights. It is WIDER, FEATHERED ones: a broad source
 * wraps the edge and reads as a gradient that slides as the bottle turns, which
 * is what real studio glass does.
 */

export type StudioPresetId =
  "softbox-tent" | "room" | "mono-studio" | "lightformer-rig" | "hybrid-small08"
  | "universal-cone";

export type StudioPreset = {
  id: StudioPresetId;
  label: string;
  /** equirectangular HDR served from /public, or null to use in-scene lights */
  hdri: string | null;
  /** true = the scene shell mounts <StudioEnvironment/> instead of passing
   *  `hdri` straight to drei. Named for WHO OWNS the environment, not for what
   *  it contains: this was `hybrid` while the rig was an HDRI with quads
   *  composited over it, and kept that name for one commit after the quads
   *  were deleted — at which point the flag was claiming a hybrid that no
   *  longer existed. The shipping rig is a single generated cone. */
  managedEnv?: boolean;
  /** true = glossy/metal parts inherit THIS environment instead of the
   *  separate metal studio. The handoff's actual architecture: exactly one
   *  environment, no per-material envMap overrides. A black dielectric
   *  reflects ~4% — under the dark metal studio it has nothing to catch and
   *  reads matte, which is what "the shiny black cap is matte" was. */
  unifiedEnv?: boolean;
  environmentIntensity: number;
  /** degrees */
  environmentRotation: number;
  toneMappingExposure: number;
  /** viewport backdrop — glass TRANSMITS this, so a dark one makes dark glass */
  backdrop: string;
  provenance: string;
};

export const STUDIO_PRESETS: Record<StudioPresetId, StudioPreset> = {
  "softbox-tent": {
    id: "softbox-tent",
    label: "Softbox tent",
    hdri: "/models/studio-browser.hdr",
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 1.05,
    backdrop: "#e9e6e0",
    provenance:
      "Generated by pipeline/paper-doll-3d/scripts/make_studio_hdri.py " +
      "--browser. Every emitter is a feathered ellipse; nothing has a hard " +
      "edge. Dynamic range 0.45–8.6, deliberately LOW contrast: three.js " +
      "mirrors the environment onto the surface, so a hot narrow source paints " +
      "a stripe that swims when the bottle rotates. Broad and dim gives a " +
      "sliding gradient instead. " +
      "NOTE the sibling profile (no --browser) is the CYCLES one: dark ambient, " +
      "hot emitters, range 0.046–23.6. The two renderers need opposite things " +
      "and the files must not be swapped.",
  },
  room: {
    id: "room",
    label: "Room",
    hdri: "/models/studio-room.hdr",
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 0.91,
    backdrop: "#e9e6e0",
    provenance:
      "APPROVED STUDIO as of 2026-08-31 (Jordan, with the amber preset). " +
      "Generated by make_studio_hdri.py --room (v8). A room for the glass to " +
      "MIRROR (Aesop-style sheen), built after probing Pacdora: one broad " +
      "key softbox, one tall-but-wide window, warm floor, ambient shell. " +
      "Every emitter fully feathered (soft=1.0), range 0.36-7.8. The first " +
      "cut of this rig was in-scene Lightformer RECTS - and their hard edges " +
      "mirrored as vertical lines down the cylinder, the exact banned " +
      "artefact. Rooms are HDRIs here, never JSX panels.",
  },
  "mono-studio": {
    id: "mono-studio",
    label: "Mono studio (Poly Haven)",
    hdri: "/models/studio-mono.hdr",
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 0.95,
    backdrop: "#e9e6e0",
    provenance:
      "Poly Haven monochrome_studio_02 (CC0, 2k). Tried as the glass studio " +
      "2026-08-31 and REJECTED within minutes (Jordan: 'the monochrome " +
      "lighting is not going to work'). Kept as a lab A/B option only. " +
      "4k EXR master: pipeline/paper-doll-3d/assets/hdri-sources/.",
  },
  "lightformer-rig": {
    id: "lightformer-rig",
    label: "Lightformer rig (legacy)",
    hdri: null,
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 1.05,
    backdrop: "#e9e6e0",
    provenance:
      "The original in-scene rig from /lab/bottle-3d. Kept for comparison. " +
      "Its rim pair (intensity 22 and 18, scale [0.35, 3.0]) is narrow and hot " +
      "and is what produces the hard vertical stripes down a cylinder.",
  },
  "hybrid-small08": {
    id: "hybrid-small08",
    label: "Hybrid studio (Small 08 + formers)",
    hdri: "/env/studio_small_08_1k_peak24.hdr",
    managedEnv: true,
    unifiedEnv: true,
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 0.91, // = RENDER_EXPOSURE; exposure is pinned globally
    backdrop: "#e9e6e0",
    provenance:
      "THE SHIPPING STUDIO. Approved 2026-08-31 (Jordan, at " +
      "/dev/lighting-test: 'the feathered softbox is much better'), briefly " +
      "replaced by 'universal-cone' on 2026-09-01 and RESTORED the same day " +
      "when the cone was rejected: 'it doesn't have that nice sheen — it " +
      "smothers the reflections where they're important.' " +
      "OPEN ISSUE, unresolved: on the fine-mist render Jordan called this rig " +
      "'too many lines'. That is NOT fixed by going back; it is the known " +
      "cost of this rig and the reason the cone was tried. See " +
      "'universal-cone' for what the two complaints have in common and why " +
      "the fix is FEWER azimuthal features, not flatter ones. " +
      "The single environment for the whole scene, per the studio-lighting " +
      "handoff: Poly Haven studio_small_08 (CC0, 1k, self-hosted — no CDN " +
      "preset; PEAK-CLAMPED at luminance 24 — the raw file's ~97 hot texels " +
      "speckled the glass as fireflies) as the neutral coverage base, " +
      "COMBINED in one cubemap with " +
      "four FEATHERED softbox emitters (StudioEnvironment.tsx EMITTERS — " +
      "Gaussian-windowed quads; the first cut used hard-edged drei " +
      "Lightformer rects and their edges printed razor lines down the " +
      "cylinders, the documented banned artefact): L/R vertical strips for " +
      "clear-glass edges, overhead softbox for cap tops, broad dim backlight " +
      "so amber/cobalt transmit. Per-finish variation lives in material " +
      "recipes, never in swapping environments. material_lock.py pins the " +
      "HDRI hash, the EMITTERS values, and this flip.",
  },
  "universal-cone": {
    id: "universal-cone",
    label: "Universal light cone",
    hdri: "/env/studio-universal-softbox.hdr",
    managedEnv: true,
    unifiedEnv: true,
    environmentIntensity: 1.0,
    environmentRotation: 0,
    toneMappingExposure: 0.91, // = RENDER_EXPOSURE; exposure is pinned globally
    backdrop: "#e9e6e0",
    provenance:
      "REJECTED 2026-09-01 (Jordan: 'we're not approving the light cone — it " +
      "doesn't have that nice sheen we were looking for, it smothers the " +
      "reflections where they're important'). Kept for A/B and for the " +
      "geometry note below, which is the most useful thing this lane has " +
      "learned about why its studios fail. Generated end to end by " +
      "pipeline/paper-doll-3d/scripts/make_universal_softbox.py — no " +
      "photographed base and no in-scene emitters, which is the point. " +
      "Jordan's framing is the design: 'think of it like a light cone — it " +
      "really is.' That is the tabletop rig for shiny things: a cone of " +
      "diffusion standing around the subject, open at the bottom, lit from " +
      "outside, used on chrome and glass BECAUSE the fabric integrates every " +
      "lamp behind it into one continuous wall. The rule it buys: a source " +
      "CONTINUOUS IN AZIMUTH has no azimuth to be AT. A cylinder mirrors a " +
      "vertical slice of the world, so a discrete source shows as a line at " +
      "whichever orbit angle faces it — wrap it through 360 deg and no such " +
      "angle exists, so lines cannot return at ANY orbit position. Softness " +
      "becomes a property of the shape instead of a value to tune, which is " +
      "why this ends a run of six rigs that each tried to feather their way " +
      "out of having small sources. The generator's --check counts how many " +
      "separate bright regions a cylinder could mirror; this passes at ONE, " +
      "360 deg wide. Level is calibrated to the retired rig (0.746 " +
      "sin-weighted mean) so the 45 material recipes, all at envMapIntensity " +
      "1.0, keep meaning what they mean. Reference: Carl Taylor's glass " +
      "lighting — large graded sources that drape, never sources you can " +
      "count (Jordan).",
  },
};

// RESTORED to the card rig 2026-09-01 after the cone was rejected. Neither
// rig is right yet: the cone has no lines and no sheen, this one has sheen and
// too many lines. Both follow from the same geometry (see 'universal-cone'):
// on a cylinder a line and a sheen are the SAME azimuthal feature, so the
// unexplored middle is FEWER, BROADER features — not a flatter world.
export const APPROVED_STUDIO: StudioPresetId = "hybrid-small08";
