import {describe,it,expect} from 'vitest';
import {mkdtemp,mkdir,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {readCompletion,completionBinding,validateCompletion,saveCompletion} from '../scripts/asset-ledger/plate-completion.mjs';
import {localBostonPreview,previewPlates} from '../scripts/asset-ledger/product-preview.mjs';
const hash=(v:string)=>createHash('sha256').update(v).digest('hex');
async function fixture(){
 const root=await mkdtemp(path.join(tmpdir(),'bb-completion-'));for(const d of ['public/images/boston-plate-candidates','public/images/boston-source-recovery','data/asset-ledger','src/lib/asset-ledger','master'])await mkdir(path.join(root,d),{recursive:true});
 const assets={'public/images/boston-plate-candidates/front.webp':'front','public/images/boston-source-recovery/source.png':'source','master/master.psd':'master','data/asset-ledger/bottle-standards.json':'{}','data/asset-ledger/boston-plate-contact-decisions.json':'preserved approvals'};for(const [p,v]of Object.entries(assets))await writeFile(path.join(root,p),v);
 const row={sku:'exact-catalog-sku',productGroupId:'group',capacityMl:30,color:'Clear',standardId:'glass',standardVersion:1,standardReferenceSha256:'standard',holds:[],before:[],origin:'new-plate',views:[{label:'Cap on',url:'/images/boston-plate-candidates/front.webp',sha256:hash('front'),source:{sourcePath:'master.psd',sourceSha256:hash('master'),url:'/images/boston-source-recovery/source.png',sha256:hash('source')}}]};
 await writeFile(path.join(root,'src/lib/asset-ledger/ledger.json'),JSON.stringify({rows:[{sku:row.sku,productRecord:true,productGroupId:'group',family:'Boston Round',capacityMl:30,color:'Clear'}]}));
 await writeFile(path.join(root,'data/asset-ledger/boston-plate-completion.json'),JSON.stringify({family:'Boston Round',standardFileSha256:hash('{}'),platePresentations:{30:{glassHeight:800}},rows:[row],preserved:[{sku:'approved'}]}));
 return {root,master:path.join(root,'master'),row};
}
describe('prepared plate review',()=>{
 it('binds new bytes and framing, and leaves published approvals untouched',async()=>{const f=await fixture();try{const s=await readCompletion(f.root,f.master);expect(s.summary).toMatchObject({reviewable:1,approved:0,preserved:1});expect(completionBinding({...f.row,views:[]},s.platePresentations[30])).not.toBe(s.rows[0].binding);expect(completionBinding(f.row,{glassHeight:801})).not.toBe(s.rows[0].binding);expect(await readFile(path.join(f.root,'data/asset-ledger/boston-plate-contact-decisions.json'),'utf8')).toBe('preserved approvals');}finally{await rm(f.root,{recursive:true,force:true});}});
 it('saves exact candidate approvals separately and returns changed renders to review',async()=>{const f=await fixture();try{const s=await readCompletion(f.root,f.master);const input={token:s.token,revision:s.revision,presentationAcknowledged:true,decisions:[{sku:f.row.sku,binding:s.rows[0].binding,status:'approved',notes:''}]};const approved=await saveCompletion(f.root,input,f.master);expect(approved.summary.approved).toBe(1);expect(approved.revision).toBe(1);const file=path.join(f.root,'data/asset-ledger/boston-plate-completion.json');const document=JSON.parse(await readFile(file,'utf8'));document.rows[0].standardVersion=2;await writeFile(file,JSON.stringify(document));const changed=await readCompletion(f.root,f.master);expect(changed.rows[0].status).toBe('pending');expect(changed.summary.approved).toBe(0);expect(await readFile(path.join(f.root,'data/asset-ledger/boston-plate-contact-decisions.json'),'utf8')).toBe('preserved approvals');}finally{await rm(f.root,{recursive:true,force:true});}});
 it('keeps this size valid when an unrelated standard changes',async()=>{const f=await fixture();try{const file=path.join(f.root,'data/asset-ledger/boston-plate-completion.json');const doc=JSON.parse(await readFile(file,'utf8'));const standard={id:'glass',state:'locked',version:1};doc.standardSnapshots={glass:standard};await writeFile(file,JSON.stringify(doc));await writeFile(path.join(f.root,'data/asset-ledger/bottle-standards.json'),JSON.stringify({standards:[standard,{id:'another-family',version:7}]}));expect((await readCompletion(f.root,f.master)).summary.reviewable).toBe(1);await writeFile(path.join(f.root,'data/asset-ledger/bottle-standards.json'),JSON.stringify({standards:[{...standard,version:2}]}));expect((await readCompletion(f.root,f.master)).summary.held).toBe(1);}finally{await rm(f.root,{recursive:true,force:true});}});
 it('holds modified image bytes and changed shared standards',async()=>{const f=await fixture();try{await writeFile(path.join(f.root,'public/images/boston-plate-candidates/front.webp'),'changed');let s=await readCompletion(f.root,f.master);expect(s.summary.held).toBe(1);expect(s.rows[0].holds.join(' ')).toMatch(/bytes changed/);await writeFile(path.join(f.root,'data/asset-ledger/bottle-standards.json'),'{"version":2}');s=await readCompletion(f.root,f.master);expect(s.rows[0].holds.join(' ')).toMatch(/standard changed/);}finally{await rm(f.root,{recursive:true,force:true});}});
 it('requires current sheet, exact binding, framing acknowledgement and resolved holds',async()=>{const f=await fixture();try{const s=await readCompletion(f.root,f.master);const input={token:s.token,revision:s.revision,presentationAcknowledged:true,decisions:[{sku:f.row.sku,binding:s.rows[0].binding,status:'approved',notes:''}]};expect(validateCompletion(s,input)).toHaveLength(1);expect(()=>validateCompletion(s,{...input,presentationAcknowledged:false})).toThrow(/framing/);expect(()=>validateCompletion(s,{...input,revision:9})).toThrow(/changed/);expect(()=>validateCompletion(s,{...input,decisions:[...input.decisions,...input.decisions]})).toThrow(/changed/);s.rows[0].eligible=false;expect(()=>validateCompletion(s,input)).toThrow(/holds/);}finally{await rm(f.root,{recursive:true,force:true});}});
});
describe('local product previews',()=>{
 it('is restricted to development localhost with an explicit flag',()=>{expect(localBostonPreview('development','localhost:3040','boston')).toBe(true);for(const args of [['production','localhost:3040','boston'],['development','example.com','boston'],['development','localhost:3040','no'],['development','localhost.evil:3040','boston']])expect(localBostonPreview(...args)).toBe(false);});
 it('matches exact catalog group and variant, preserves indexed siblings, and skips held drafts',()=>{const current={old:{image:'old',imageCapOff:'old-off'}};const row={sku:'website',productGroupId:'group',eligible:true,status:'pending',views:[{label:'Cap on',url:'draft'},{label:'Cap off',url:'draft-off'}]};const variants=[{websiteSku:'website',graceSku:'grace'}];const result=previewPlates({rows:[row]},'group',variants,current);expect(result.grace).toEqual(result.website);expect(result.website.imageCapOff).toBe('draft-off');expect(result.old).toEqual(current.old);expect(current).not.toHaveProperty('website');expect(previewPlates({rows:[{...row,eligible:false}]},'group',variants,current)).toEqual(current);expect(previewPlates({rows:[row]},'other',variants,current)).toEqual(current);});
});
