"use client";

/**
 * Best Bottles — Material Lab
 *
 * Tune production glass against REAL geometry, in the renderer that ships.
 * Additive only: this reads the existing manifest and GLBs and writes nothing.
 * Values leave via "Copy JSON" — never by overwriting materials.json, which is
 * generated by materials.py and would silently lose a hand edit.
 */

import { Suspense, useEffect, useMemo, useRef, useState, useCallback } from "react";
import { Canvas, useThree } from "@react-three/fiber";
import { OrbitControls, Environment, Lightformer, useGLTF, Center,
         MeshTransmissionMaterial } from "@react-three/drei";
import * as THREE from "three";
import {
  GLASS_PRESETS, applyGlassPreset, roleOf,
  type GlassPreset, type GlassPresetId,
} from "@/lib/materials/glassPresets";

type Body = {
  bodyId: string; family: string; shape: string;
  heightMm: number; diameterMm: number | null;
  widthMm: number | null; depthMm: number | null;
  skuCount: number; url: string; bytes: number;
};

type Measured = {
  wMm: number; hMm: number; dMm: number;
  verts: number; tris: number; meshes: string[];
  materialsInFile: number; unit: string; scaleWarning: string | null;
};

/* ------------------------------------------------------------------ model */

function Model({
  url, preset, envIntensity, transmissionMat, onMeasure,
}: {
  url: string; preset: GlassPreset; envIntensity: number;
  transmissionMat: boolean; onMeasure: (m: Measured) => void;
}) {
  const gltf = useGLTF(url);
  const scene = useMemo(() => gltf.scene.clone(true), [gltf.scene]);
  const materialsInFile: number =
    (gltf as unknown as { parser?: { json?: { materials?: unknown[] } } })
      .parser?.json?.materials?.length ?? 0;

  // Pull the glass mesh OUT of the cloned scene so its material can be a JSX
  // child. drei's MeshTransmissionMaterial is a component, not a constructor -
  // and it is the reason /lab/bottle-3d reads as glass while a plain
  // MeshPhysicalMaterial does not: it renders the BACKSIDE through the front
  // wall and multi-samples the transmission.
  const glass = useMemo(() => {
    let g: THREE.Mesh | null = null;
    scene.traverse((o) => {
      const m = o as THREE.Mesh;
      if (m.isMesh && roleOf(m.name) === "bottle_glass" && !g) g = m;
    });
    if (g) (g as THREE.Mesh).visible = false;
    return g as THREE.Mesh | null;
  }, [scene]);

  useEffect(() => {
    let verts = 0, tris = 0;
    const meshes: string[] = [];
    scene.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      meshes.push(m.name);
      const pos = m.geometry.getAttribute("position");
      verts += pos ? pos.count : 0;
      const idx = m.geometry.getIndex();
      tris += idx ? idx.count / 3 : (pos ? pos.count / 3 : 0);
    });
    if (!glass) return;
    glass.geometry.computeBoundingBox();
    const size = new THREE.Vector3();
    (glass.geometry.boundingBox as THREE.Box3).getSize(size);
    const hMm = size.y * 1000;
    onMeasure({
      wMm: size.x * 1000, hMm, dMm: size.z * 1000,
      verts, tris: Math.round(tris), meshes, materialsInFile,
      unit: "metres (1 world unit = 1 m)",
      scaleWarning:
        hMm > 400 ? `height ${hMm.toFixed(0)} — exported in MILLIMETRES?`
        : hMm < 5 ? `height ${hMm.toFixed(2)} mm — exported too small?`
        : null,
    });
  }, [scene, glass, onMeasure, materialsInFile]);

  // the fallback path, for A/B against the better material
  useEffect(() => {
    if (!glass || transmissionMat) return;
    glass.visible = true;
    applyGlassPreset(glass, { ...preset, envMapIntensity: envIntensity });
    return () => { glass.visible = false; };
  }, [glass, preset, envIntensity, transmissionMat]);

  return (
    <group>
      <primitive object={scene} />
      {glass && transmissionMat ? (
        <mesh geometry={glass.geometry} position={glass.position}
              rotation={glass.rotation} scale={glass.scale}>
          <MeshTransmissionMaterial
            transmission={preset.transmission}
            thickness={preset.thickness}
            backside
            backsideThickness={preset.thickness * 2.6}
            samples={8}
            resolution={512}
            backsideResolution={256}
            roughness={preset.roughness}
            ior={preset.ior}
            chromaticAberration={preset.dispersion * 0.055}
            anisotropicBlur={preset.roughness > 0.4 ? 0.6 : 0.1}
            distortion={0}
            attenuationDistance={preset.attenuationDistance}
            attenuationColor={preset.attenuationColor}
            color="#ffffff"
            envMapIntensity={envIntensity}
          />
        </mesh>
      ) : null}
    </group>
  );
}

/* ------------------------------------------------------------- environment */

function StudioEnv({ intensity, rotationDeg }: { intensity: number; rotationDeg: number }) {
  const { scene } = useThree();
  useEffect(() => {
    // three >= 0.163 — scene-level env controls, no deprecated APIs
    scene.environmentIntensity = intensity;
    scene.environmentRotation = new THREE.Euler(0, (rotationDeg * Math.PI) / 180, 0);
  }, [scene, intensity, rotationDeg]);

  // THE SAME RIG that produces the good renders at /lab/bottle-3d. Copied
  // deliberately rather than invented: glass is read almost entirely through
  // what it MIRRORS, so a lab lit differently from the viewer would tune
  // values that then look wrong in the product.
  //
  // NOT studio.hdr — that file is authored dark-ambient for Cycles, where a
  // bright surround floods dense glass. three.js needs the opposite.
  return (
    <Environment resolution={1024}>
      {/* key */}
      <Lightformer form="rect" intensity={10} color="#ffffff"
                   position={[0, 1.6, 0.9]} rotation={[-Math.PI / 3, 0, 0]}
                   scale={[3.5, 2.6, 1]} />
      {/* fill */}
      <Lightformer form="rect" intensity={3.2} color="#eef2f6"
                   position={[-1.9, 0.5, 0.5]} rotation={[0, Math.PI / 2.4, 0]}
                   scale={[2.2, 3.2, 1]} />
      <Lightformer form="rect" intensity={2.4} color="#f6f2ee"
                   position={[1.9, 0.4, 0.4]} rotation={[0, -Math.PI / 2.4, 0]}
                   scale={[2.0, 3.0, 1]} />
      {/* rim pair — narrow and hot; the bright outline that says "transparent" */}
      <Lightformer form="rect" intensity={22} color="#ffffff"
                   position={[-1.1, 0.7, -1.5]} rotation={[0, Math.PI / 4, 0]}
                   scale={[0.35, 3.0, 1]} />
      <Lightformer form="rect" intensity={18} color="#ffffff"
                   position={[1.1, 0.7, -1.5]} rotation={[0, -Math.PI / 4, 0]}
                   scale={[0.35, 3.0, 1]} />
      {/* floor bounce */}
      <Lightformer form="rect" intensity={1.6} color="#ffffff"
                   position={[0, -1.4, 0.2]} rotation={[Math.PI / 2, 0, 0]}
                   scale={[4, 4, 1]} />
      <Lightformer form="ring" intensity={1.2} color="#ffffff"
                   position={[0, 2.4, -0.6]} scale={[4, 4, 1]} />
    </Environment>
  );
}

/* ------------------------------------------------------------------ camera */

const CAM_PRESETS = {
  front: { azimuth: 0, elevation: 4 },
  threeQuarter: { azimuth: 35, elevation: 12 },
  side: { azimuth: 90, elevation: 4 },
} as const;
type CamPresetId = keyof typeof CAM_PRESETS;

function Rig({ azimuth, elevation, distance, targetY, fov }: {
  azimuth: number; elevation: number; distance: number; targetY: number; fov: number;
}) {
  const { camera } = useThree();
  useEffect(() => {
    const cam = camera as THREE.PerspectiveCamera;
    if (cam.isPerspectiveCamera && cam.fov !== fov) {
      cam.fov = fov; cam.updateProjectionMatrix();
    }
    const a = (azimuth * Math.PI) / 180, e = (elevation * Math.PI) / 180;
    cam.position.set(
      distance * Math.cos(e) * Math.sin(a),
      targetY + distance * Math.sin(e),
      distance * Math.cos(e) * Math.cos(a),
    );
    cam.lookAt(0, targetY, 0);
  }, [camera, azimuth, elevation, distance, targetY, fov]);
  return null;
}

/* ---------------------------------------------------------------- controls */

function Slider({ label, value, min, max, step, onChange, hint }: {
  label: string; value: number; min: number; max: number; step: number;
  onChange: (v: number) => void; hint?: string;
}) {
  return (
    <label style={{ display: "block", marginBottom: 9 }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11 }}>
        <span style={{ color: "#b9b9c4" }}>{label}</span>
        <span style={{ color: "#f0f0f4" }}>{value.toFixed(step < 0.001 ? 5 : 3)}</span>
      </div>
      <input type="range" min={min} max={max} step={step} value={value}
             onChange={(e) => onChange(parseFloat(e.target.value))}
             style={{ width: "100%", accentColor: "#6a6af0" }} />
      {hint ? <div style={{ fontSize: 10, color: "#6f6f7d", marginTop: -2 }}>{hint}</div> : null}
    </label>
  );
}

const btn = (on: boolean): React.CSSProperties => ({
  padding: "4px 9px", fontSize: 11, borderRadius: 4, cursor: "pointer",
  border: "1px solid " + (on ? "#6a6af0" : "#33333c"),
  background: on ? "#23234a" : "#1a1a20", color: "#e8e8ea",
});

/* -------------------------------------------------------------------- page */

export default function MaterialLab(
  { bodies, threadedIds = [] }: { bodies: Body[]; threadedIds?: string[] },
) {
  const [bodyIdx, setBodyIdx] = useState(() =>
    Math.max(0, bodies.findIndex((b) => b.bodyId.startsWith("Cyl-round-17-415"))));
  const [presetId, setPresetId] = useState<GlassPresetId>("amber");
  const [working, setWorking] = useState<GlassPreset>(GLASS_PRESETS.amber);
  const [m, setM] = useState<Measured | null>(null);
  const [envIntensity, setEnvIntensity] = useState(1.0);
  const [envRot, setEnvRot] = useState(0);
  const [exposure, setExposure] = useState(1.05);
  const [cam, setCam] = useState<CamPresetId>("threeQuarter");
  const [distance, setDistance] = useState(0.22);
  const [fov, setFov] = useState(30);
  const [copied, setCopied] = useState(false);
  // Glass TRANSMITS the background. A dark viewport makes even a correct amber
  // render near-black - the values are fine, there is simply nothing behind the
  // bottle to see through it. /lab/bottle-3d gets this right with a light
  // studio backdrop, which is why the same values look rich there.
  const [bg, setBg] = useState("#e9e6e0");
  // MeshTransmissionMaterial renders the BACKSIDE through the front wall and
  // multi-samples; MeshPhysicalMaterial does a single flat backdrop lookup.
  // The difference is most of what separates "glass" from "tinted plastic".
  const [transmissionMat, setTransmissionMat] = useState(true);
  // Default ON: the plain bodies/ build has a FLAT neck (0.00 mm relief).
  // Only bodies-threaded/ carries the drawing-exact helix, and glass
  // magnifies the neck - a flat one is immediately obvious.
  const [threaded, setThreaded] = useState(true);
  // Reference comparison. The photo is held LOCALLY (object URL) — nothing is
  // uploaded. Framing does not need to match: scale/offset/opacity exist so a
  // hand-held shot can still be lined up for judging.
  const [refUrl, setRefUrl] = useState<string | null>(null);
  const [refMode, setRefMode] = useState<"off" | "side" | "overlay">("off");
  const [refOpacity, setRefOpacity] = useState(0.5);
  const [refScale, setRefScale] = useState(1);
  const [refX, setRefX] = useState(0);
  const [refY, setRefY] = useState(0);

  const body = bodies[bodyIdx];
  const hasThreaded = threadedIds.includes(body.bodyId);
  const modelUrl = threaded && hasThreaded
    ? `/models/bodies-threaded/${body.bodyId}.glb`
    : body.url;
  const onMeasure = useCallback((x: Measured) => setM(x), []);

  const loadPreset = (id: GlassPresetId) => {
    setPresetId(id); setWorking({ ...GLASS_PRESETS[id] });
  };
  const set = <K extends keyof GlassPreset>(k: K, v: GlassPreset[K]) =>
    setWorking((p) => ({ ...p, [k]: v }));

  const dirty = useMemo(() => {
    const base = GLASS_PRESETS[presetId];
    return (Object.keys(base) as (keyof GlassPreset)[])
      .some((k) => k !== "provenance" && base[k] !== working[k]);
  }, [presetId, working]);

  const copyJson = async () => {
    const { provenance, ...values } = working;
    await navigator.clipboard.writeText(JSON.stringify(
      { ...values, provenance: dirty ? "TUNED IN MATERIAL LAB — re-solve before shipping" : provenance },
      null, 2));
    setCopied(true); setTimeout(() => setCopied(false), 1400);
  };

  const onPickRef = (f: File | null) => {
    if (refUrl) URL.revokeObjectURL(refUrl);
    if (!f) { setRefUrl(null); setRefMode("off"); return; }
    setRefUrl(URL.createObjectURL(f));
    setRefMode("side");
  };
  useEffect(() => () => { if (refUrl) URL.revokeObjectURL(refUrl); }, [refUrl]);

  const targetY = m ? (m.hMm / 1000) / 2 : 0.035;
  const { azimuth, elevation } = CAM_PRESETS[cam];

  return (
    <div style={{ display: "flex", height: "100vh", background: "#101014", color: "#e8e8ea",
                  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12 }}>
      {refUrl && refMode === "side" ? (
        <div style={{ flex: 1, position: "relative", background: "#0c0c10",
                      borderRight: "1px solid #26262c", overflow: "hidden" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={refUrl} alt="reference"
               style={{ position: "absolute", inset: 0, margin: "auto",
                        maxWidth: "100%", maxHeight: "100%", objectFit: "contain",
                        transform: `translate(${refX}px, ${refY}px) scale(${refScale})` }} />
          <div style={{ position: "absolute", bottom: 8, left: 10, fontSize: 10,
                        color: "#7d7d88" }}>REFERENCE PHOTOGRAPH</div>
        </div>
      ) : null}

      <main style={{ flex: 1, position: "relative" }}>
        <Canvas dpr={[1, 2]} shadows={false}
                camera={{ position: [0.12, 0.05, 0.18], fov }}
                gl={{ antialias: true, toneMapping: THREE.ACESFilmicToneMapping,
                      toneMappingExposure: exposure }}>
          <color attach="background" args={[bg]} />
          <Suspense fallback={null}>
            <Center key={modelUrl}>
              <Model url={modelUrl} preset={working} envIntensity={envIntensity}
                    transmissionMat={transmissionMat}
                     onMeasure={onMeasure} />
            </Center>
            <StudioEnv intensity={envIntensity} rotationDeg={envRot} />
          </Suspense>
          <Rig azimuth={azimuth} elevation={elevation} distance={distance}
               targetY={0} fov={fov} />
          <OrbitControls makeDefault target={[0, 0, 0]} minDistance={0.05} maxDistance={1} />
        </Canvas>

        {refUrl && refMode === "overlay" ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={refUrl} alt="reference overlay"
               style={{ position: "absolute", inset: 0, margin: "auto",
                        maxWidth: "100%", maxHeight: "100%", objectFit: "contain",
                        opacity: refOpacity, pointerEvents: "none",
                        transform: `translate(${refX}px, ${refY}px) scale(${refScale})` }} />
        ) : null}

        {m ? (
          <div style={{ position: "absolute", top: 12, left: 12, padding: "9px 11px",
                        background: "rgba(16,16,20,.88)", border: "1px solid #26262c",
                        borderRadius: 6, lineHeight: 1.55, minWidth: 250 }}>
            <div style={{ fontWeight: 600, marginBottom: 3 }}>{body.bodyId}</div>
            <Row k="height" v={`${m.hMm.toFixed(1)} mm`} />
            <Row k="width × depth" v={`${m.wMm.toFixed(1)} × ${m.dMm.toFixed(1)} mm`} />
            <Row k="world units" v={m.unit} />
            <Row k="materials in file" v={`${m.materialsInFile}`} good={m.materialsInFile === 0} />
            <Row k="verts / tris" v={`${m.verts.toLocaleString()} / ${m.tris.toLocaleString()}`} />
            <Row k="neck" v={threaded && hasThreaded
                   ? "threaded — drawing-exact helix"
                   : hasThreaded ? "PLAIN (flat neck)" : "no threaded build"}
                 good={threaded && hasThreaded} />
            {m.scaleWarning ? <Row k="⚠ scale" v={m.scaleWarning} good={false} /> : null}
          </div>
        ) : null}
      </main>

      <aside style={{ width: 306, padding: 14, overflowY: "auto",
                      borderLeft: "1px solid #26262c" }}>
        <div style={{ fontSize: 13, fontWeight: 600 }}>Material Lab</div>
        <div style={{ color: "#7d7d88", marginBottom: 13 }}>
          glass tuned in the renderer that ships
        </div>

        <Section title="PRESET" />
        <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 6 }}>
          {(Object.keys(GLASS_PRESETS) as GlassPresetId[]).map((id) => (
            <button key={id} onClick={() => loadPreset(id)} style={btn(presetId === id)}>
              {GLASS_PRESETS[id].label}
            </button>
          ))}
        </div>
        <div style={{ fontSize: 10, color: dirty ? "#e8b44a" : "#5fd68a", marginBottom: 12 }}>
          {dirty ? "● working copy — differs from the approved preset" : "○ matches approved preset"}
        </div>

        <Section title="MATERIAL" />
        <Slider label="transmission" value={working.transmission} min={0} max={1} step={0.01}
                onChange={(v) => set("transmission", v)} />
        <Slider label="roughness" value={working.roughness} min={0} max={1} step={0.01}
                onChange={(v) => set("roughness", v)}
                hint="0 = polished · 0.5+ = etched/frosted" />
        <Slider label="ior" value={working.ior} min={1.3} max={1.8} step={0.01}
                onChange={(v) => set("ior", v)} hint="soda-lime glass = 1.52" />
        <Slider label="thickness (m)" value={working.thickness} min={0} max={0.05} step={0.0005}
                onChange={(v) => set("thickness", v)}
                hint="a SCALAR stand-in for optical path — not the real wall" />
        <Slider label="attenuationDistance (m)" value={working.attenuationDistance}
                min={0.001} max={0.5} step={0.001}
                onChange={(v) => set("attenuationDistance", v)}
                hint="pair with thickness — together these ARE the depth" />
        <label style={{ display: "flex", justifyContent: "space-between",
                        alignItems: "center", margin: "2px 0 10px" }}>
          <span style={{ color: "#b9b9c4", fontSize: 11 }}>attenuationColor</span>
          <input type="color" value={working.attenuationColor}
                 onChange={(e) => set("attenuationColor", e.target.value)}
                 style={{ width: 54, height: 22, background: "none", border: "1px solid #33333c" }} />
        </label>
        <Slider label="dispersion" value={working.dispersion} min={0} max={4} step={0.05}
                onChange={(v) => set("dispersion", v)}
                hint="prismatic edge split — the anti-plastic cue" />

        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        margin: "2px 0 4px", cursor: "pointer" }}>
          <input type="checkbox" checked={transmissionMat}
                 onChange={(e) => setTransmissionMat(e.target.checked)} />
          <span>MeshTransmissionMaterial</span>
        </label>
        <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
          backside refraction + 8-sample transmission. Off = plain
          MeshPhysicalMaterial, a single flat backdrop lookup.
        </div>

        <Section title="ENVIRONMENT" />
        <label style={{ display: "flex", justifyContent: "space-between",
                        alignItems: "center", marginBottom: 9 }}>
          <span style={{ color: "#b9b9c4", fontSize: 11 }}>backdrop</span>
          <input type="color" value={bg} onChange={(e) => setBg(e.target.value)}
                 style={{ width: 54, height: 22, background: "none",
                          border: "1px solid #33333c" }} />
        </label>
        <div style={{ display: "flex", gap: 4, marginBottom: 10 }}>
          {[["bone", "#e9e6e0"], ["white", "#f7f7f7"], ["grey", "#8d8d94"],
            ["dark", "#15151a"]].map(([n, c]) => (
            <button key={n} onClick={() => setBg(c)} style={btn(bg === c)}>{n}</button>
          ))}
        </div>
        <Slider label="env intensity" value={envIntensity} min={0} max={4} step={0.05}
                onChange={setEnvIntensity} />
        <Slider label="env rotation °" value={envRot} min={0} max={360} step={1}
                onChange={setEnvRot} />
        <Slider label="exposure" value={exposure} min={0.2} max={2.5} step={0.01}
                onChange={setExposure} />

        <Section title="CAMERA" />
        <div style={{ display: "flex", gap: 4, marginBottom: 8 }}>
          {(Object.keys(CAM_PRESETS) as CamPresetId[]).map((id) => (
            <button key={id} onClick={() => setCam(id)} style={btn(cam === id)}>
              {id === "threeQuarter" ? "¾" : id}
            </button>
          ))}
        </div>
        <Slider label="focal (fov°)" value={fov} min={14} max={60} step={1} onChange={setFov}
                hint="lower = longer lens, less product distortion" />
        <Slider label="distance (m)" value={distance} min={0.06} max={0.6} step={0.005}
                onChange={setDistance} />

        <Section title="EXPORT" />
        <button onClick={copyJson}
                style={{ ...btn(false), width: "100%", padding: "7px 0", marginBottom: 5 }}>
          {copied ? "copied ✓" : "Copy preset JSON"}
        </button>
        <button onClick={() => loadPreset(presetId)}
                style={{ ...btn(false), width: "100%", padding: "7px 0" }}>
          Reset to approved
        </button>
        <div style={{ fontSize: 10, color: "#6f6f7d", margin: "7px 0 12px" }}>
          Nothing is written to materials.json — that file is generated by
          materials.py and a hand edit would be lost on the next extract.
        </div>

        <Section title="REFERENCE" />
        <input type="file" accept="image/*"
               onChange={(e) => onPickRef(e.target.files?.[0] ?? null)}
               style={{ fontSize: 10, color: "#9a9aa6", marginBottom: 7, width: "100%" }} />
        {refUrl ? (
          <>
            <div style={{ display: "flex", gap: 4, marginBottom: 8 }}>
              {(["off", "side", "overlay"] as const).map((mode) => (
                <button key={mode} onClick={() => setRefMode(mode)} style={btn(refMode === mode)}>
                  {mode}
                </button>
              ))}
            </div>
            {refMode === "overlay" ? (
              <Slider label="overlay opacity" value={refOpacity} min={0} max={1} step={0.01}
                      onChange={setRefOpacity} />
            ) : null}
            <Slider label="ref scale" value={refScale} min={0.3} max={2.5} step={0.01}
                    onChange={setRefScale}
                    hint="framing need not match — line it up here" />
            <Slider label="ref offset X" value={refX} min={-300} max={300} step={1}
                    onChange={setRefX} />
            <Slider label="ref offset Y" value={refY} min={-300} max={300} step={1}
                    onChange={setRefY} />
            <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
              Held locally — nothing is uploaded. Your photo&apos;s LIGHTING is not
              copied into the browser; only the glass is being compared.
            </div>
          </>
        ) : (
          <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
            Load a photo of the real bottle. Cap off, background visible beside
            it, not blown out. Size and framing do not matter.
          </div>
        )}

        <Section title="MODEL" />
        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        marginBottom: 8, cursor: hasThreaded ? "pointer" : "default",
                        opacity: hasThreaded ? 1 : 0.45 }}>
          <input type="checkbox" checked={threaded && hasThreaded} disabled={!hasThreaded}
                 onChange={(e) => setThreaded(e.target.checked)} />
          <span>threaded neck (real helix)</span>
        </label>
        {bodies.map((b, i) => (
          <button key={b.bodyId} onClick={() => setBodyIdx(i)}
                  style={{ display: "block", width: "100%", textAlign: "left",
                           padding: "4px 6px", marginBottom: 2, borderRadius: 4,
                           cursor: "pointer", fontSize: 10.5,
                           border: "1px solid " + (i === bodyIdx ? "#6a6af0" : "transparent"),
                           background: i === bodyIdx ? "#23234a" : "transparent",
                           color: "#d2d2d8" }}>
            <div style={{ whiteSpace: "nowrap", overflow: "hidden",
                          textOverflow: "ellipsis" }}>{b.bodyId}</div>
            <div style={{ color: "#7d7d88" }}>{b.shape} · {b.skuCount} SKUs</div>
          </button>
        ))}
      </aside>
    </div>
  );
}

function Section({ title }: { title: string }) {
  return <div style={{ fontSize: 10, letterSpacing: 1, color: "#6a6af0",
                       borderTop: "1px solid #26262c", paddingTop: 9,
                       margin: "12px 0 8px" }}>{title}</div>;
}

function Row({ k, v, good }: { k: string; v: string; good?: boolean }) {
  return (
    <div style={{ display: "flex", gap: 8 }}>
      <span style={{ color: "#7d7d88", minWidth: 108 }}>{k}</span>
      <span style={{ color: good === undefined ? "#d2d2d8" : good ? "#5fd68a" : "#ff6b6b" }}>{v}</span>
    </div>
  );
}
