"use client";

/**
 * Best Bottles — Material Lab
 *
 * Tune production glass against REAL geometry, in the renderer that ships.
 * Additive only: this reads the existing manifest and GLBs and writes nothing.
 * Values leave via "Copy JSON" — never by overwriting materials.json, which is
 * generated by materials.py and would silently lose a hand edit.
 */

import { Suspense, useEffect, useMemo, useRef, useState, useCallback } from "react";
import { Canvas, useThree } from "@react-three/fiber";
import { OrbitControls, Environment, Lightformer, useGLTF, useTexture,
         useEnvironment, Center,
         MeshTransmissionMaterial, Caustics, ContactShadows } from "@react-three/drei";
import * as THREE from "three";
import { useMetalStudioHdri, METAL_STUDIO_DEFAULTS, APPROVED_METAL_STUDIO,
         type MetalStudioParams, type MetalStudioId } from "@/lib/materials/metalStudio";
import {
  GLASS_PRESETS, applyGlassPreset, roleOf,
  type GlassPreset, type GlassPresetId,
} from "@/lib/materials/glassPresets";
import {
  STUDIO_PRESETS, APPROVED_STUDIO,
  type StudioPresetId,
} from "@/lib/materials/studioPresets";
import { StudioEnvironment } from "@/components/products/StudioEnvironment";

type Body = {
  bodyId: string; family: string; shape: string;
  heightMm: number; diameterMm: number | null;
  widthMm: number | null; depthMm: number | null;
  skuCount: number; url: string; bytes: number;
};

type Measured = {
  wMm: number; hMm: number; dMm: number;
  verts: number; tris: number; meshes: string[];
  materialsInFile: number; unit: string; scaleWarning: string | null;
};

/* ------------------------------------------------------------------ model */

/** Lane B's 17-415 closure set, seated per its manifest contract: every part
 *  origins at the neck rim; parent to BB_ATTACH_NECK and zero the transform.
 *  This is what Pacdora's clear bottle taught us: colourless glass reads as
 *  glass when it has CONTENT of its own to refract — their dip tube, our
 *  steel roller descending into the neck. Also the first configurator joint:
 *  same parts, same datum, same materials.json. */
const CLOSURE_MATS: Record<string, { color: string; roughness: number;
  metalness: number; clearcoat?: number }> = {} as never;

export type MatOverride = {
  color?: string; roughness?: number; envMapIntensity?: number;
} | null;

type LabClosure = "none" | "capped" | "roller" | "rollerCapped"
  | "sprayer" | "sprayerCapped" | "pump" | "pumpCapped";

function Closure({ mode, neckY, capMat, ballMat, capTune, trimMat, metalTune,
                   metalStudioId, capFinish = "17-415" }: {
  mode: LabClosure; neckY: number;
  capMat: string; ballMat: string; capTune: MatOverride; trimMat: string;
  metalTune?: Partial<MetalStudioParams>;
  metalStudioId?: MetalStudioId;
  /** the SELECTED BODY's neck finish — closures follow the body so a
   *  O25 18-415 leather cap can never sit on a O20 17-415 bottle
   *  (Jordan's "conflict" screenshot) */
  capFinish?: "17-415" | "18-415";
}) {
  const housing = useGLTF("/models/closures/BB_ROLL_HOUSING_17415_STEEL.glb");
  const ball = useGLTF("/models/closures/BB_ROLL_BALL_17415_STEEL.glb");
  const labFin = capFinish.replace("-", "");
  const cap = useGLTF(`/models/closures/BB_CAP_${labFin}.glb`);
  const cap18 = useGLTF("/models/closures/BB_CAP_18415.glb");
  const cap18Tall = useGLTF("/models/closures/BB_CAP_18415_TALL.glb");
  const cap18Leather = useGLTF("/models/closures/BB_CAP_18415_LEATHER.glb");
  const capDots = useGLTF("/models/closures/BB_CAP_DOTS_17415.glb");
  const collar = useGLTF(`/models/closures/BB_SPR_COLLAR_${labFin}.glb`);
  const actuator = useGLTF(`/models/closures/BB_SPR_ACTUATOR_${labFin}.glb`);
  const overcap = useGLTF(`/models/closures/BB_SPR_OVERCAP_${labFin}.glb`);
  const spout = useGLTF(`/models/closures/BB_PMP_SPOUT_${labFin}.glb`);
  const [mats, setMats] = useState<Record<string, {
    color: string; roughness: number; metalness: number; clearcoat?: number;
  }> | null>(null);
  useEffect(() => {
    fetch("/models/materials.json").then(r => r.json())
      .then(j => setMats(j.materials)).catch(() => {});
  }, []);
  // metals mirror whatever surrounds them, and the room is deliberately
  // dark for the glass — so a chrome ball reads as a smoked-glass dome
  // (Jordan's close-up). Metals get their OWN bright environment, the way
  // a product shot gives jewellery its own bounce card.
  const plasticEnv = useEnvironment({ files: "/models/studio-browser.hdr" });
  // METALLIZED finishes use MeshMatcapMaterial (core three.js): a whole
  // studio baked into a mirrored-sphere image, generated by gen_matcaps.py
  // from OUR studio-metal.hdr - perfectly lit from every angle, in every
  // scene, at zero runtime cost. Plastics stay PBR under the soft tent.
  // real brushed/matte metal maps from the absorbed physicallybased library
  const pbrMaps = useTexture({
    brushNormal: "/models/pbr/brush/normal.png",
    brushRough: "/models/pbr/brush/roughness.png",
    matteNormal: "/models/pbr/matte/normal.png",
    matteRough: "/models/pbr/matte/roughness.png",
  });
  useEffect(() => {
    for (const t of Object.values(pbrMaps)) {
      t.colorSpace = THREE.NoColorSpace;
      t.wrapS = t.wrapT = THREE.RepeatWrapping;
      t.repeat.set(3, 1);
      t.needsUpdate = true;
    }
  }, [pbrMaps]);
  const matcaps = useTexture({
    // versioned filename: the matcap went through three layouts at one URL
    // and browser caches served the stale black-centred v1 ("still a
    // transparent dome") long after v3 shipped
    ballSteel: "/models/matcaps/ball-steel-v3.png",
    steel: "/models/matcaps/steel.png",
    gold: "/models/matcaps/gold.png",
    goldMatte: "/models/matcaps/gold-matte.png",
    silverMatte: "/models/matcaps/silver-matte.png",
    copperMatte: "/models/matcaps/copper-matte.png",
  });
  useEffect(() => {
    for (const t of Object.values(matcaps)) {
      t.colorSpace = THREE.SRGBColorSpace;
      t.needsUpdate = true;
    }
  }, [matcaps]);
  // matcap ONLY for the ball: spheres sample the whole baked studio, but a
  // straight cylinder wall varies its normal only horizontally and drags one
  // line of the matcap into full-height smears (Jordan's gold cap close-up).
  // Cylindrical caps are PBR metal under the rhythmic metal env instead —
  // which is exactly what Pacdora's chrome cap is.
  // THE UNIVERSAL REFLECTION STUDIO (Jordan): one real studio for every
  // reflective component, clean rather than busy - a 19mm cap cannot carry
  // clutter. Now Poly Haven studio_small_03 (CC0), the NEUTRAL classic
  // (drei's own "studio" preset): brown_photostudio_02 was warm and turned
  // mirror silver sepia ("the silver went wacky"). Mirrors have no colour
  // of their own - a neutral studio is what keeps silver silver.
  // metals bake three's RoomEnvironment — the threejs-materials library's
  // "Studio mode" (Jordan: the beautiful shiny gold/silver were graded
  // under it); broad area lights never stripe a cylinder
  const metalEnv = useMetalStudioHdri(metalStudioId);
  // matcap for the BALL only: a chrome sphere in a soft-gradient env is
  // indistinguishable from glass (mirrors show only their surroundings);
  // "steel" is a baked PATTERN - bright sky, crisp horizon, dark floor,
  // window glints - synthesized in ball-steel.png. Cylinders never matcap.
  // Matcaps are RETIRED: they were a workaround for the ball's inverted
  // normals (the real bug, fixed in the asset). Real PBR metal under the
  // universal studio is correct and consistent with every other component.
  // The baked matcaps stay in public/models/matcaps/ for future use.
  const MATCAP_FOR: Record<string, THREE.Texture> = {};
  const build = useCallback((gltf: { scene: THREE.Object3D }, matName: string,
                             tune?: MatOverride) => {
    const scene = gltf.scene.clone(true);
    const base = mats?.[matName];
    const m = base ? { ...base, ...(tune || {}) } : base;
    scene.traverse((o) => {
      const mesh = o as THREE.Mesh;
      if (!mesh.isMesh) return;
      const mc = MATCAP_FOR[matName];
      if (mc) {
        mesh.material = new THREE.MeshMatcapMaterial({ matcap: mc });
        return;
      }
      const aniso = (m as { anisotropy?: number } | undefined)?.anisotropy ?? 0;
      const mapSet = (m as { maps?: string } | undefined)?.maps;
      if ((aniso > 0 || mapSet) && !mesh.geometry.getAttribute("uv")) {
        // anisotropy needs a tangent frame; the geometry-only closure GLBs
        // carry no UVs, so generate a cylindrical unwrap on the fly
        const pos = mesh.geometry.getAttribute("position");
        const uv = new Float32Array(pos.count * 2);
        mesh.geometry.computeBoundingBox();
        const bb = mesh.geometry.boundingBox as THREE.Box3;
        const h = Math.max(1e-6, bb.max.y - bb.min.y);
        for (let i = 0; i < pos.count; i++) {
          uv[i * 2] = (Math.atan2(pos.getX(i), pos.getZ(i)) / (2 * Math.PI)) + 0.5;
          uv[i * 2 + 1] = (pos.getY(i) - bb.min.y) / h;
        }
        mesh.geometry.setAttribute("uv", new THREE.BufferAttribute(uv, 2));
      }
      const phys = m ? {
        color: new THREE.Color(m.color), roughness: m.roughness,
        metalness: m.metalness, clearcoat: m.clearcoat ?? 0,
        ior: (m as { ior?: number }).ior ?? 1.5,
        transmission: (m as { transmission?: number }).transmission ?? 0,
      } : { color: 0x888888, roughness: 0.4, metalness: 0.5,
            ior: 1.5, transmission: 0 };
      const mat = new THREE.MeshPhysicalMaterial(phys);
      // library reflectivity fields (specularIntensity scales dielectric F0)
      const spec = m as { specularIntensity?: number; specularColor?: string } | undefined;
      if (spec?.specularIntensity != null) mat.specularIntensity = spec.specularIntensity;
      if (spec?.specularColor) mat.specularColor = new THREE.Color(spec.specularColor);
      if (phys.transmission > 0) {           // translucent plastics
        mat.thickness = 0.002;
        mat.transparent = false;
      }
      // every closure part lights from the bright component env — the dark
      // glass room greys white phenolic and smokes chrome (both observed);
      // components get their own bounce light like any product shoot
      // metallized AND glossy surfaces mirror the rhythmic metal studio
      // (glossy black under a featureless env goes flat); matte plastics
      // light from the soft tent (the dark glass room greys them)
      if (aniso > 0) {
        mat.anisotropy = aniso;
        mat.anisotropyRotation = Math.PI / 2;   // flash runs along the cap axis
      }
      if (mapSet === "brush" || mapSet === "matte") {
        mat.normalMap = mapSet === "brush" ? pbrMaps.brushNormal : pbrMaps.matteNormal;
        mat.roughnessMap = mapSet === "brush" ? pbrMaps.brushRough : pbrMaps.matteRough;
        mat.roughness = 1.0;                     // the map IS the roughness
        mat.normalScale = new THREE.Vector2(0.6, 0.6);
      }
      const glossy = phys.metalness >= 0.85 || phys.roughness <= 0.3;
      const envChoice = (m as { env?: string } | undefined)?.env;
      mat.envMap = envChoice === "tent" ? plasticEnv
                 : envChoice === "metal" ? metalEnv
                 : glossy ? metalEnv : plasticEnv;
      const envOverride = (m as { envMapIntensity?: number } | undefined)?.envMapIntensity;
      mat.envMapIntensity = envOverride ?? (glossy ? 1.15 : 0.9);
      mesh.material = mat;
      // dev diagnostic: what did each closure part ACTUALLY get?
      if (typeof window !== "undefined") {
        const w = window as unknown as { __labParts?: Record<string, unknown> };
        w.__labParts = w.__labParts || {};
        w.__labParts[matName] = {
          mesh: mesh.name, type: mat.type,
          color: mat.color.getHexString(), rough: mat.roughness,
          metal: mat.metalness, envMap: !!mat.envMap,
          envInt: mat.envMapIntensity, transmission: mat.transmission,
          side: mat.side, visible: mesh.visible,
        };
      }
    });
    return scene;
  }, [mats, plasticEnv, metalEnv, matcaps, pbrMaps]);
  const parts = useMemo(() => {
    if (mode === "none" || !mats) return null;
    const g: { scene: THREE.Object3D }[] = [];
    if (mode === "capped") {
      // 18-415 capped-bottle inspection: leather mats force their
      // moulding; CAP_WHITE ships tall-only at this finish
      const capGltf = capFinish !== "18-415" ? cap
                    : capMat.startsWith("LEATHER_") ? cap18Leather
                    : (capMat === "CAP_WHITE" || capMat.endsWith("_TALL_VIEW"))
                    ? cap18Tall : cap18;
      g.push({ scene: build(capGltf, capMat.replace("_TALL_VIEW", ""), capTune) });
      return g;
    }
    if (mode === "roller" || mode === "rollerCapped") {
      g.push({ scene: build(housing, "PART_HOUSING_PP_NATURAL") });
      g.push({ scene: build(ball, ballMat) });
      if (mode === "rollerCapped") {
        // *Dot caps: shell in the colourway + BB_CAP_DOTS studs in chrome
        g.push({ scene: build(cap, capMat, capTune) });
        if (capMat.startsWith("CAP_DOTS"))
          g.push({ scene: build(capDots, capMat === "CAP_DOTS_SILVER"
                        ? "PART_STUD_CHROME_BRIGHT" : "PART_STUD_CHROME") });
      }
    } else {
      // the trim tune rides capTune so the same sliders serve sprays too
      g.push({ scene: build(collar, trimMat, capTune) });
      g.push({ scene: build(actuator, "PART_ACTUATOR_PP") });   // always white
      if (mode === "pump" || mode === "pumpCapped")
        g.push({ scene: build(spout, "PART_ACTUATOR_PP") });
      if (mode === "sprayerCapped" || mode === "pumpCapped")
        g.push({ scene: build(overcap, "PART_OVERCAP_CLEAR") });
    }
    return g;
  }, [mode, mats, build, housing, ball, cap, cap18, cap18Tall, cap18Leather,
      capDots, collar, actuator, overcap, spout,
      capMat, ballMat, capTune, trimMat]);
  if (!parts) return null;
  return (
    <group position={[0, neckY, 0]}>
      {parts.map((p, i) => <primitive key={i} object={p.scene} />)}
    </group>
  );
}

function Model({
  url, preset, envIntensity, transmissionMat, caustics, causticIntensity,
  thicknessUrl, bakeMax, frostUrl, closure, capMat, ballMat, capTune, trimMat,
  metalTune, metalStudioId, capFinish, onMeasure,
}: {
  url: string; preset: GlassPreset; envIntensity: number;
  transmissionMat: boolean; caustics: boolean; causticIntensity: number;
  /** baked per-texel thickness (Blender lane). null = identity 1x1 white,
   *  which multiplies the scalar by 1 — a no-op that keeps hook order stable. */
  thicknessUrl: string | null; bakeMax: number | null;
  /** baked frost mask, or null for a uniformly finished colourway */
  frostUrl: string | null;
  closure: LabClosure;
  capMat: string; ballMat: string; trimMat: string; capTune: MatOverride;
  metalTune?: Partial<MetalStudioParams>;
  metalStudioId?: MetalStudioId;
  capFinish?: "17-415" | "18-415";
  onMeasure: (m: Measured) => void;
}) {
  const gltf = useGLTF(url);
  const thicknessTex = useTexture(
    thicknessUrl ?? "/models/bodies-thickness/white-1x1.png");
  // frost mask: white = etched body, black = clear finish. Fed as a
  // roughnessMap so one mesh carries both surfaces, the way a real
  // acid-etched bottle does.
  const frostTex = useTexture(
    frostUrl ?? "/models/bodies-thickness/white-1x1.png");
  useEffect(() => {
    frostTex.flipY = false;
    frostTex.colorSpace = THREE.NoColorSpace;
    frostTex.needsUpdate = true;
  }, [frostTex]);
  useEffect(() => {
    // glTF-convention UVs + linear data, not colour
    thicknessTex.flipY = false;
    thicknessTex.colorSpace = THREE.NoColorSpace;
    thicknessTex.needsUpdate = true;
  }, [thicknessTex]);
  // when the bake is live, the thickness slider sets the map's CEILING and
  // each texel scales down from it — the slider stays the tuning dial instead
  // of the sidecar hardcoding the look. (The sidecar's maxThicknessM is the
  // metric ceiling: at slider = maxThicknessM the map is metrically exact.)
  const effThickness = preset.thickness;
  const effBackside = bakeMax != null ? preset.thickness : preset.thickness * 2.6;
  const scene = useMemo(() => gltf.scene.clone(true), [gltf.scene]);
  const materialsInFile: number =
    (gltf as unknown as { parser?: { json?: { materials?: unknown[] } } })
      .parser?.json?.materials?.length ?? 0;

  // Pull the glass mesh OUT of the cloned scene so its material can be a JSX
  // child. drei's MeshTransmissionMaterial is a component, not a constructor -
  // and it is the reason /lab/bottle-3d reads as glass while a plain
  // MeshPhysicalMaterial does not: it renders the BACKSIDE through the front
  // wall and multi-samples the transmission.
  const glass = useMemo(() => {
    let g: THREE.Mesh | null = null;
    scene.traverse((o) => {
      const m = o as THREE.Mesh;
      if (m.isMesh && roleOf(m.name) === "bottle_glass" && !g) g = m;
    });
    if (g) (g as THREE.Mesh).visible = false;
    return g as THREE.Mesh | null;
  }, [scene]);

  useEffect(() => {
    let verts = 0, tris = 0;
    const meshes: string[] = [];
    scene.traverse((o) => {
      const m = o as THREE.Mesh;
      if (!m.isMesh) return;
      meshes.push(m.name);
      const pos = m.geometry.getAttribute("position");
      verts += pos ? pos.count : 0;
      const idx = m.geometry.getIndex();
      tris += idx ? idx.count / 3 : (pos ? pos.count / 3 : 0);
    });
    if (!glass) return;
    glass.geometry.computeBoundingBox();
    const size = new THREE.Vector3();
    (glass.geometry.boundingBox as THREE.Box3).getSize(size);
    const hMm = size.y * 1000;
    onMeasure({
      wMm: size.x * 1000, hMm, dMm: size.z * 1000,
      verts, tris: Math.round(tris), meshes, materialsInFile,
      unit: "metres (1 world unit = 1 m)",
      scaleWarning:
        hMm > 400 ? `height ${hMm.toFixed(0)} — exported in MILLIMETRES?`
        : hMm < 5 ? `height ${hMm.toFixed(2)} mm — exported too small?`
        : null,
    });
  }, [scene, glass, onMeasure, materialsInFile]);

  // the fallback path, for A/B against the better material
  useEffect(() => {
    if (!glass || (transmissionMat && !preset.thinWall)) return;
    glass.visible = true;
    const m = applyGlassPreset(glass, { ...preset, envMapIntensity: envIntensity });
    if (bakeMax != null) {
      m.thicknessMap = thicknessTex;
      m.needsUpdate = true;
    }
    if (frostUrl) {
      m.roughnessMap = frostTex;
      m.needsUpdate = true;
    }
    return () => { glass.visible = false; };
  }, [glass, preset, envIntensity, transmissionMat, bakeMax, thicknessTex, frostUrl, frostTex]);

  // rim datum from the GLB's own empty — the manifest contract
  const neckY = useMemo(() => {
    let y = 0;
    scene.traverse((o) => { if (o.name === "BB_ATTACH_NECK") y = o.position.y; });
    return y;
  }, [scene]);

  return (
    <group>
      <primitive object={scene} />
      <Closure mode={closure} neckY={neckY} capMat={capMat} ballMat={ballMat}
               capTune={capTune} trimMat={trimMat} metalTune={metalTune}
               metalStudioId={metalStudioId} capFinish={capFinish} />
      {glass && transmissionMat && !preset.thinWall && caustics ? (
        <Caustics
          // The closest real-time approximation of light focused THROUGH the
          // glass onto the surface below. Not path-traced caustics - it renders
          // the object from the light's point of view and projects the result -
          // but it is the single strongest "this is really glass" cue available,
          // because a bottle that casts a flat grey shadow reads as plastic.
          color={preset.attenuationColor}
          ior={preset.ior}
          backsideIOR={preset.ior * 0.72}
          worldRadius={0.006}
          intensity={causticIntensity}
          backside
          causticsOnly={false}
          resolution={1024}
          lightSource={[-0.6, 1.2, 0.8]}
        >
        <mesh geometry={glass.geometry} position={glass.position}
              rotation={glass.rotation} scale={glass.scale}>
          <MeshTransmissionMaterial
            transmission={preset.transmission}
            thickness={effThickness}
            thicknessMap={thicknessTex}
            roughnessMap={frostUrl ? frostTex : null}
            backside={!preset.thinWall}
            backsideThickness={effBackside}
            samples={16}
            resolution={1024}
            backsideResolution={512}
            roughness={preset.roughness}
            ior={preset.ior}
            chromaticAberration={preset.dispersion * 0.055}
            clearcoat={preset.clearcoat} clearcoatRoughness={preset.clearcoatRoughness}
            anisotropicBlur={preset.anisotropicBlur}
            distortion={preset.distortion}
            distortionScale={0.5}
            temporalDistortion={0}
            attenuationDistance={preset.attenuationDistance}
            attenuationColor={preset.attenuationColor}
            color="#ffffff"
            envMapIntensity={envIntensity}
          />
        </mesh>
        </Caustics>
      ) : glass && transmissionMat && !preset.thinWall ? (
        <mesh geometry={glass.geometry} position={glass.position}
              rotation={glass.rotation} scale={glass.scale}>
          <MeshTransmissionMaterial
            transmission={preset.transmission} thickness={effThickness}
            thicknessMap={thicknessTex}
            roughnessMap={frostUrl ? frostTex : null}
            backside={!preset.thinWall} backsideThickness={effBackside}
            samples={16} resolution={1024} backsideResolution={512}
            roughness={preset.roughness} ior={preset.ior}
            chromaticAberration={preset.dispersion * 0.055}
            clearcoat={preset.clearcoat} clearcoatRoughness={preset.clearcoatRoughness}
            anisotropicBlur={preset.anisotropicBlur}
            distortion={preset.distortion}
            distortionScale={0.5}
            temporalDistortion={0}
            attenuationDistance={preset.attenuationDistance}
            attenuationColor={preset.attenuationColor}
            color="#ffffff" envMapIntensity={envIntensity}
          />
        </mesh>
      ) : null}
    </group>
  );
}

/* ------------------------------------------------------------- environment */

/** Cyclorama sweep: floor -> quarter fillet -> back wall, one smooth surface.
 *  Module-level because it never changes; sized generously for a 0.22 m camera. */
const CYC_GEOMETRY = (() => {
  const FRONT = 0.9, BACK = -0.35, FILLET = 0.16, WALL_H = 1.4, W = 3.0, ARC = 24;
  const profile: [number, number][] = [[FRONT, 0]];
  for (let i = 0; i <= ARC; i++) {
    const a = (i / ARC) * (Math.PI / 2);
    profile.push([BACK + FILLET - Math.sin(a) * FILLET,
                  FILLET - Math.cos(a) * FILLET]);
  }
  profile.push([BACK, WALL_H]);
  const pos: number[] = [], idx: number[] = [];
  profile.forEach(([z, y]) => { pos.push(-W / 2, y, z, W / 2, y, z); });
  for (let i = 0; i < profile.length - 1; i++) {
    const a = i * 2, b = a + 1, c = a + 2, d = a + 3;
    idx.push(a, b, c, b, d, c);
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.Float32BufferAttribute(pos, 3));
  g.setIndex(idx);
  g.computeVertexNormals();
  return g;
})();

/** Hex text entry that types freely and commits only valid #rrggbb. Exists
 *  because the native color-dialog popup cannot open inside the embedded
 *  preview pane — typing (and the swatches) must always work. */
function HexField({ value, onValid }: { value: string; onValid: (v: string) => void }) {
  const [draft, setDraft] = useState(value);
  useEffect(() => { setDraft(value); }, [value]);
  return (
    <input value={draft} spellCheck={false}
           onChange={(e) => {
             const t = e.target.value.trim();
             setDraft(t);
             const v = /^[0-9a-fA-F]{6}$/.test(t) ? "#" + t : t;
             if (/^#[0-9a-fA-F]{6}$/.test(v)) onValid(v.toLowerCase());
           }}
           style={{ width: 70, height: 22, background: "#101014",
                    color: "#e8e8ea", border: "1px solid #33333c",
                    fontSize: 11, fontFamily: "inherit", padding: "0 5px" }} />
  );
}

function StudioEnv({ studioId, intensity, rotationDeg }:
                   { studioId: StudioPresetId; intensity: number; rotationDeg: number }) {
  const { scene } = useThree();
  const preset = STUDIO_PRESETS[studioId];
  useEffect(() => {
    scene.environmentIntensity = intensity;
    scene.environmentRotation = new THREE.Euler(0, (rotationDeg * Math.PI) / 180, 0);
  }, [scene, intensity, rotationDeg]);

  // hybrid = HDRI + Lightformers baked into ONE cubemap (the candidate
  // single-environment architecture) — same component the scene shell mounts
  if (preset.managedEnv) return <StudioEnvironment />;
  if (preset.hdri) return <Environment files={preset.hdri} />;

  // legacy in-scene rig, kept only for A/B. Its narrow hot rim pair is what
  // paints hard vertical stripes down a cylinder.
  return (
    <Environment resolution={1024}>
      <Lightformer form="rect" intensity={10} color="#ffffff"
                   position={[0, 1.6, 0.9]} rotation={[-Math.PI / 3, 0, 0]}
                   scale={[3.5, 2.6, 1]} />
      <Lightformer form="rect" intensity={3.2} color="#eef2f6"
                   position={[-1.9, 0.5, 0.5]} rotation={[0, Math.PI / 2.4, 0]}
                   scale={[2.2, 3.2, 1]} />
      <Lightformer form="rect" intensity={2.4} color="#f6f2ee"
                   position={[1.9, 0.4, 0.4]} rotation={[0, -Math.PI / 2.4, 0]}
                   scale={[2.0, 3.0, 1]} />
      <Lightformer form="rect" intensity={22} color="#ffffff"
                   position={[-1.1, 0.7, -1.5]} rotation={[0, Math.PI / 4, 0]}
                   scale={[0.35, 3.0, 1]} />
      <Lightformer form="rect" intensity={18} color="#ffffff"
                   position={[1.1, 0.7, -1.5]} rotation={[0, -Math.PI / 4, 0]}
                   scale={[0.35, 3.0, 1]} />
      <Lightformer form="rect" intensity={1.6} color="#ffffff"
                   position={[0, -1.4, 0.2]} rotation={[Math.PI / 2, 0, 0]}
                   scale={[4, 4, 1]} />
      <Lightformer form="ring" intensity={1.2} color="#ffffff"
                   position={[0, 2.4, -0.6]} scale={[4, 4, 1]} />
    </Environment>
  );
}

/* ------------------------------------------------------------------ camera */

const CAM_PRESETS = {
  front: { azimuth: 0, elevation: 4 },
  threeQuarter: { azimuth: 35, elevation: 12 },
  side: { azimuth: 90, elevation: 4 },
} as const;
type CamPresetId = keyof typeof CAM_PRESETS;

function Rig({ azimuth, elevation, distance, targetY, fov, nonce }: {
  azimuth: number; elevation: number; distance: number; targetY: number;
  fov: number; nonce: number;
}) {
  const { camera } = useThree();
  useEffect(() => {
    const cam = camera as THREE.PerspectiveCamera;
    if (cam.isPerspectiveCamera && cam.fov !== fov) {
      cam.fov = fov; cam.updateProjectionMatrix();
    }
    const a = (azimuth * Math.PI) / 180, e = (elevation * Math.PI) / 180;
    cam.position.set(
      distance * Math.cos(e) * Math.sin(a),
      targetY + distance * Math.sin(e),
      distance * Math.cos(e) * Math.cos(a),
    );
    cam.lookAt(0, targetY, 0);
  }, [camera, azimuth, elevation, distance, targetY, fov, nonce]);
  return null;
}

/* ---------------------------------------------------------------- controls */

function Slider({ label, value, min, max, step, onChange, hint }: {
  label: string; value: number; min: number; max: number; step: number;
  onChange: (v: number) => void; hint?: string;
}) {
  return (
    <label style={{ display: "block", marginBottom: 9 }}>
      <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11 }}>
        <span style={{ color: "#b9b9c4" }}>{label}</span>
        <span style={{ color: "#f0f0f4" }}>{value.toFixed(step < 0.001 ? 5 : 3)}</span>
      </div>
      <input type="range" min={min} max={max} step={step} value={value}
             onChange={(e) => onChange(parseFloat(e.target.value))}
             style={{ width: "100%", accentColor: "#6a6af0" }} />
      {hint ? <div style={{ fontSize: 10, color: "#6f6f7d", marginTop: -2 }}>{hint}</div> : null}
    </label>
  );
}

const btn = (on: boolean): React.CSSProperties => ({
  padding: "4px 9px", fontSize: 11, borderRadius: 4, cursor: "pointer",
  border: "1px solid " + (on ? "#6a6af0" : "#33333c"),
  background: on ? "#23234a" : "#1a1a20", color: "#e8e8ea",
});

/* -------------------------------------------------------------------- page */

export default function MaterialLab(
  { bodies, threadedIds = [] }: { bodies: Body[]; threadedIds?: string[] },
) {
  const [bodyIdx, setBodyIdx] = useState(() =>
    Math.max(0, bodies.findIndex((b) => b.bodyId.startsWith("Cyl-round-17-415"))));
  const [presetId, setPresetId] = useState<GlassPresetId>("amber");
  const [working, setWorking] = useState<GlassPreset>(GLASS_PRESETS.amber);
  const [m, setM] = useState<Measured | null>(null);
  const [envIntensity, setEnvIntensity] = useState(1.0);
  const [envRot, setEnvRot] = useState(0);
  const [exposure, setExposure] = useState(1.05);
  const [cam, setCam] = useState<CamPresetId>("threeQuarter");
  const [distance, setDistance] = useState(0.22);
  const [fov, setFov] = useState(30);
  const [copied, setCopied] = useState(false);
  // Glass TRANSMITS the background. A dark viewport makes even a correct amber
  // render near-black - the values are fine, there is simply nothing behind the
  // bottle to see through it. /lab/bottle-3d gets this right with a light
  // studio backdrop, which is why the same values look rich there.
  const [studioId, setStudioId] = useState<StudioPresetId>(APPROVED_STUDIO);
  const [bg, setBg] = useState(STUDIO_PRESETS[APPROVED_STUDIO].backdrop);
  // MeshTransmissionMaterial renders the BACKSIDE through the front wall and
  // multi-samples; MeshPhysicalMaterial does a single flat backdrop lookup.
  // The difference is most of what separates "glass" from "tinted plastic".
  const [transmissionMat, setTransmissionMat] = useState(true);
  const [caustics, setCaustics] = useState(true);
  const [causticIntensity, setCausticIntensity] = useState(0.04);
  const [ground, setGround] = useState(true);
  // Default ON: the plain bodies/ build has a FLAT neck (0.00 mm relief).
  // Only bodies-threaded/ carries the drawing-exact helix, and glass
  // magnifies the neck - a flat one is immediately obvious.
  const [threaded, setThreaded] = useState(true);
  // interior content: Pacdora's lesson — clear glass needs something of its
  // own to refract. Also the first live configurator joint.
  const [closure, setClosure] = useState<LabClosure>("roller");
  const [trimMat, setTrimMat] = useState("CAP_SHINY_BLACK");
  const [capMat, setCapMat] = useState("CAP_SHINY_BLACK");
  const [ballMat, setBallMat] = useState("PART_BALL_STEEL");
  // live overrides for the SELECTED cap finish — Jordan tunes caps the same
  // way he tunes glass, then Copy hands back JSON for materials.json
  const [capTune, setCapTune] = useState<MatOverride>(null);
  // the metal STUDIO on sliders — Jordan dials the shine itself, then the
  // landed values get written into METAL_STUDIO_DEFAULTS and locked
  const [metalTune, setMetalTune] = useState<MetalStudioParams>(METAL_STUDIO_DEFAULTS);
  const [metalStudioId, setMetalStudioId] = useState<MetalStudioId>(APPROVED_METAL_STUDIO);
  useEffect(() => { setCapTune(null); }, [capMat]);
  // Reference comparison. The photo is held LOCALLY (object URL) — nothing is
  // uploaded. Framing does not need to match: scale/offset/opacity exist so a
  // hand-held shot can still be lined up for judging.
  const [refUrl, setRefUrl] = useState<string | null>(null);
  const [refMode, setRefMode] = useState<"off" | "side" | "overlay">("off");
  const [refOpacity, setRefOpacity] = useState(0.5);
  const [refScale, setRefScale] = useState(1);
  const [refX, setRefX] = useState(0);
  const [refY, setRefY] = useState(0);

  // Baked per-texel thickness (Pacdora's biggest trick, produced by the
  // Blender lane: bake_thickness.py). Availability is per body — probe the
  // sidecar. The baked GLB is the SAME threaded geometry plus UVs.
  const [bakedMap, setBakedMap] = useState(true);
  const [bakeMax, setBakeMax] = useState<number | null>(null);

  const body = bodies[bodyIdx];
  const hasThreaded = threadedIds.includes(body.bodyId);

  useEffect(() => {
    let dead = false;
    setBakeMax(null);
    fetch(`/models/bodies-thickness/${body.bodyId}.thickness.json`)
      .then((r) => (r.ok ? r.json() : null))
      .then((j) => {
        if (!dead && j && typeof j.maxThicknessM === "number")
          setBakeMax(j.maxThicknessM);
      })
      .catch(() => {});
    return () => { dead = true; };
  }, [body.bodyId]);

  // the UV'd GLB serves BOTH maps; a preset may want the frost mask (UVs)
  // without consuming the thickness map (thinWall frosted does exactly that)
  const uvModel = bakedMap && bakeMax != null;
  const bakeLive = uvModel && working.thicknessBake !== false;
  const modelUrl = uvModel
    ? `/models/bodies-thickness/${body.bodyId}.glb`
    : threaded && hasThreaded
      ? `/models/bodies-threaded/${body.bodyId}.glb`
      : body.url;
  const onMeasure = useCallback((x: Measured) => setM(x), []);

  const loadPreset = (id: GlassPresetId) => {
    setPresetId(id); setWorking({ ...GLASS_PRESETS[id] });
    // each colourway carries its own studio angle so the finishes do not all
    // catch the light in the same place (Jordan, 2026-08-31)
    setEnvRot(GLASS_PRESETS[id].envRotationDeg);
  };
  const set = <K extends keyof GlassPreset>(k: K, v: GlassPreset[K]) =>
    setWorking((p) => ({ ...p, [k]: v }));

  const dirty = useMemo(() => {
    const base = GLASS_PRESETS[presetId];
    return (Object.keys(base) as (keyof GlassPreset)[])
      .some((k) => k !== "provenance" && base[k] !== working[k]);
  }, [presetId, working]);

  const copyJson = async () => {
    const { provenance, ...values } = working;
    await navigator.clipboard.writeText(JSON.stringify(
      { ...values, provenance: dirty ? "TUNED IN MATERIAL LAB — re-solve before shipping" : provenance },
      null, 2));
    setCopied(true); setTimeout(() => setCopied(false), 1400);
  };

  const onPickRef = (f: File | null) => {
    if (refUrl) URL.revokeObjectURL(refUrl);
    if (!f) { setRefUrl(null); setRefMode("off"); return; }
    setRefUrl(URL.createObjectURL(f));
    setRefMode("side");
  };
  useEffect(() => () => { if (refUrl) URL.revokeObjectURL(refUrl); }, [refUrl]);

  const targetY = m ? (m.hMm / 1000) / 2 : 0.035;
  const { azimuth, elevation } = CAM_PRESETS[cam];
  // OrbitControls drift persists until something re-seizes the camera —
  // bumping the nonce re-runs the Rig placement (Jordan: "the orbital
  // adjustment needs to be reset")
  const [viewNonce, setViewNonce] = useState(0);
  const controlsRef = useRef<{ target: THREE.Vector3; update: () => void } | null>(null);
  const resetView = () => {
    const c = controlsRef.current;
    if (c) { c.target.set(0, targetY, 0); c.update(); }
    setViewNonce((n) => n + 1);
  };

  return (
    <div style={{ display: "flex", height: "100vh", background: "#101014", color: "#e8e8ea",
                  fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 12 }}>
      {refUrl && refMode === "side" ? (
        <div style={{ flex: 1, position: "relative", background: "#0c0c10",
                      borderRight: "1px solid #26262c", overflow: "hidden" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src={refUrl} alt="reference"
               style={{ position: "absolute", inset: 0, margin: "auto",
                        maxWidth: "100%", maxHeight: "100%", objectFit: "contain",
                        transform: `translate(${refX}px, ${refY}px) scale(${refScale})` }} />
          <div style={{ position: "absolute", bottom: 8, left: 10, fontSize: 10,
                        color: "#7d7d88" }}>REFERENCE PHOTOGRAPH</div>
        </div>
      ) : null}

      <main style={{ flex: 1, position: "relative" }}>
        <Canvas dpr={[1, 2]} shadows={false}
                camera={{ position: [0.12, 0.05, 0.18], fov }}
                gl={{ antialias: true, toneMapping: THREE.ACESFilmicToneMapping,
                      toneMappingExposure: exposure }}
                onCreated={(state) => {
                  if (process.env.NODE_ENV !== "production")
                    (window as unknown as Record<string, unknown>).__lab = state;
                }}>
          {/* the OFF-FRAME ROOM: only rays that refract past the sweep's
              edges ever see this — the camera never does, the sweep covers
              the frame. Strongly-bent rays (heel, rim, silhouette) land
              here, and its darkness is what draws the grey edge bands every
              real clear bottle shows. Bright, it was the milkiness: bent
              rays clamped to bone. */}
          <color attach="background"
                 args={[new THREE.Color(bg).multiplyScalar(0.32)]} />
          <Suspense fallback={null}>
            {/* disableY: the GLB contract puts the base at y=0 and the rig
                targets h/2 above origin. Vertical centering re-centred the
                WHOLE assembly when the closure mounted, sinking the bottle
                foot through the floor. */}
            <Center key={modelUrl} disableY>
              <Model url={modelUrl} preset={working} envIntensity={envIntensity}
                     thicknessUrl={bakeLive
                       ? `/models/bodies-thickness/${body.bodyId}.thickness.png`
                       : null}
                     bakeMax={bakeLive ? bakeMax : null}
                     closure={closure} capMat={capMat} ballMat={ballMat}
                     capTune={capTune} trimMat={trimMat} metalTune={metalTune}
                     metalStudioId={metalStudioId}
                     capFinish={(body.bodyId.includes("18-415") ? "18-415" : "17-415")}
                     frostUrl={uvModel && working.frostMask
                       ? `/models/bodies-thickness/${body.bodyId}.frost.png`
                       : null}
                    transmissionMat={transmissionMat}
                    caustics={caustics} causticIntensity={causticIntensity}
                     onMeasure={onMeasure} />
            </Center>
            {ground && m ? (
              <group position={[0, 0, 0]}>
                {/* caustics need a surface to land on, and a floating bottle
                    reads as a cut-out no matter how good the glass is */}
                {/* seamless cyclorama: floor sweeps up into the back wall
                    through a fillet, so no horizon line ever cuts through the
                    glass. Profile runs front->back->up; swept across x. */}
                <mesh position={[0, -0.0002, 0]} geometry={CYC_GEOMETRY}>
                  {/* a real sweep is never one flat tone, and CLEAR glass is
                      invisible without something to bend: the vertical
                      gradient is what its refraction actually shows */}
                  <meshStandardMaterial color={bg} roughness={0.85} metalness={0}
                                        side={THREE.DoubleSide}
                                        onBeforeCompile={(sh) => {
                                          sh.vertexShader = sh.vertexShader.replace(
                                            "#include <common>",
                                            "#include <common>\nvarying float vSweepY;\nvarying float vSweepX;");
                                          sh.vertexShader = sh.vertexShader.replace(
                                            "#include <begin_vertex>",
                                            "#include <begin_vertex>\nvSweepY = position.y;\nvSweepX = position.x;");
                                          sh.fragmentShader = sh.fragmentShader.replace(
                                            "#include <common>",
                                            "#include <common>\nvarying float vSweepY;\nvarying float vSweepX;");
                                          sh.fragmentShader = sh.fragmentShader.replace(
                                            "#include <dithering_fragment>",
                                            "#include <dithering_fragment>\n" +
                                            "float g = smoothstep(-0.05, 1.05, vSweepY);\n" +
                                            "gl_FragColor.rgb *= mix(0.97, 0.80, g);\n" +
                                            // off-axis falloff: invisible behind the
                                            // bottle, but the silhouette's edge lens
                                            // compresses it into the dark bands real
                                            // clear glass shows
                                            "float ox = smoothstep(0.14, 0.90, abs(vSweepX));\n" +
                                            "gl_FragColor.rgb *= 1.0 - 0.30 * ox;\n" +
                                            // soft light pool behind the product:
                                            // a dark sweep with no pool reads as a
                                            // flat card, not a lit studio
                                            "float pool = exp(-pow(vSweepX / 0.30, 2.0)) *\n" +
                                            "             exp(-pow((vSweepY - 0.13) / 0.26, 2.0));\n" +
                                            "gl_FragColor.rgb *= 1.0 + 0.26 * pool;");
                                        }} />
                </mesh>
                <ContactShadows opacity={0.42} scale={0.35} blur={2.4}
                                far={0.06} resolution={1024} color="#3a3128" />
              </group>
            ) : null}
            <StudioEnv studioId={studioId} intensity={envIntensity} rotationDeg={envRot} />
          </Suspense>
          <Rig nonce={viewNonce}
               azimuth={azimuth} elevation={elevation} distance={distance}
               targetY={0} fov={fov} />
          <OrbitControls makeDefault target={[0, targetY, 0]}
                         // eslint-disable-next-line @typescript-eslint/no-explicit-any
                         ref={controlsRef as any}
                         minDistance={0.05} maxDistance={1} />
        </Canvas>

        {refUrl && refMode === "overlay" ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img src={refUrl} alt="reference overlay"
               style={{ position: "absolute", inset: 0, margin: "auto",
                        maxWidth: "100%", maxHeight: "100%", objectFit: "contain",
                        opacity: refOpacity, pointerEvents: "none",
                        transform: `translate(${refX}px, ${refY}px) scale(${refScale})` }} />
        ) : null}

        {m ? (
          <div style={{ position: "absolute", top: 12, left: 12, padding: "9px 11px",
                        background: "rgba(16,16,20,.88)", border: "1px solid #26262c",
                        borderRadius: 6, lineHeight: 1.55, minWidth: 250 }}>
            <div style={{ fontWeight: 600, marginBottom: 3 }}>{body.bodyId}</div>
            <Row k="height" v={`${m.hMm.toFixed(1)} mm`} />
            <Row k="width × depth" v={`${m.wMm.toFixed(1)} × ${m.dMm.toFixed(1)} mm`} />
            <Row k="world units" v={m.unit} />
            <Row k="materials in file" v={`${m.materialsInFile}`} good={m.materialsInFile === 0} />
            <Row k="verts / tris" v={`${m.verts.toLocaleString()} / ${m.tris.toLocaleString()}`} />
            <Row k="neck" v={threaded && hasThreaded
                   ? "threaded — drawing-exact helix"
                   : hasThreaded ? "PLAIN (flat neck)" : "no threaded build"}
                 good={threaded && hasThreaded} />
            {m.scaleWarning ? <Row k="⚠ scale" v={m.scaleWarning} good={false} /> : null}
          </div>
        ) : null}
      </main>

      <aside style={{ width: 306, padding: 14, overflowY: "auto",
                      borderLeft: "1px solid #26262c" }}>
        <div style={{ fontSize: 13, fontWeight: 600 }}>Material Lab</div>
        <div style={{ color: "#7d7d88", marginBottom: 13 }}>
          glass tuned in the renderer that ships
        </div>

        <Section title="PRESET" />
        <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 6 }}>
          {(Object.keys(GLASS_PRESETS) as GlassPresetId[]).map((id) => (
            <button key={id} onClick={() => loadPreset(id)} style={btn(presetId === id)}>
              {GLASS_PRESETS[id].label}
            </button>
          ))}
        </div>
        <div style={{ fontSize: 10, color: dirty ? "#e8b44a" : "#5fd68a", marginBottom: 12 }}>
          {dirty ? "● working copy — differs from the approved preset" : "○ matches approved preset"}
        </div>

        <Section title="MATERIAL" />
        <Slider label="transmission" value={working.transmission} min={0} max={1} step={0.01}
                onChange={(v) => set("transmission", v)} />
        <Slider label="roughness" value={working.roughness} min={0} max={1} step={0.01}
                onChange={(v) => set("roughness", v)}
                hint="0 = polished · 0.5+ = etched/frosted" />
        <Slider label="distortion" value={working.distortion} min={0} max={0.5} step={0.01}
                onChange={(v) => set("distortion", v)}
                hint="static wall waviness — the refraction swims like real glass" />
        <Slider label="anisotropicBlur" value={working.anisotropicBlur}
                min={0} max={0.8} step={0.01}
                onChange={(v) => set("anisotropicBlur", v)}
                hint="smear of the TRANSMITTED image — high = opaque plastic" />
        <Slider label="ior" value={working.ior} min={1.3} max={1.8} step={0.01}
                onChange={(v) => set("ior", v)} hint="soda-lime glass = 1.52" />
        <Slider label="thickness (m)" value={working.thickness} min={0} max={0.05} step={0.0005}
                onChange={(v) => set("thickness", v)}
                hint="a SCALAR stand-in for optical path — not the real wall" />
        <Slider label="attenuationDistance (m)" value={working.attenuationDistance}
                min={0.001} max={0.5} step={0.001}
                onChange={(v) => set("attenuationDistance", v)}
                hint="pair with thickness — together these ARE the depth" />
        <label style={{ display: "flex", justifyContent: "space-between",
                        alignItems: "center", margin: "2px 0 4px" }}>
          <span style={{ color: "#b9b9c4", fontSize: 11 }}>attenuationColor</span>
          <span style={{ display: "flex", gap: 6, alignItems: "center" }}>
            <HexField value={working.attenuationColor}
                      onValid={(v) => set("attenuationColor", v)} />
            <input type="color" value={working.attenuationColor}
                   onChange={(e) => set("attenuationColor", e.target.value)}
                   style={{ width: 34, height: 22, background: "none", border: "1px solid #33333c" }} />
          </span>
        </label>
        <div style={{ display: "flex", gap: 4, marginBottom: 10, flexWrap: "wrap" }}>
          {[["amber", "#a8571a"], ["amber pale", "#c88e63"], ["amber deep", "#7a3c10"],
            ["cobalt", "#123f9e"], ["clear", "#eef6f2"], ["frost", "#f4f6f5"],
            ["swirl", "#e2d8c6"]].map(([n, c]) => (
            <button key={n} onClick={() => set("attenuationColor", c)}
                    title={c}
                    style={{ width: 22, height: 18, background: c, cursor: "pointer",
                             border: working.attenuationColor === c
                               ? "2px solid #8a8af0" : "1px solid #33333c",
                             borderRadius: 3 }} />
          ))}
        </div>
        <Slider label="dispersion" value={working.dispersion} min={0} max={4} step={0.05}
                onChange={(v) => set("dispersion", v)}
                hint="prismatic edge split — the anti-plastic cue" />
        <Slider label="clearcoat" value={working.clearcoat} min={0} max={1} step={0.05}
                onChange={(v) => set("clearcoat", v)}
                hint="the wet second highlight — Pacdora runs this high, dispersion 0" />
        <Slider label="clearcoatRoughness" value={working.clearcoatRoughness} min={0} max={0.5} step={0.01}
                onChange={(v) => set("clearcoatRoughness", v)}
                hint="~0.05 polished · higher softens the coat only" />

        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        margin: "2px 0 4px", cursor: "pointer" }}>
          <input type="checkbox" checked={transmissionMat}
                 onChange={(e) => setTransmissionMat(e.target.checked)} />
          <span>MeshTransmissionMaterial</span>
        </label>
        <div style={{ display: "flex", gap: 4, alignItems: "center", margin: "2px 0 8px" }}>
          <span style={{ color: "#b9b9c4", fontSize: 11, marginRight: 4 }}>closure</span>
          {(["none", "capped", "roller", "rollerCapped", "sprayer", "sprayerCapped",
             "pump", "pumpCapped"] as const)
            // 18-415 has NO roll-ons (Jordan; catalog agrees: zero groups)
            .filter((m) => !(body.bodyId.includes("18-415") && m.startsWith("roller")))
            .map((m) => (
            <button key={m} onClick={() => setClosure(m)} style={btn(closure === m)}>
              {m === "capped" ? "cap 18"
               : m === "rollerCapped" ? "roller+cap"
               : m === "sprayerCapped" ? "spray+cap"
               : m === "pumpCapped" ? "pump+cap" : m}
            </button>
          ))}
        </div>
        {closure.startsWith("spray") || closure.startsWith("pump") ? (
          <div style={{ display: "flex", gap: 4, alignItems: "center",
                        margin: "0 0 6px", flexWrap: "wrap" }}>
            <span style={{ color: "#b9b9c4", fontSize: 11, marginRight: 2 }}>trim</span>
            {[["black", "CAP_SHINY_BLACK"], ["gold", "CAP_SHINY_GOLD"],
              ["mt silver", "CAP_MATTE_SILVER"], ["sh silver", "CAP_SHINY_SILVER"],
              ["turquoise", "SPRAY_TURQUOISE"], ["red", "SPRAY_RED"]].map(([n, m]) => (
              <button key={m} onClick={() => { setTrimMat(m); setCapTune(null); }}
                      style={btn(trimMat === m)}>{n}</button>
            ))}
          </div>
        ) : null}
        {closure !== "none" ? (
          <div style={{ display: "flex", gap: 4, alignItems: "center",
                        margin: "0 0 6px", flexWrap: "wrap" }}>
            <span style={{ color: "#b9b9c4", fontSize: 11, marginRight: 2 }}>ball</span>
            {[["steel", "PART_BALL_STEEL"], ["plastic", "PART_BALL_PLASTIC"]].map(([n, m]) => (
              <button key={m} onClick={() => setBallMat(m)} style={btn(ballMat === m)}>{n}</button>
            ))}
            {closure === "rollerCapped" || closure === "capped" ? (<>
              <span style={{ color: "#b9b9c4", fontSize: 11, margin: "0 2px 0 8px" }}>cap</span>
              {[["black", "CAP_SHINY_BLACK"], ["white", "CAP_WHITE"],
                ["gold", "CAP_SHINY_GOLD"], ["mt gold", "CAP_MATTE_GOLD"],
                ["silver", "CAP_SHINY_SILVER"], ["mt silver", "CAP_MATTE_SILVER"],
                ["copper", "CAP_COPPER"], ["blk dot", "CAP_DOTS_BLACK"],
                ["pnk dot", "CAP_DOTS_PINK"], ["sl dot", "CAP_DOTS_SILVER"],
                ["blk T", "CAP_SHINY_BLACK_TALL_VIEW"], ["mtSl T", "CAP_MATTE_SILVER_TALL_VIEW"],
                ["lthr blk", "LEATHER_BLACK"], ["lthr brn", "LEATHER_BROWN"],
                ["lthr lbr", "LEATHER_LIGHT_BROWN"], ["lthr ivy", "LEATHER_IVORY"],
                ["lthr pnk", "LEATHER_PINK"]].map(([n, m]) => (
                // switching caps clears the tune override — every cap
                // arrives showing REGISTRY truth (a leftover roughness
                // override made shiny black read matte)
                <button key={m} onClick={() => { setCapMat(m); setCapTune(null); }}
                        style={btn(capMat === m)}>{n}</button>
              ))}
            </>) : null}
          </div>
        ) : null}
        {closure === "rollerCapped" || closure === "capped" || closure.startsWith("spray") || closure.startsWith("pump") ? (
          <div style={{ margin: "0 0 8px", padding: "6px 8px",
                        border: "1px solid #26262c", borderRadius: 4 }}>
            <div style={{ fontSize: 10, color: "#8a8a94", marginBottom: 4 }}>
              {closure === "rollerCapped" || closure === "capped" ? "cap" : "trim"} tuning — {closure === "rollerCapped" || closure === "capped" ? capMat : trimMat}{capTune ? " (edited)" : ""}
            </div>
            <Slider label="cap roughness" value={capTune?.roughness ?? 0.2}
                    min={0} max={0.8} step={0.01}
                    onChange={(v) => setCapTune((t) => ({ ...t, roughness: v }))} />
            <Slider label="cap env intensity" value={capTune?.envMapIntensity ?? 1.0}
                    min={0} max={2.5} step={0.05}
                    onChange={(v) => setCapTune((t) => ({ ...t, envMapIntensity: v }))} />
            <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
              <span style={{ color: "#b9b9c4", fontSize: 11 }}>cap color</span>
              <HexField value={capTune?.color ?? "#888888"}
                        onValid={(v) => setCapTune((t) => ({ ...t, color: v }))} />
              <button onClick={() => navigator.clipboard.writeText(
                        JSON.stringify({ [capMat]: capTune }, null, 2))}
                      style={btn(false)}>copy</button>
              <button onClick={() => setCapTune(null)} style={btn(false)}>reset</button>
            </div>
          </div>
        ) : null}
        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        margin: "2px 0 4px",
                        cursor: bakeMax != null ? "pointer" : "default",
                        opacity: bakeMax != null ? 1 : 0.45 }}>
          <input type="checkbox" checked={bakeLive} disabled={bakeMax == null}
                 onChange={(e) => setBakedMap(e.target.checked)} />
          <span>thicknessMap (baked)</span>
        </label>
        <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 6 }}>
          {bakeMax != null
            ? "per-texel thickness from Blender — thick heel darkens, thin " +
              "threads lighten. The thickness slider sets the CEILING each " +
              `texel scales from; ${(bakeMax * 1000).toFixed(1)} mm is metric-exact`
            : "no bake exists for this body yet — run bake_thickness.py"}
        </div>
        <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
          backside refraction + 8-sample transmission. Off = plain
          MeshPhysicalMaterial, a single flat backdrop lookup.
        </div>

        <label style={{ display: "flex", gap: 6, alignItems: "center", margin: "2px 0" }}>
          <input type="checkbox" checked={caustics}
                 onChange={(e) => setCaustics(e.target.checked)} />
          <span>caustics</span>
        </label>
        {caustics ? (
          <Slider label="caustic intensity" value={causticIntensity}
                  min={0} max={0.25} step={0.005} onChange={setCausticIntensity}
                  hint="light focused through the glass onto the surface" />
        ) : null}
        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        margin: "2px 0 10px" }}>
          <input type="checkbox" checked={ground}
                 onChange={(e) => setGround(e.target.checked)} />
          <span>ground + contact shadow</span>
        </label>

        <Section title="METAL STUDIO" />
        <div style={{ display: "flex", gap: 4, marginBottom: 4 }}>
          {([["key light", "key"], ["classic studio", "classic"]] as const).map(([n, id]) => (
            <button key={id} onClick={() => setMetalStudioId(id)}
                    style={btn(metalStudioId === id)}>{n}</button>
          ))}
        </div>
        <div style={{ fontSize: 10, color: "#8a8a94", marginBottom: 4 }}>
          the reflection itself — what shiny caps mirror. Dial it, then have
          the values locked.
        </div>
        <Slider label="ceiling (overhead sheen)" value={metalTune.ceiling}
                min={0} max={10} step={0.1}
                onChange={(v) => setMetalTune((t) => ({ ...t, ceiling: v }))} />
        <Slider label="band (level-on sheen)" value={metalTune.band}
                min={0} max={3} step={0.05}
                onChange={(v) => setMetalTune((t) => ({ ...t, band: v }))} />
        <Slider label="band height" value={metalTune.bandEl}
                min={-0.3} max={0.6} step={0.01}
                onChange={(v) => setMetalTune((t) => ({ ...t, bandEl: v }))} />
        <Slider label="band softness" value={metalTune.bandWidth}
                min={0.05} max={0.5} step={0.01}
                onChange={(v) => setMetalTune((t) => ({ ...t, bandWidth: v }))} />
        <Slider label="key softbox (the visible shine)" value={metalTune.key}
                min={0} max={14} step={0.2}
                onChange={(v) => setMetalTune((t) => ({ ...t, key: v }))} />
        <Slider label="key direction (deg)" value={metalTune.keyDeg}
                min={0} max={360} step={5}
                onChange={(v) => setMetalTune((t) => ({ ...t, keyDeg: v }))} />
        <Slider label="key width (deg)" value={metalTune.keyWidth}
                min={8} max={70} step={1}
                onChange={(v) => setMetalTune((t) => ({ ...t, keyWidth: v }))} />
        <Slider label="counter softbox" value={metalTune.counter}
                min={0} max={8} step={0.1}
                onChange={(v) => setMetalTune((t) => ({ ...t, counter: v }))} />
        <Slider label="accent strength" value={metalTune.lobe}
                min={0} max={1} step={0.02}
                onChange={(v) => setMetalTune((t) => ({ ...t, lobe: v }))} />
        <Slider label="accent direction (deg)" value={metalTune.lobeDeg}
                min={0} max={360} step={5}
                onChange={(v) => setMetalTune((t) => ({ ...t, lobeDeg: v }))} />
        <Slider label="floor darkness" value={metalTune.floor}
                min={0} max={0.3} step={0.005}
                onChange={(v) => setMetalTune((t) => ({ ...t, floor: v }))} />
        <div style={{ fontSize: 9, color: "#6f6f7d", margin: "2px 0 10px",
                      fontFamily: "monospace", userSelect: "all" }}>
          {JSON.stringify(metalTune)}
        </div>

        <Section title="ENVIRONMENT" />
        <div style={{ display: "flex", gap: 4, marginBottom: 4 }}>
          {(Object.keys(STUDIO_PRESETS) as StudioPresetId[]).map((id) => (
            <button key={id} onClick={() => { setStudioId(id); setBg(STUDIO_PRESETS[id].backdrop); }}
                    style={btn(studioId === id)}>
              {id === "softbox-tent" ? "tent" : id === "room" ? "room"
                : id === "mono-studio" ? "mono" : "rig (legacy)"}
            </button>
          ))}
        </div>
        <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 9 }}>
          the legacy rig&apos;s narrow hot rim lights are what paint hard
          vertical stripes down a cylinder
        </div>
        <label style={{ display: "flex", justifyContent: "space-between",
                        alignItems: "center", marginBottom: 9 }}>
          <span style={{ color: "#b9b9c4", fontSize: 11 }}>backdrop</span>
          <input type="color" value={bg} onChange={(e) => setBg(e.target.value)}
                 style={{ width: 54, height: 22, background: "none",
                          border: "1px solid #33333c" }} />
        </label>
        <div style={{ display: "flex", gap: 4, marginBottom: 10 }}>
          {[["bone", "#e9e6e0"], ["white", "#f7f7f7"], ["grey", "#8d8d94"],
            ["brown", "#3b2f27"], ["dark", "#15151a"]].map(([n, c]) => (
            <button key={n} onClick={() => setBg(c)} style={btn(bg === c)}>{n}</button>
          ))}
        </div>
        <Slider label="env intensity" value={envIntensity} min={0} max={4} step={0.05}
                onChange={setEnvIntensity} />
        <Slider label="env rotation °" value={envRot} min={0} max={360} step={1}
                onChange={setEnvRot} />
        <Slider label="exposure" value={exposure} min={0.2} max={2.5} step={0.01}
                onChange={setExposure} />

        <Section title="CAMERA" />
        <div style={{ display: "flex", gap: 4, marginBottom: 8 }}>
          <button onClick={resetView} style={btn(false)}>reset view</button>
          {(Object.keys(CAM_PRESETS) as CamPresetId[]).map((id) => (
            <button key={id} onClick={() => setCam(id)} style={btn(cam === id)}>
              {id === "threeQuarter" ? "¾" : id}
            </button>
          ))}
        </div>
        <Slider label="focal (fov°)" value={fov} min={14} max={60} step={1} onChange={setFov}
                hint="lower = longer lens, less product distortion" />
        <Slider label="distance (m)" value={distance} min={0.06} max={0.6} step={0.005}
                onChange={setDistance} />

        <Section title="EXPORT" />
        <button onClick={copyJson}
                style={{ ...btn(false), width: "100%", padding: "7px 0", marginBottom: 5 }}>
          {copied ? "copied ✓" : "Copy preset JSON"}
        </button>
        <button onClick={() => loadPreset(presetId)}
                style={{ ...btn(false), width: "100%", padding: "7px 0" }}>
          Reset to approved
        </button>
        <div style={{ fontSize: 10, color: "#6f6f7d", margin: "7px 0 12px" }}>
          Nothing is written to materials.json — that file is generated by
          materials.py and a hand edit would be lost on the next extract.
        </div>

        <Section title="REFERENCE" />
        <input type="file" accept="image/*"
               onChange={(e) => onPickRef(e.target.files?.[0] ?? null)}
               style={{ fontSize: 10, color: "#9a9aa6", marginBottom: 7, width: "100%" }} />
        {refUrl ? (
          <>
            <div style={{ display: "flex", gap: 4, marginBottom: 8 }}>
              {(["off", "side", "overlay"] as const).map((mode) => (
                <button key={mode} onClick={() => setRefMode(mode)} style={btn(refMode === mode)}>
                  {mode}
                </button>
              ))}
            </div>
            {refMode === "overlay" ? (
              <Slider label="overlay opacity" value={refOpacity} min={0} max={1} step={0.01}
                      onChange={setRefOpacity} />
            ) : null}
            <Slider label="ref scale" value={refScale} min={0.3} max={2.5} step={0.01}
                    onChange={setRefScale}
                    hint="framing need not match — line it up here" />
            <Slider label="ref offset X" value={refX} min={-300} max={300} step={1}
                    onChange={setRefX} />
            <Slider label="ref offset Y" value={refY} min={-300} max={300} step={1}
                    onChange={setRefY} />
            <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
              Held locally — nothing is uploaded. Your photo&apos;s LIGHTING is not
              copied into the browser; only the glass is being compared.
            </div>
          </>
        ) : (
          <div style={{ fontSize: 10, color: "#6f6f7d", marginBottom: 10 }}>
            Load a photo of the real bottle. Cap off, background visible beside
            it, not blown out. Size and framing do not matter.
          </div>
        )}

        <Section title="MODEL" />
        <label style={{ display: "flex", gap: 6, alignItems: "center",
                        marginBottom: 8, cursor: hasThreaded ? "pointer" : "default",
                        opacity: hasThreaded ? 1 : 0.45 }}>
          <input type="checkbox" checked={threaded && hasThreaded} disabled={!hasThreaded}
                 onChange={(e) => setThreaded(e.target.checked)} />
          <span>threaded neck (real helix)</span>
        </label>
        {bodies.map((b, i) => (
          <button key={b.bodyId} onClick={() => setBodyIdx(i)}
                  style={{ display: "block", width: "100%", textAlign: "left",
                           padding: "4px 6px", marginBottom: 2, borderRadius: 4,
                           cursor: "pointer", fontSize: 10.5,
                           border: "1px solid " + (i === bodyIdx ? "#6a6af0" : "transparent"),
                           background: i === bodyIdx ? "#23234a" : "transparent",
                           color: "#d2d2d8" }}>
            <div style={{ whiteSpace: "nowrap", overflow: "hidden",
                          textOverflow: "ellipsis" }}>{b.bodyId}</div>
            <div style={{ color: "#7d7d88" }}>{b.shape} · {b.skuCount} SKUs</div>
          </button>
        ))}
      </aside>
    </div>
  );
}

function Section({ title }: { title: string }) {
  return <div style={{ fontSize: 10, letterSpacing: 1, color: "#6a6af0",
                       borderTop: "1px solid #26262c", paddingTop: 9,
                       margin: "12px 0 8px" }}>{title}</div>;
}

function Row({ k, v, good }: { k: string; v: string; good?: boolean }) {
  return (
    <div style={{ display: "flex", gap: 8 }}>
      <span style={{ color: "#7d7d88", minWidth: 108 }}>{k}</span>
      <span style={{ color: good === undefined ? "#d2d2d8" : good ? "#5fd68a" : "#ff6b6b" }}>{v}</span>
    </div>
  );
}
