// GENERATED by scripts/paperdoll/emit_tokens_ts.py from data/paper-doll/tokens.json.
// Do not edit by hand: run the script, or the SKU vocabulary and the page disagree.
// 2432 of 2473 catalogue SKUs parse from this vocabulary (35 finishes, 67 spellings).
// tokens.json generatedAt 2026-09-01T23:38:55, reviewedAt not yet reviewed.

export type FinishToken = { label: string; swatchName: string };

/** Website-SKU finish suffixes, longest first. */
export const WEBSITE_SKU_FINISHES: Array<[string, FinishToken]> = [
    ["MtSlClOvrCap", { label: "Matte Silver Clear Overcap", swatchName: "Matte Silver Clear Overcap" }],   // 1
    ["ShnGlWhite", { label: "Shiny Gold White", swatchName: "Shiny Gold White" }],   // 3
    ["ShnSlWhite", { label: "Shiny Silver White", swatchName: "Shiny Silver White" }],   // 3
    ["WhtClOvrCp", { label: "White Clear Overcap", swatchName: "White Clear Overcap" }],   // 6
    ["ClrOvrCap", { label: "Clear Overcap", swatchName: "Clear Overcap" }],   // 29
    ["LBrwnLthr", { label: "Light Brown Leather", swatchName: "Light Brown Leather" }],   // 30
    ["BrwnLthr", { label: "Brown Leather", swatchName: "Brown Leather" }],   // 30
    ["ClOvrCap", { label: "Clear Overcap", swatchName: "Clear Overcap" }],   // 29
    ["ShnGlBlk", { label: "Shiny Gold Black", swatchName: "Shiny Gold Black" }],   // 3
    ["ShnSlBlk", { label: "Shiny Silver Black", swatchName: "Shiny Silver Black" }],   // 3
    ["BlkLthr", { label: "Black Leather", swatchName: "Black Leather" }],   // 30
    ["BlkMatt", { label: "Matte Black", swatchName: "Matte Black" }],   // 29
    ["BluMatt", { label: "Matte Blue", swatchName: "Matte Blue" }],   // 19
    ["IvyLthr", { label: "Ivory Leather", swatchName: "Ivory Leather" }],   // 30
    ["MattBlk", { label: "Matte Black", swatchName: "Matte Black" }],   // 29
    ["PnkLthr", { label: "Pink Leather", swatchName: "Pink Leather" }],   // 30
    ["CuMatt", { label: "Matte Copper", swatchName: "Matte Copper" }],   // 63
    ["GlMatt", { label: "Matte Gold", swatchName: "Matte Gold" }],   // 139
    ["MattCu", { label: "Matte Copper", swatchName: "Matte Copper" }],   // 63
    ["MattGl", { label: "Matte Gold", swatchName: "Matte Gold" }],   // 139
    ["MattSl", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["MtSlCl", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["ShnBlk", { label: "Shiny Black", swatchName: "Shiny Black" }],   // 226
    ["SlMatt", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["Black", { label: "Black", swatchName: "Black" }],   // 172
    ["BlkMt", { label: "Matte Black", swatchName: "Matte Black" }],   // 29
    ["BlkSh", { label: "Shiny Black", swatchName: "Shiny Black" }],   // 226
    ["BluMt", { label: "Matte Blue", swatchName: "Matte Blue" }],   // 19
    ["ClBlk", { label: "Black", swatchName: "Black" }],   // 172
    ["ClWht", { label: "White", swatchName: "White" }],   // 142
    ["Clear", { label: "Clear", swatchName: "Clear" }],   // 5
    ["Green", { label: "Green", swatchName: "Green" }],   // 4
    ["IvyGl", { label: "Ivory + Gold", swatchName: "Ivory + Gold" }],   // 58
    ["IvySl", { label: "Ivory + Silver", swatchName: "Ivory + Silver" }],   // 60
    ["ShBlk", { label: "Shiny Black", swatchName: "Shiny Black" }],   // 226
    ["ShnGl", { label: "Shiny Gold", swatchName: "Shiny Gold" }],   // 177
    ["ShnSl", { label: "Shiny Silver", swatchName: "Shiny Silver" }],   // 189
    ["White", { label: "White", swatchName: "White" }],   // 142
    ["Blck", { label: "Black", swatchName: "Black" }],   // 172
    ["Blue", { label: "Blue", swatchName: "Blue" }],   // 7
    ["ClWh", { label: "White", swatchName: "White" }],   // 142
    ["CuMt", { label: "Matte Copper", swatchName: "Matte Copper" }],   // 63
    ["GlMt", { label: "Matte Gold", swatchName: "Matte Gold" }],   // 139
    ["GlSh", { label: "Shiny Gold", swatchName: "Shiny Gold" }],   // 177
    ["MtGl", { label: "Matte Gold", swatchName: "Matte Gold" }],   // 139
    ["MtSl", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["Pink", { label: "Pink", swatchName: "Pink" }],   // 106
    ["ShGl", { label: "Shiny Gold", swatchName: "Shiny Gold" }],   // 177
    ["ShSl", { label: "Shiny Silver", swatchName: "Shiny Silver" }],   // 189
    ["SlMt", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["SlSh", { label: "Shiny Silver", swatchName: "Shiny Silver" }],   // 189
    ["Blk", { label: "Black", swatchName: "Black" }],   // 172
    ["Blu", { label: "Blue", swatchName: "Blue" }],   // 7
    ["Lvn", { label: "Lavender", swatchName: "Lavender" }],   // 61
    ["MtS", { label: "Matte Silver", swatchName: "Matte Silver" }],   // 297
    ["Nat", { label: "Natural", swatchName: "Natural" }],   // 2
    ["Pnk", { label: "Pink", swatchName: "Pink" }],   // 106
    ["Red", { label: "Red", swatchName: "Red" }],   // 65
    ["Tur", { label: "Turquoise", swatchName: "Turquoise" }],   // 6
    ["Wht", { label: "White", swatchName: "White" }],   // 142
    ["Cl", { label: "Clear", swatchName: "Clear" }],   // 5
    ["Cu", { label: "Copper", swatchName: "Copper" }],   // 77
    ["Gl", { label: "Gold", swatchName: "Gold" }],   // 121
    ["Gr", { label: "Green", swatchName: "Green" }],   // 4
    ["Lv", { label: "Lavender", swatchName: "Lavender" }],   // 61
    ["Sl", { label: "Silver", swatchName: "Silver" }],   // 90
    ["Wh", { label: "White", swatchName: "White" }],   // 142
];

/**
 * The finish a website SKU spells, or null. The decorative-ring modifier is
 * stripped first: a ring variant is the same closure in the same finish.
 */
/** Modifiers that may follow the finish, with how they read in a label. */
const MODIFIER_SUFFIXES: Array<[string, string]> = [
    ["Dot", "Dotted"],
    ["Tall", "Tall"],
    ["Short", "Short"],
    ["Sht", "Short"],
];

export function getFinishFromWebsiteSku(websiteSku: string | null | undefined): FinishToken | null {
    if (!websiteSku) return null;
    // the decorative-ring modifier is a variant of the same closure in the same finish
    let stem = websiteSku.trim().replace(/Rng$/, "");
    // a modifier can follow the finish (SlDot, ShnBlkTall); take it off, then read
    // the finish underneath and put the modifier back into the label
    let suffix: string | null = null;
    for (const [token, label] of MODIFIER_SUFFIXES) {
        if (stem.endsWith(token) && stem.length > token.length) { stem = stem.slice(0, -token.length); suffix = label; break; }
    }
    for (const [token, finish] of WEBSITE_SKU_FINISHES) {
        if (stem.endsWith(token) && stem.length > token.length) {
            return suffix
                ? { label: `${finish.label} ${suffix}`, swatchName: finish.swatchName }
                : finish;
        }
    }
    return null;
}
