from pathlib import Path
import json,hashlib,html
from PIL import Image,ImageDraw
ROOT=Path.cwd();ID='cylinder-final38-2026-09-13';R=ROOT/'docs/reviews'/ID;PUB=ROOT/'public/reviews'/ID;PUB.mkdir(exist_ok=True)
p=R/'prepared-v2.json';data=json.loads(p.read_text());digest=hashlib.sha256(p.read_bytes()).hexdigest();esc=lambda s:html.escape(str(s or ''))
for batch in range((len(data['rows'])+5)//6):
 canvas=Image.new('RGB',(1320,980),'#eeede8')
 for i,row in enumerate(data['rows'][batch*6:batch*6+6]):
  x=i%3*440;y=i//3*490;d=ImageDraw.Draw(canvas);d.text((x+6,y+6),row['sku'],fill='black')
  for j,v in enumerate(row['views']):
   im=Image.open(ROOT/'public'/v['url'].lstrip('/')).convert('RGB');im.thumbnail((218,430));canvas.paste(im,(x+j*220,y+30));d.text((x+j*220+8,y+455),v['label'],fill='black')
  d.text((x+6,y+472),'Pair error '+str(row['pairCheck']['bodyMeanError']),fill='black')
 canvas.save(R/f'final-pairs-{batch+1}.jpg')
parts=[]
for i,row in enumerate(data['rows']):
 before=row['before'][0];views=[(before,'Approved front · unchanged')]
 if row['views'][0]['sha256']!=before['sha256']:views.append((row['views'][0],'Prepared master front'))
 if len(row['before'])>1:views.append((row['before'][1],'Previous cap-off'))
 views.append((row['views'][1],'Prepared cap-off'))
 figures=''.join(f'<figure><figcaption>{esc(label)}</figcaption><a href="{esc(v["url"])}" target="_blank"><img src="{esc(v["url"])}" width="1000" height="1100" alt="{esc(row["sku"])} {esc(label)}"></a><details><summary>Image fingerprint</summary><code>{v["sha256"]}</code></details></figure>' for v,label in views)
 source_pending=row['classification'] in ['Plain short cap','Flip top'];notes=''.join(f'<li>{esc(n)}</li>' for n in row['notes'])
 parts.append(f'<article data-kind="{esc(row["classification"])}" data-sku="{esc(row["sku"])}"><div class="eyebrow">{i+1:02} / 38 · {esc(row["classification"])}</div><h2>{row["capacityMl"]} mL · {esc(row["color"])} · {esc(row["capColor"])}</h2><p class="sku">{esc(row["sku"])}</p><div class="views" style="--cols:{len(views)}">{figures}</div><p class="metric">Body alignment: {row["pairCheck"]["bodyMeanError"]:.2f} / 255 · limit 12. Same 1000 × 1100 canvas and zoom.</p><details><summary>Source and preparation notes</summary><p>{esc(row["itemName"])}</p><ul>{notes}</ul><code>{row["binding"]}</code></details>{"<p class=source-note>Source decision: retain the approved original legacy front. The ledger currently requires a master source for this view.</p>" if source_pending else "<p class=pass>Master sources verified. Original source approval remains saved.</p>"}</article>')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Cylinder · final 38 plate pairs</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f3ef;color:#253c30;font:16px/1.55 system-ui}main{max-width:1360px;margin:auto;padding:36px 24px 90px}h1,h2{font-family:Georgia,serif;font-weight:400;line-height:1.2}h1{font-size:clamp(36px,5vw,60px)}h2{font-size:30px}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.09em;font-weight:650}a{color:inherit}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.stat,article{background:white;border:1px solid #d7dfd6;border-radius:12px;padding:20px}.stat{border-top:4px solid #598765}.stat strong{font-size:32px;display:block}.stat.blue{border-color:#719dbb}.stat.amber{border-color:#c7994f}.notice,.source-note{padding:16px;background:#fff3db;border-radius:8px}.pass,.metric{padding:12px;background:#eff6ef;border-radius:8px}.toolbar{display:flex;flex-wrap:wrap;gap:12px;align-items:center;padding:16px 0;position:sticky;top:0;background:#f5f3ef;z-index:2}input,select,button{font:inherit;padding:10px;border:1px solid #a6b6a9;border-radius:6px}button{cursor:pointer;background:#254c37;color:white}button:disabled{opacity:.5;cursor:default}article{margin:20px 0 32px;padding:24px;scroll-margin-top:90px}.views{display:grid;grid-template-columns:repeat(var(--cols),minmax(0,1fr));gap:14px}figure{margin:0;min-width:0}figure img{display:block;width:100%;height:auto;aspect-ratio:10/11;background:white}figcaption{font-size:13px;font-weight:650;border-bottom:2px solid #b5caba;text-align:center;padding:8px;min-height:48px}details{font-size:14px;color:#5a7062;margin-top:12px}code{font-size:11px;overflow-wrap:anywhere;display:block}.sku{color:#617365;font-size:14px}.approval{padding:26px;background:white;border:2px solid #567c64;border-radius:12px}label.ack{display:flex;gap:12px;margin:18px 0}.ack input{flex:none;width:20px;height:20px}#status{white-space:pre-wrap}footer{margin-top:28px;font-size:12px;color:#617365}[hidden]{display:none!important}@media(max-width:650px){main{padding:22px 12px 60px}.stats{grid-template-columns:repeat(2,1fr)}article{padding:14px}.views{gap:5px}figcaption{font-size:10px;padding:4px}.toolbar{position:static}h2{font-size:25px}}
</style><main><a href="/team/asset-ledger?preview=1&family=Cylinder">← Cylinder ledger</a><header><p class="eyebrow">Cylinder · final plate reconciliation</p><h1>All 38 remaining pairs.</h1><p>Your 398 completed plates stay intact. Every remaining configuration now has a prepared cap-on / cap-off pair. Existing front approvals are preserved.</p><div class="stats"><div class="stat"><strong>398 / 436</strong>Already complete and indexed</div><div class="stat blue"><strong>38</strong>Prepared pairs on this sheet</div><div class="stat blue"><strong>0</strong>Missing candidate cap-off views</div><div class="stat amber"><strong>27</strong>Legacy-source decisions</div></div><p class="notice"><strong>The one source decision:</strong> 24 short-cap fronts and three plastic flip-top fronts are original legacy website photographs you already approved. Exact master finish files remain unmatched. This sheet retains those fronts with honest source records. The short-cap glass comes from the master; the three plastic cap-off photos come from their exact product pages at the original 360 × 480 resolution. Approving their use accepts that documented source basis; it does not turn them into Photoshop renders.</p><p>All paired glass alignment checks pass. Four roller pairs reuse their previously approved final files. The corrected roller and new cap-off files need this batch review. No new image has been published.</p><a href="#review">Go to batch approval ↓</a></header><div class="toolbar"><label>Find a bottle <input id="search" type="search" placeholder="Size, finish or SKU"></label><label>Show <select id="filter"><option value="">All 38 pairs</option><option>Plain short cap</option><option>Sprayer</option><option>Roller</option><option>Flip top</option></select></label><span id="count">38 pairs</span></div>'''+''.join(parts)+'''
<section class="approval" id="review"><h2>Approve this final batch</h2><p>This registers the exact new image files and the retained original-source decision. Existing approvals stay saved. Publication still requires a ship instruction for this release.</p><label class="ack"><input type="checkbox" id="visual">I reviewed the prepared pairs and approve the new image files shown.</label><label class="ack"><input type="checkbox" id="source">I accept the original legacy photographs for the 27 identified rows, including the original resolution of the three plastic cap-off photos.</label><button id="approve" disabled>Approve final Cylinder batch</button><p id="status" role="status">Loading review checks…</p></section><footer>Review revision 2 · <a href="prepared-v2.json">Exact preparation record</a><code>'''+digest+'''</code></footer></main><script>
const search=document.querySelector('#search'),filter=document.querySelector('#filter'),cards=[...document.querySelectorAll('article')];function update(){let count=0;for(const c of cards){c.hidden=!(c.textContent.toLowerCase().includes(search.value.toLowerCase())&&(!filter.value||c.dataset.kind===filter.value));if(!c.hidden)count++;}document.querySelector('#count').textContent=count+' pairs';}search.oninput=update;filter.onchange=update;
let state=null;const approve=document.querySelector('#approve'),status=document.querySelector('#status'),visual=document.querySelector('#visual'),source=document.querySelector('#source');function ready(){approve.disabled=!state||state.status==='approved'||!visual.checked||!source.checked||[...document.images].some(i=>!i.complete||!i.naturalWidth);}visual.onchange=ready;source.onchange=ready;for(const im of document.images){im.addEventListener('load',ready);im.addEventListener('error',()=>{status.textContent='An image did not load. Reload before approving.';ready();});}
fetch('/api/asset-ledger/cylinder-final-plates').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(d.token!==document.querySelector('footer code').textContent.trim())throw Error('This comparison changed. Reload the final review sheet.');state=d;status.textContent=d.status==='approved'?'Batch approval saved. Awaiting release-specific ship.':'Exact image and source checks passed. Review the pairs above.';ready();}).catch(e=>{status.textContent=e.message;});
approve.onclick=async()=>{approve.disabled=true;status.textContent='Verifying and recording the batch…';try{const r=await fetch('/api/asset-ledger/cylinder-final-plates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:state.token,revision:state.revision,visualApproved:visual.checked,legacySourcesAccepted:source.checked})});const d=await r.json();if(!r.ok)throw Error(d.error);state=d;status.textContent='Your final batch approval is saved to the exact image hashes. Publication awaits ship for Cylinder final plate release 2026-09-13.';}catch(e){status.textContent=e.message;}ready();};
</script></html>'''
(R/'index.html').write_text(page);(PUB/'index.html').write_text(page);(PUB/'prepared-v2.json').write_bytes(p.read_bytes());print('Built sheet',digest)
